### ISSUE TITLE
Add issue templates to Scribe-iOS

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#101]
It would be good if Scribe-iOS had some base issue templates for future contributors.

The following [YouTube video](https://www.youtube.com/watch?v=qQE1BUkf2-s) has a good description of how to set them up using `.yml` files for custom structures, and [Signal's iOS templates section](https://github.com/signalapp/Signal-iOS/tree/master/.github/ISSUE_TEMPLATE) is another place to look for how to set up the configuration files. 

Templates could be made for the following: bugs, feature requests, data, new keyboards, and questions. `blank_issues_enabled: false` could then be set in the `config.yml` file of the `.github/ISSUE_TEMPLATE` directory.

**Comment by RishiKumarRay** [comment]
I would like to work on this also can i generate more than 1 PR to complete these tasks?

**Comment by andrewtavis** [comment]
Hi @RishiKumarRay :)

You'd be more than welcome to work on this. And yes, you could do more than one PR.

Generally how I'm thinking about this: I think that the `.github/ISSUE_TEMPLATE/config.yml` likely will just have `blank_issues_enabled: false`, as I'm hoping that the five templates in the issue will be enough to cover all potential issues. From there we'll need to have separate `.yml` files per template in `.github/ISSUE_TEMPLATE/`.

Feel free to check in with me if you have any questions, and thanks so much for reaching out!

**Comment by andrewtavis** [comment]
There's no work being done on [Scribe-Android](https://github.com/scribe-org/Scribe-Android) or [Scribe-Desktop](https://github.com/scribe-org/Scribe-Desktop) (yet 😊), but you'd also be welcome to port your solutions to this issue over to those repositories. Would be good to get an early contribution into those code bases :)

**Comment by RishiKumarRay** [comment]
@andrewtavis Hi, Thankyou for assigning
I will be adding files in Upcoming PR
Currently I have added PR for Feature template
The config.yml , i will be adding that at the end 
please review this PR #102

**Comment by RishiKumarRay** [comment]
@andrewtavis Please do review this PR so that I can work on other files , Thanks

**Comment by andrewtavis** [comment]
@RishiKumarRay, so far looks good to me :) 

Your naming criteria is close to what I was thinking. Let's agree on those so I don't need to edit the files and potentially lose your contribution credit. Let's do `feature_request.yml`, `bug_report.yml`, `data.yml`, `new_keyboard.yml`, and `question.yml`. Each of those should be automatically labeled with the corresponding issue using the `labels:` section of the `.yml` files (I'll note this in the issue).

I'll make some comments and then will start winding my day down (is late in Berlin). Feel free to send along any other PRs that you want to. There might be some edits based on what I'd like the workflow to be, but I'm very happy you're taking this on!

**Comment by RishiKumarRay** [comment]
@andrewtavis True , I have updated the file name you can now check the latest commit . For today this was only PR , I will work on others file tomorrow. If there are more suggestions please do let me know or else you can merge this :) Thanks

**Comment by andrewtavis** [comment]
Other suggestions are in the PR :) Thanks again for your work! You're more than welcome to create similar PRs for the other files based on what I talked about. Really am happy for the help 😊

**Comment by RishiKumarRay** [comment]
Sure I will look into all this and come up with changes

**Comment by andrewtavis** [comment]
Looking forward :)

**Comment by andrewtavis** [comment]
@RishiKumarRay, another random thing for this that I wanted to check, what do you think of emojis in the names of the issues? I think it might make them a bit more clear from the outset, and there are standard emojis for GitHub that can [be found here](https://gitmoji.dev/). Basically the idea on this would be that the `name:` for each of the templates we've talked about would be:

`✨ Feature request`
`🐛 Bug report`
`🗃️ Data and Wikidata`
`🌐 New keyboard`
`❓ Question`

**Comment by andrewtavis** [comment]
@RishiKumarRay, done with the edits based on how it was looking when I was trying it :) I gotta say, that there issue template really is a thing of beauty 😊😊

Lemme know if you don't agree with some of the changes, but aside from that you're more than welcome to work on the others with this one as a basic guide.

Again and again, thanks for your work on this!

**Comment by RishiKumarRay** [comment]
@andrewtavis Thanks, I agree with the touch you gave to the templates , its awesome , Now I am working on bug template , let's discuss that too when i finish and raise a PR for that

**Comment by andrewtavis** [comment]
Wonderful! Thanks for your efforts!

**Comment by RishiKumarRay** [comment]
@andrewtavis please review the bug template #105

**Comment by andrewtavis** [comment]
@RishiKumarRay, I did some more edits than I expected when I merged, so please take no offense :) #106 is an example of an issue written with the new version. I thought that keeping the number of text areas down would be good, and really simplifying the device and version areas of the form might streamline it for people.

**Comment by andrewtavis** [comment]
Also another thing that just went through in b6fb208, I think it'd be great if we're hyperlinking the issues that the person should be searching for before posting the issue (makes it easy for them to open them in a new window and do a quick search). The URLs for that would be:

Open issues: https://github.com/scribe-org/Scribe-iOS/issues
Open and closed issues: https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue

Let me know which one you're going to start on next! This is really going great 😊

**Comment by RishiKumarRay** [comment]
Hi, @andrewtavis I have gone through the changes and let me tell the enhancement you did completely fits the project , It looks great and The issues link is perfect too and yeah it will help them search the issues easily. you did some preety cool things.
Next I would like to pickup 🗃️ Data and Wikidata , Can you give me a format idea for this, How you want this , if there is any example for it then it would be best.

**Comment by andrewtavis** [comment]
@RishiKumarRay, thanks for the feedback on it! Glad that you like the changes. I had a very solid baseline to go from :) :)

`Data and Wikidata` is gonna be really hard. As I'm writing this I'm going through all the issues marked `data`. The big thing is that we want experienced Wikidata users to be able to quickly see what's up with the issue and address it given the word or property in question. It could be something simple like "Hey, this conjugation for this verb is wrong" to something massive like we should add all translations from Spanish to German so that Spanish speakers can use Scribe to help them with their German :) Wikidata's linguistic data is also a bit hard for people to find, so I should write something that helps people find it.

The following are things that could be included:
- What languages is the issue for, with this being an `input` type with all the current Scribe languages as a `prompt` in alphabetical order separated by commas
  - I'm thinking let's do `input` instead of `checkboxes` as these lists will only get longer and then we'll need to edit it
- Word type could be another `input` type with all the types of words that Scribe deals with `nouns, verbs, translations, adjectives, prepositions, etc` as the prompt
- What's being done with the data as far as does it need to be added to Scribe or added to Wikidata is also something that could be included
  - For this we can do a drop down and use some terms from data engineering
  - The first dropdown option can read `ETL: Wikidata to Scribe` where ETL refers to Extract, Transform, Load - the process by which data gets from a central data source to the end user (I figure I'll explain this, but sorry if you know this and I'm boring you 😋)
  - The second dropdown option can read `ELT: Add to Wikidata` where ELT is Extract, Load, Transform - the process by which raw/collected data is added to the central database where it can then be accessed by ETL processes
  - The third dropdown can then be `ETL and ELT` where the user will know what these terms mean :)
- From there we have the setting for the issue, and we then need to know what the user wants to report about
  - This will be a text field
  - We'll need a prompt asking them about what they want
  - It'd also be good to give them some useful things in the `description` in this case - maybe two lines:
    - You can search Wikidata for language data be putting `L:` at the start of a [search](https://www.wikidata.org/w/index.php?search=&search=&title=Special%3ASearch&go=Go)
      - This is a helpful tip I got from their product owner :)
    - I'll try to think of something else that could help (this is already a ton!)
- And after comes our signature thank you message 😊 I think something like `Thank you for supporting Scribe and Wikidata create free information platforms!` - but lemme know what you think on this :)

In the above, if we're mentioning Wikidata let's make it a link so they can go there easily. That's https://www.wikidata.org/.

I'm at your service if you have any questions on the above, and again thanks for everything!

**Comment by andrewtavis** [comment]
Also I wanted to let you know that the next updates for the project are going to be design based. Over the next week a friend here in Berlin and I are going to be revamping the whole look of the app and keyboards, as he has the design experience needed to direct me on the development side. The keyboards are going to look a lot more modern, and the app icon/logo will also get a new look.

Just don’t be surprised when things look a bit different here soon :) :)

**Comment by RishiKumarRay** [comment]
@andrewtavis Wow! happy to hear that, I will be looking forward to the changes.

**Comment by RishiKumarRay** [comment]
@andrewtavis I have gone through all the format you suggested, and made this PR , Please do review and let me know the changes.

**Comment by andrewtavis** [comment]
@RishiKumarRay, thanks again so much for putting this together! The baseline was really helpful to work from. The above commits are the edits I did for this. I ended up taking out the word types section as I thought it was out of place when I finally looked at it (sorry for suggesting it in the first place). Other things were basic edits of the prompts, and I had the idea of using markdown to put the "tips" under the text area :) 

Let me know what you think of the end result, and also what the next template you want to tackle would be 😊 We definitely got the hard one finished with this one!

**Comment by andrewtavis** [comment]
@RishiKumarRay, we'll see how these work once we have some more contributors, but I gotta say the templates are looking so professional :) Really glad to have them!

**Comment by RishiKumarRay** [comment]
That looks great @andrewtavis I saw the changes , they are good and important too , Thanks 
I would like to work next on 🌐 New keyboard , This looks preety Interesting too, Can you give me idea about this too , like you gave for the last one, Thanks for that. Yeah I am excited too when contributors will start using this templates . Lets finish this all.

**Comment by andrewtavis** [comment]
@RishiKumarRay, thanks for the feedback on the changes :) Glad you like them.

The big thing for new keyboards would be how much data is available on Wikidata, and what kind of support is necessary. The following are things that could be included:
- labels: "-new keyboard-"
- The terms that we've had at the top of each of the templates, but just open issues
- We can do a `checkboxes` next asking what word types need support with the options being nouns, verbs, adjectives and prepositions
- Then likely what would be best is a `textarea` where they can describe what kind of support is needed - maybe a prompt of "Explain the language a bit including why support is needed for certain word types, and tell us how Scribe can help people type in it."
- After that say an `input` field that's asking for current amounts of data on Wikidata (this wouldn't be required)
  - For this, I'll write a query that people can use to check totals for the language that we can direct people to in a comment
  - They'll be able to go to Wikidata's query service and just put that query in, select their language, and run it
  - You can get started without this if you want though :)
- From there we can sign off with a thank you - maybe "Thanks for sharing your interest in bringing another language to Scribe!"

Let me know if you have any questions! Thanks again and again for your help! 😊

**Comment by RishiKumarRay** [comment]
Hi, @andrewtavis i have tried to put up everything as you said , let me know if there are any changes, thanks

**Comment by andrewtavis** [comment]
@RishiKumarRay, I screwed up in the review and didn't pick something up. The file that you submitted was named `new_keyword`, not `new_keyboard`. I was hoping that in changing the file name it would retain credit to you as an author, but it didn't....

Can you submit a PR with some changes to the document so you can get credit? Things that still need to be done include:
- Change the description from `Help Scribe add a new language keyboard!` to `Suggest a new language keyboard for Scribe!`
- Change the thank you message from `Thanks for showing interest in bringing another language to Scribe!` to `Thanks for your interest in adding another Scribe keyboard!`
- Let's also give this one a `title` parameter at the top: `Add "language" keyboard`
- And lets also add one more item to the `terms` field: `This issue is about one language, and I've changed the title to reflect this`

The last point is that it'd be better to have different issues for different languages, not "Add Danish, Finish and Norwegian keyboards"

Very sorry for the mixup and sending you a bit of extra work to do!

**Comment by andrewtavis** [comment]
From here we just have `❓ Question` left, which should be asking people if they have a question or want to start a discussion. It should have the terms at the top and be labeled as "question", but aside from that I'm not really sure that it'll have much more than a `textarea` with a prompt :)

From there we add the `.github/ISSUE_TEMPLATE/config.yml` file and we're done! 🎉

**Comment by RishiKumarRay** [comment]
@andrewtavis No problem , I understand,  the last point "The last point is that it'd be better to have different issues for different languages, not "Add Danish, Finish and Norwegian keyboards". where i have to put this ?

**Comment by andrewtavis** [comment]
@RishiKumarRay, that's just a comment about why I included the `This issue is about one language, and I've changed the title to reflect this` term :) You don't need to add it to the form :)

Thanks for checking!

**Comment by andrewtavis** [comment]
Feel free to send along the edits PR and the question one too if you want. I'm volunteering today, so if I don't get to them quickly I'll merge them when I get home :)

**Comment by RishiKumarRay** [comment]
@andrewtavis I am going to complete everything today itself , then maybe will work on some more thank , let me finish this then we will discuss that too

**Comment by RishiKumarRay** [comment]
sure no problem , you can merge them whenever you are free , Its just that i feel i should complete everything today

**Comment by andrewtavis** [comment]
Finish it when you need/want to. This all has been a great help, and has been going very quickly :)

**Comment by RishiKumarRay** [comment]
@andrewtavis I have generated PR with question template along with added changes to keyboard that you suggested. Please review whenever you are free , I am going out for few hours , I will be working on config after returning. Thanks also please let me know if you anything else added to question template. Thanks

**Comment by andrewtavis** [comment]
@RishiKumarRay alright! Looks like these are done :) This is really great 😊 

Could I ask you to check the [New keyboard](https://github.com/scribe-org/Scribe-iOS/issues/new?assignees=&labels=new+keyboard&template=new_keyboard.yml&title=Add+%3Clanguage%3E+keyboard) issue template and see if the `Available data` section makes sense? I wrote the query I talked to you about that would give people the totals for a given language, and I just want to know if you think someone would understand what that's saying there :) Feel free to say it's confusing!

**Comment by andrewtavis** [comment]
You're free to send along a `config.yml` whenever. To my knowledge that should just have `blank_issues_enabled: false`, but let me know if you have other ideas :)

Thanks again!

**Comment by RishiKumarRay** [comment]
@andrewtavis I was thinking we should put some contacts in config.yml , where anyone can contact you , i see there is an option of contacts too

**Comment by RishiKumarRay** [comment]
@andrewtavis for available data , I don't think , maybe we can include this in future when people start opening up issues so that we have more clear idea , how it is going

**Comment by andrewtavis** [comment]
> @andrewtavis I was thinking we should put some contacts in config.yml , where anyone can contact you , i see there is an option of contacts too

@RishiKumarRay, I was seeing that you can put contacts in the links as well. The email that's for Scribe  - scribe.language@gmail.com - is on the organization's page. I think that it's ok in that case to not put contact information so that people are pushed to open an issue rather than emailing. The `Question` template also allows them to just send a message to the team, so everyone should be able to find something :)

> @andrewtavis for available data , I don't think , maybe we can include this in future when people start opening up issues so that we have more clear idea , how it is going

I agree 😊 I was trying to make it work, but you're right that this will likely just confuse people and get them to not send the issue. Thanks for your feedback! 3735114 removes the section :)

**Comment by andrewtavis** [comment]
c8d3bf3 added in a `Contribution` section to `New keyboard` like we have for `Feature request`. I think that's a good solution, but please let me know what your thoughts are :) That way we can get an idea of what the person wants to contribute, and I'll run the query for the data totals whenever someone posts a new keyboard issue 😊

**Comment by RishiKumarRay** [comment]
@andrewtavis I have raised a PR for config file please do review

**Comment by RishiKumarRay** [comment]
> [c8d3bf3](https://github.com/scribe-org/Scribe-iOS/commit/c8d3bf34c1ad4a19979165a13c6bab71dcb323f3) added in a `Contribution` section to `New keyboard` like we have for `Feature request`. I think that's a good solution, but please let me know what your thoughts are :) That way we can get an idea of what the person wants to contribute, and I'll run the query for the data totals whenever someone posts a new keyboard issue blush

yeah this looks good

**Comment by RishiKumarRay** [comment]
@andrewtavis i was thinking of adding something like a greeting bot with messages for people when they open an issue or Raise a PR Like for issue they will get a message to please wait unless they are assigned and for PR they will get a message that thankyou for raising a PR , wait until your PR gets reviewed

**Comment by andrewtavis** [comment]
@RishiKumarRay, looks like we're all done with the original issue :) :) It really does look great! Thanks again and again 🙏 

> @andrewtavis i was thinking of adding something like a greeting bot with messages for people when they open an issue or Raise a PR Like for issue they will get a message to please wait unless they are assigned and for PR they will get a message that thankyou for raising a PR , wait until your PR gets reviewed

I'm really not sure on bots, but you'd be welcome to add something like this 😊 I think that having some kind of a greeting bot would be really great so that there's an initial interaction to thank them and let them know we'll be with them when we can. Would the bot be able to tell if the issue/PR has been assigned on writing and then not respond if so? That'd be best.

Do you want to continue to work on this in here, or should we open another issue?

Thanks for your initiative! 🚀

**Comment by andrewtavis** [comment]
Also, not sure if you have interest in this, but you are more than welcome to do PRs in [Scribe-Android](https://github.com/scribe-org/Scribe-Android) and [Scribe-Desktop](https://github.com/scribe-org/Scribe-Desktop) to add the `ISSUE_TEMPLATE` files from here. You can just drop them in and I'll fix the links :)

**Comment by RishiKumarRay** [comment]
> Also, not sure if you have interest in this, but you are more than welcome to do PRs in [Scribe-Android](https://github.com/scribe-org/Scribe-Android) and [Scribe-Desktop](https://github.com/scribe-org/Scribe-Desktop) to add the `ISSUE_TEMPLATE` files from here. You can just drop them in and I'll fix the links :)

Sure i would love to drop the templates there. thanks for letting me know

**Comment by andrewtavis** [comment]
> Actually there are other bots too that does different purposes , but with the time we can add others with the time , for now i will add a github actions workflow for a greeting bot. Yeah I am comfortable with both , you decide if you want to open up a new issue or work on this and thank you for letting me work on this , I would love to connect with you on discord if you want for working in future.

@RishiKumarRay, I'm actually not on Discord, but may eventually get on there if people want to do one for Scribe. As of now I'm more inclined to do a [Gitter](https://gitter.im/) for it. You're welcome to connect on here or drop me an email to the one on my profile though :)

> > Also, not sure if you have interest in this, but you are more than welcome to do PRs in [Scribe-Android](https://github.com/scribe-org/Scribe-Android) and [Scribe-Desktop](https://github.com/scribe-org/Scribe-Desktop) to add the `ISSUE_TEMPLATE` files from here. You can just drop them in and I'll fix the links :)
> 
> Sure i would love to drop the templates there. thanks for letting me know

Awesome! Thanks so much for this 🙏

**Comment by andrewtavis** [comment]
And ya let's open a new issue as this one is super long at this point. I'll do a feature one and assign you :)
