### ISSUE TITLE
Add pull_request_template.md to .github

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#104]
### Terms

- [X] I have searched open and closed issues for duplicates
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As in #101, it would be beneficial if Scribe-iOS also had a PR template. This would be a file `.github/pull_request_template.md` that would then be used as a template for future pull requests.

Helpful resources for this are: [the GitHub documentation](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository), [this YouTube video](https://www.youtube.com/watch?v=MjsS4ujX3nU), [this article](https://embeddedartistry.com/blog/2017/08/04/a-github-pull-request-template-for-your-projects/) and [the Signal-iOS PR template](https://raw.githubusercontent.com/signalapp/Signal-iOS/master/.github/PULL_REQUEST_TEMPLATE.md).

It would be best if directions were commented out using markdown comments `<-- -->` so they're not present in the PR text.

### Contribution

I'd be happy to work on this if no one else has interest :)

**Comment by andrewtavis** [comment]
@RishiKumarRay, this is an example of what the output is of `feature_request.yml` with the most recent edits. I chose to combine the description and screenshots section there was going to be a lot of

### Screenshots

_No response_

for that section. The screenshots are instead prompted for in the `placeholder:` key of each section, which has replaced the `description:` key. I think that overall it's best to use placeholders instead of descriptions as that will keep the length of the form down. Let's also try to limit the number of `textarea` fields to two per issue template, as when I tried to use it to make this issue I was like "Woah this form feels longgg" 😄

**Comment by RishiKumarRay** [comment]
@andrewtavis got it , I will implement this placeholder in place of description

**Comment by andrewtavis** [comment]
Implemented in the above two commits :)
