### ISSUE TITLE
Documentation for Scribe

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#11]
### Terms

- [x] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue)
- [x] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

Functions and variables are generally documented in Scribe, but this should be expanded on so that there can be a reference to help new contributors get up to speed as quickly as possible. This issue is for discussing best practices for automatic Swift documentation and planning the implementation of Scribe's docs.

**Comment by andrewtavis** [comment]
Once this issue gets some work on it it would be good to create a `Documentation` issue template so that issues can be automatically tagged.

**Comment by uhteen21** [comment]
What exactly is automatic documentation? Is that documentation that is generated of a software instead of by a programmer, of guidelines/regulations that make creating documentation easier?

**Comment by andrewtavis** [comment]
Hi @uhteen21! Thanks for writing 😊

I'm thinking that [DocC](https://developer.apple.com/news/?id=xa4ak3qr) is the program to use for this. Basically what we're looking for is to generate function documentation from the strings at the top of the functions. It looks like DocC is the tool for this, with us then being able to link the documentation to the readme so that people can read about the methods we're using rather than finding them in code. 

I do this with my Python packages using [Read the Docs](https://readthedocs.org/).

Would be happy to discuss this with you further!

**Comment by andrewtavis** [comment]
ef141db added directions on how to get to the developer documentation, which is a thing in XCode now 😊 Closing this up!
