### ISSUE TITLE
Add greeting bot to Scribe-iOS

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#111]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to create a greeting bot that will communicate with people who open an issue in or send a PR to Scribe-iOS.

### Contribution

Assigned to @RishiKumarRay 🙏

**Comment by andrewtavis** [comment]
@RishiKumarRay, an update for you :) There's been plans for a bit for Scribe to be featured on [Wikimedia Deutschland's Tech News page](https://tech-news.wikimedia.de/en/homepage/). By the sounds of it the interview I'll be doing about Scribe that they'll feature will be happening next week. It'd be great if we could get the issue templates into [Scribe-Android](https://github.com/scribe-org/Scribe-Android) and [Scribe-Desktop](https://github.com/scribe-org/Scribe-Desktop) before that :) :) Getting a bit of testing for this issue beforehand would also be great!

**Comment by andrewtavis** [comment]
With the above being said, we have plenty of time, so no stress about all this 😎

**Comment by RishiKumarRay** [comment]
@andrewtavis Its a great news , glad to hear that , I will be happy to read the interview , Yeah then let's finish that adding issues in both the repo first , maybe after that i will work on this greeting bot. So how do we proceed shall i add all files in a single PR ? Let me know after that i will raise the PR and you can merge and it will be ready

**Comment by andrewtavis** [comment]
I think all files in a single PR to both repositories would be fine :) I'll go through the links and test them, so don't worry about those on your end.

**Comment by RishiKumarRay** [comment]
@andrewtavis If you don't mind can i use 2 PR for adding to both , like I will raise 2 PR simultaneously for each repo and you can edit them. Let me know if you don't want then i will go with one for each :)

**Comment by andrewtavis** [comment]
@RishiKumarRay, feel free to use as many PRs as you need :)

**Comment by RishiKumarRay** [comment]
@andrewtavis Hi , Thanks i have created PR for Scribe Android , adding all the templates, please review , I will be doing so for scribe IOS too today itself

**Comment by andrewtavis** [comment]
@RishiKumarRay, thanks for these! I'll get to them shortly :) I've been hammering away at the new designs, with the design sprint looking to be finished by tomorrow or Saturday :) The new version of Scribe with the updated look should be available by Monday!

**Comment by andrewtavis** [comment]
@RishiKumarRay, all of them are merged, and I changed the URLs in my commits afterwards. My thanks for your efforts on these issues, and let me know what your plan is for this issue :)

Many many thanks! 🙏

**Comment by RishiKumarRay** [comment]
@andrewtavis Thankyou for merging all , it feels great to contribute to this project , i have added PR to solve this issue too.
you can review that PR #113 
The bot will send a custom message , I have written it , if you want to add anything please let me know .
through the bot the message will be displayed  as well as it will also go to any users email id too , I found out while testing that.
Do let me know your comments when you try that.

**Comment by andrewtavis** [comment]
@RishiKumarRay, thanks for this! I requested another file name change from you in the review of #113 😜 As I said in the rest of the review, I'll send some edits and we can discuss them in here before we close this :)

**Comment by andrewtavis** [comment]
Once this is done, as with #101 you'll be welcome to send the bot along to Scribe-Android and Scribe-Desktop. I'm hammering #112 tomorrow to get it done, but should be able to get to things as you send them :)

**Comment by RishiKumarRay** [comment]
@andrewtavis I have updated the changes , please have a look , thanks

**Comment by andrewtavis** [comment]
@RishiKumarRay, edits have been sent through :) What I was trying to add was the following:

- A bit of formatting so there's a title and spacing
- Telling users it's a bot (obviously the icon is a bot, but I think it's even more "human" from our end to have it say so itself)
- Make it a bit more personable with a sign off from the team like it's a letter, which I think is a nice opening for new contributors

Let me know what you think of them, and thanks so much for the suggestion to add this and the research on how to get it up and running!

**Comment by RishiKumarRay** [comment]
@andrewtavis Thank you , the edits are good , i liked the message you defined there

**Comment by andrewtavis** [comment]
@RishiKumarRay, great :) This issues looks done to me then! Awesome 😊 If you want to commit the welcome bot to Android and Desktop as before with the issue templates then you're welcome to. Let me know if you don't and I'll get it in them myself. Up to you :)

Hope you're having a nice weekend!

**Comment by RishiKumarRay** [comment]
Thanks @andrewtavis I have already raised PR for the both , have a look whenever you're free

**Comment by RishiKumarRay** [comment]
@andrewtavis Also I am looking forward to your release , and the interview you will be having , Best wishes for that, It was a great time working with you , I got to learn a lot , I wish whenever in future if you are working on any automation using devOps tools , do let me know , I would love to contribute in them. Happy Weekend to you too :)

**Comment by andrewtavis** [comment]
@RishiKumarRay, thanks again for all of this and the minor change as well :)

I'll send along the interview when it's posted, and I'll also link to it in the readme of this repository 😊 I've had a nice time working with you as well, and will let you know if any more automation is in the works. Feel free to suggest something later if you have an idea! You're also welcome to help with future coding tasks. I'm unsure if you have experience with or want to learn Kotlin or TypeScript, but Scribe-Android and Scribe-Desktop will be written in those respectively when they get under way.

Take care!

**Comment by RishiKumarRay** [comment]
@andrewtavis thanks , maybe in future i will learn typescript or kotlin , i was learning this but left and focused on other tools.  yes ofcourse i will suggest you if i come across anything new.
Take care  :)

**Comment by andrewtavis** [comment]
@RishiKumarRay, FYI I removed the bot for PRs. The [check](https://github.com/scribe-org/Scribe-iOS/pull/129/checks) for #129 failed and the bot didn't run. I'm unsure if there's just a mini issue with it, but I decided to disable it for now. It looks like [this issue](https://github.com/actions/first-interaction/issues/10) has some potential fixes.

For now I just commented it out :)

**Comment by RishiKumarRay** [comment]
@andrewtavis let me look into this, thanks for letting me know

**Comment by andrewtavis** [comment]
@RishiKumarRay, it looks like it’s been problematic for a lot of people. The issues bot worked great though 😊

**Comment by RishiKumarRay** [comment]
@andrewtavis yeah it looks like a major problem from the github itself let me find a alternative , Thanks and sorry it failed now

**Comment by andrewtavis** [comment]
@RishiKumarRay, don't worry about it at all. Take your time and I'm sure you'll figure it out. I'm working on other things the next few days, but I'd also be happy to discuss potential solutions :)
