### ISSUE TITLE
Add Localization issue template

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#119]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Scribe being a multilingual app, it would be good if the app and App Store texts were also localized across various regions. This is going to be a task that will continue as the app grows, so having a template for this would be nice so that users can report interest in helping or issues with current implementations.

Suggested structure:

- A file in [.github/ISSUE_TEMPLATE](https://github.com/scribe-org/Scribe-iOS/tree/main/.github/ISSUE_TEMPLATE) called `localization.yml`
- Title being `🌐 Localization`
- Labeled using `"localization"`
- The terms of normal issues
- Description and contribution fields with `placeholder` texts for each
- A nice thank you in markdown at the end

- This issue is a part of #9 

### Contribution

I'd be happy to work on this if others don't have interest :)

**Comment by andrewtavis** [comment]
@RishiKumarRay, let me know if this is something you'd have interest in working on :)

**Comment by RishiKumarRay** [comment]
@andrewtavis yes, i would love to contribute again, please assign me this issue, i will work on this , thanks for mentioning

**Comment by andrewtavis** [comment]
@RishiKumarRay, happy to mention you, and as always thanks for your help! :)

**Comment by andrewtavis** [comment]
The interview on Tuesday went well, btw :) They're making a transcript of it that I'll check sometime next week, and then that'll go live 😊

**Comment by RishiKumarRay** [comment]
@andrewtavis happy to hear that, i will wait for it. thanks for letting me know
also i have raise PR for this issue please review @andrewtavis and let me know the changes

**Comment by andrewtavis** [comment]
@RishiKumarRay, changes were pretty simple for this one :) I just cleaned up the description, and I decided my suggestions for two text fields wasn't a good one upon looking at it. I think localization is an easy enough issue that we can just have a single field like in the `Question` template 😊

Let me know what you think! If it looks good for you, as before you're welcome to push it to Android and Desktop :)

**Comment by RishiKumarRay** [comment]
@andrewtavis  Yeah i totally agree, this looks great , thanks , sure i will raise PR to both the repos and let you know

**Comment by andrewtavis** [comment]
Thank you, @RishiKumarRay! Look forward to them :)

**Comment by RishiKumarRay** [comment]
@andrewtavis please review i have raise both the PR

**Comment by andrewtavis** [comment]
@RishiKumarRay, merged both and just changed the links and the corresponding text :) Thanks again for your great work! 🙏 

Will close this now :) Hope you're having a nice weekend!

**Comment by RishiKumarRay** [comment]
Thankyou for mentioning , i will happy to work in future too for more such issues.
