### ISSUE TITLE
No pronouns in translations

### ISSUE THREAD

**Issue by jdgiddens** [scribe-org/Scribe-iOS#128]
### Terms

- [X] I have searched [open and closed data issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Adata+)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Languages

deutsch

### Issue

pronouns are not saved to be translated, not sure if data is missing from Wikidata or what

**Comment by andrewtavis** [comment]
Issue is that I didn't add pronouns to the translation files, but I can potentially add those in for another version as those in to another version :)

Thanks for letting me know!

**Comment by andrewtavis** [comment]
Checking the personal pronouns, pronouns and articles for words that were missing, the following words will be added to the translation options for each language: you, we, he, she, they, xe, it, sie, ze, fae, hir, ae, I, ne, heer, zhe, ey, thon, zie, ve, a, the, whomst, who, anyone, something, whomsoever, everyone, everything, anything, whoever, idem, what, yous, which, anybody, whosoever, whether, everybody, where, whoso, ya, that, and oneself.

I'm just going to Google translate these and add them in as it seems a waste to run a ML model to get such a small list :)

**Comment by andrewtavis** [comment]
@jdgiddens, 339a005 closes this :) All pronoun translations will be included in the v1.2.1 release, which should go out in the next few days. Thanks again! 😊
