### ISSUE TITLE
Rework Scribe key press when selecting a word

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#141]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Many have commented recently that the functionality of the Scribe key when a word is selected could be reworked to present the commands and then run them over the selected word. What this means is that the command prompts would not be shown and instead the selected word would directly have the command ran over it. This would replace the current functionality where for nouns and pronouns have their form and coinciding case shown respectively.

A way to include the current functionality would be to include it as a selectable option instead of commands that aren't applicable. Specifically words that are already in the keyboard's target language would not need to be translated, so this command could be replaced. Commands that could be displayed given the type of word selected include:

Nouns: form, plural
Verbs: conjugate (and case once #81 is finished)
Prepositions: case

This feature could also later present the `Synonym` command when #20 has been finished. A `Definition` command could be included as well, with maybe the information from `Form` and `Case` being included so that only three options would be needed.

### Contribution

I need to get more feedback on this, but will implement it if it makes sense. Help would be appreciated if people have interest!

**Comment by andrewtavis** [comment]
Something that could also be done for this is that the command options could be shown along with the annotation. The annotation could be shown over the translate button field if there is one, and aside from that the conjugate button and plural button could be shown. It doesn't seem reasonable that a person would want to do an autosuggestion at this time, so we could present the two other buttons with it and use the selected word as a source of the command when it's pressed. This would actually be quite simple to implement! 😊

**Comment by Jag-Marcel** [comment]
Working on this one ✋

**Comment by andrewtavis** [comment]
Closed by #485 :) Thanks so much for the great work here, @Jag-Marcel! 🚀
