### ISSUE TITLE
Separable verbs need to have the cursor go between the verb and prefix

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#155]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

For German verbs it would be good to check if the verb is separable, and if so for conjugation the cursor of the text field would be put between the verb and the prefix. As of now the cursor is at the end of the prefix that would be at the end of the sentence. 

Example:
The German verb for wake up is "aufstehen", where "auf" would normally be at the end of the sentence. Currently the first person singular conjugation would lead to "stehe auf |", but it would be better if it would be "stehe | auf" so that the user could easily type in the middle of the sentence and then move the cursor to the end to continue.

### Contribution

I'd be happy to work on this, but others are welcome to contribute! 

Things to do include:
- Figuring out how to query verbs that are separable ("trennbar" in German)
- Checking support for this across verbs would also be needed to assure that verbs that are separable are marked as such
- Placing the cursor in the appropriate place if such a verb is used

**Comment by lucastronova** [comment]
I have a PR open for this issue (#321)

**Comment by andrewtavis** [comment]
Thank you, @lucastronova! Really a pleasure to have two contributions so quickly from someone 😊 I’ll check the two PRs tomorrow to Tuesday at the latest as I’m pretty busy on Monday. 

Thanks again so much!

**Comment by lucastronova** [comment]
@andrewtavis Thank you for putting your project on GitHub! I have been looking to learn Swift and to get into open source, so I look forward to contributing to this project :^)

**Comment by andrewtavis** [comment]
Closed via #321 😊 Thanks again, @lucastronova! Let me know if you have questions about the project or want some guidance to where else you can help.

There are a lot of issues assigned to @SaurabhJamadagni, but if you'd like to pick one up you'd be welcome to. With those he'd just be the initial reviewer as it's part of his work for Google Summer of Code ☀️ On my end I promise to be a bit more responsive going forward. Has just been a crazy last few weeks for me :)

**Comment by andrewtavis** [comment]
@lucastronova, d914a97 is just a bunch of formatting save for one edit to this process. In cases where the proxy was capitalized for verb conjugation we were returning both words capitalized - so `Bin |Gegenagen` instead of `Bin |gegangen`. That got cleared up in the changes to `Conjugate.swift` 😊
