### ISSUE TITLE
Change return key icon to a right triangle during command executions

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#165]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This is a very simple issue. The goal is that the commands Translate, Conjugate or Plural would trigger a change in the icon that's applied to the return key. Not only would it change color to `ScribeBlue`, but it would also change its icon to `arrowtriangle.right.fill` of SF Symbols from `arrow.turn.down.left`, with the original icon being replaced once a command is canceled or executed. 

General feedback has been that it's a bit hard to realize that the return key should be pressed to execute commands, so adding this might make it more apparent.

- #103 could potentially he changed such that `arrowtriangle.right.fill` or `arrow.right` could be used when the user is making a web search.
- This could similarly include switching the button to `magnifyingglass` if the user is searching.

### Contribution

Would be happy to do this if others don't have interest :)

**Comment by SaurabhJamadagni** [comment]
> As of now I'm thinking that arrowtriangle.right.fill might be best as it would be very apparent for new users, as the rest of the UI is similar to arrowtriangle.right, which thus might blend in too much.

@andrewtavis, the `arrowTriangle.right` does seem like a good option. The return key changes colour when the command state is true. I think that coupled with the `arrowTriangle.right.fill` symbol should make it prominent enough.

**Comment by andrewtavis** [comment]
Glad you agree :) Looking forward to this change! We can also include it in v1.4.0 if you plan to get to it quickly, but no stress if you need more time. I’ll likely try to release by early next week at the latest. 

Also, note that maybe the size of the icon will need to change as some of them look a bit off at certain dimensions. Hopefully this isn’t the case, but I can give more directions if you think `arrowTriangle.right.fill` looks too small or big.

**Comment by SaurabhJamadagni** [comment]
> We can also include it in v1.4.0 if you plan to get to it quickly, but no stress if you need more time.

Yeah sure, I will get to it at the earliest. Fingers crossed, this should be straightforward and shouldn't take long 😅

I'll let you know if I need help. Thanks!

**Comment by andrewtavis** [comment]
Ya the only thing that might hold it up is if the icon needs resizing, but there are examples of how to do that in the code. Not worried about your ability to figure it out :)

**Comment by SaurabhJamadagni** [comment]
@andrewtavis, could you verify if the size of the symbol `arrowTriangle.right.fill`  is large enough or not? It seems proportionate but I am not sure. Anything larger, I think would be too bold in contrast to the blue background of the key. Do let me know what you think. 

![image](https://user-images.githubusercontent.com/68957712/180603476-c92aa424-2385-4f64-903e-b48c54427874.png)

**Comment by andrewtavis** [comment]
Really exciting, @SaurabhJamadagni! I'd honestly go bigger - trying to match the height of the delete button character, or specifically `123` so that the special characters are the same height on the same row.

**Comment by andrewtavis** [comment]
My initial impression would be to increase the size by 10%.

**Comment by andrewtavis** [comment]
I get your thinking that we want it to fit, but we also really want it to stick out so that a first time user is like "Aaaaa I press enter."

**Comment by andrewtavis** [comment]
![Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2022-07-23 at 13 58 24](https://user-images.githubusercontent.com/24387426/180603903-ce7a81a8-a54d-4578-872e-55db334ee23f.png)
The prompts look great on iPad, btw 😊

**Comment by SaurabhJamadagni** [comment]
> My initial impression would be to increase the size by 20%.

Sure, I'll make the changes.

**Comment by SaurabhJamadagni** [comment]
Is this better, @andrewtavis? 

- After adding `arrowTriangle.right.fill` to [keysThatAreSlightlyLarger](https://github.com/scribe-org/Scribe-iOS/blob/bddbaaa1805d244f852ac46ec07eb47e4b253c0a/Keyboards/KeyboardsBase/KeyboardStyling.swift#L32) array
https://github.com/scribe-org/Scribe-iOS/blob/bddbaaa1805d244f852ac46ec07eb47e4b253c0a/Keyboards/KeyboardsBase/KeyboardStyling.swift#L32

![image](https://user-images.githubusercontent.com/68957712/180605327-92edccef-cc36-49e9-9d1c-bdd14f79106b.png)

- This is the previous iteration. Putting this here for easier comparison :)

![image](https://user-images.githubusercontent.com/68957712/180605268-9aa2692c-4a89-4e7d-9e53-ca9824300cc7.png)

**Comment by andrewtavis** [comment]
Looks great, @SaurabhJamadagni! Thanks so much for the quick edit 😊

**Comment by SaurabhJamadagni** [comment]
> Looks great, @SaurabhJamadagni! Thanks so much for the quick edit 😊

Awesome, I'll issue the PR right away. Glad to help out 😊

**Comment by andrewtavis** [comment]
Thanks for your help with all this, @SaurabhJamadagni! Really well done 👏

Let me know if you think it's a problem that the `123`, `delete` and other keys are changing size during translation for some keyboards. I mentioned that in the PR as I noticed it during review. What I mean is that for German, Swedish and Russian the characters on these keys will change size because the characters on the English keyboard are slightly different given the width of the keys. There is no change for Latin languages as the top row has the same number of keys as English (the number of keys in the top row determines the width of the keys and therefore the size of the characters). I don't think it's a major problem, but we can make a bug issue for it if you think it should be fixed :)

I'll get to #176 tomorrow and send along the new version to Apple 😊 Thanks again so much!

**Comment by andrewtavis** [comment]
This really is so great, @SaurabhJamadagni 😊 I'm gonna take a video and send it to the designer now :)

**Comment by andrewtavis** [comment]
And alsooo, great work on the ternary operator in there :) Hope you're having a nice weekend!

**Comment by SaurabhJamadagni** [comment]
> Let me know if you think it's a problem that the 123, delete and other keys are changing size during translation for some keyboards. I mentioned that in the PR as I noticed it during review.

Yes @andrewtavis, I noticed it now that you point it out. We can definitely make a bug issue out of it. Like you said, it is not a major issue, but I can see how it could become slightly annoying for someone who notices uniformity quickly. 😅

We can get to it whenever you see fit. Thank you for your kind words. I am just thrilled I am able to contribute.

**Comment by SaurabhJamadagni** [comment]
> And alsooo, great work on the ternary operator in there :) Hope you're having a nice weekend!

Thank you! Yes, I am having a nice weekend. I hope you are having one too :)

PS: I am sorry, I totally forgot about the CHANGELOG. Completely slipped my mind. I need to add it to habit to reflect the changes in the changelog immediately. Thank you for adding the changes for me 😅

**Comment by andrewtavis** [comment]
No worries on the changelog 😊 Am having a nice weekend! I'm gonna shift to something else for a bit, but let's check in again soon, @SaurabhJamadagni! Feel free to look into other issues and message if you think they'd be good for now/the hackathon, or I can also look into it later :)
