### ISSUE TITLE
Add information icon to the command bar

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#166]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Scribe-iOS will eventually allow users to press the command bar for information (see #13). The first step in this is to make the command bar a button instead of a label, or putting a button above the label that the user can then interact with. This is a simple task that could be done now and disabled until the commands are ready.

Some work would happen in [KeyboardsBase/Keyboard.xib](https://github.com/scribe-org/Scribe-iOS/blob/main/Keyboards/KeyboardsBase/Keyboard.xib), with the rest happening in [KeyboardsBase/KeyboardViewController.swift](https://github.com/scribe-org/Scribe-iOS/blob/main/Keyboards/KeyboardsBase/KeyboardViewController.swift) and [KeyboardsBase/ScribeFunctionality/CommandBar.swift](https://github.com/scribe-org/Scribe-iOS/blob/main/Keyboards/KeyboardsBase/ScribeFunctionality/CommandBar.swift) (the custom class that the button would be added as an element of).

### Contribution

I'd be happy to work on this later or collaborate with others on it :)

**Comment by misteu** [comment]
Hi again,
the `CommandBar` is this thing I colored `.red` here, right?
![grafik](https://user-images.githubusercontent.com/35889530/192851161-eefdeea3-c434-4c47-94a9-f747e88f76d1.png)

So all of this should behave like a button? I think this interaction might not be that easy to find.

A button above the label will make the whole keyboard really huge I think.

What about adding something at the trailing edge, e.g. some round button with "info.circle", "info.circle.fill" or this three dots icon?

For example what about something like this? 
![grafik](https://user-images.githubusercontent.com/35889530/192865628-c4ed79a0-f8f7-43eb-b655-78e93116ece2.png) (of course I could pick another color as well)

**Comment by andrewtavis** [comment]
Hi @misteu! First and foremost, really glad to have you commenting on another issue! Also thanks for going to the effort of making a mockup of an idea that I honestly think is dramatically better than what it is that this issue is talking about. Totally makes sense that it would be hard to find 😊

Big thing is that the most recent switch that's happening in #209 is gonna switch the priority on this, and we likely won't end up doing it the way it works now :) You're correct that the `CommandBar` is what you have colored red, and the what used to be happening is that a user would see the annotations in the bar as we didn't have autocomplete or autosuggest. The idea for this was click the bar so that at one point you can get info on words. Now that #188 is done and #194 is getting close to being finished, annotations will instead be shown instead of the first autosuggest field. Let me demonstrate with a video of the new annotation for "Schild" and "See" below, with the first being neutral or masculine, and the second being masculine or feminine, so the idea would be that you could one day click the annotation and learn what the difference is:

https://user-images.githubusercontent.com/24387426/192896938-4ae8c3ec-6d96-4b2c-9fb5-f9b117d84435.mp4

As an aside, your feedback on how the new annotations work would be much appreciated! From there, the command bar is now only going to be present when a user is typing words to translate, conjugate, or make plural (and when the user enters something that's not valid and gets the "Not in Wikidata" message). I'm not sure at this point if there would be a major need for the command bar being user interactable at this point. A general idea would be that if the user sees "Not in Wikidata", then maybe they could click on the bar and be prompted to add it to Wikidata themselves? In that case, I think that your UI is dramatically more sensical! What do you think on this?

Sorry for reworking this issue on the fly. It's hard to keep track of some of the older issues particularly at this time when so much is happening for v2.0.0 😊

**Comment by misteu** [comment]
Hey!
Alright, wasn't aware that this will change :) Sure it can be an info icon or whatever.

My "mockup" was actually made in the app :D So it's actually already on a separate branch. I can change it to an info icon and visually hide the button until you want to use it for anything.

I would also provide a tap handler as a property of `CommandBar` so that you can quickly add some action later.

If you want to completely park this button on the `CommandBar` for now, no worries, then I'll pick up something else.

**Comment by andrewtavis** [comment]
Hey back!

> Alright, wasn't aware that this will change :)

Ya very sorry again. I do try to keep the issues up to date, but then we have four issues here and one in [Scribe-Date](https://github.com/scribe-org/Scribe-Data) for the next release, so I've been focussing on getting things done and not the backlog.

I honestly do think that there's a lot of value in there being an info icon on the right as we discussed. I'd likely apply `ScribeBlue` to it for consistency, but aside from that having a clickable element there when the keyboard presents the `invalidCommandMsg` when `commandState == .invalid` would be great, just so we can eventually implement a short tooltip for the user that explains what Wikidata is, how Scribe uses it, and maybe prompts them to get involved. The tap handler would also be helpful in those regards 😊

Unsure where exactly the changes are as far as conflicts are concerned. [CommandBar.swift](https://github.com/scribe-org/Scribe-iOS/blob/main/Keyboards/KeyboardsBase/ScribeFunctionality/CommandBar.swift) has very few changes going through now, but the main [KeyboardViewController.swift](https://github.com/scribe-org/Scribe-iOS/blob/main/Keyboards/KeyboardsBase/KeyboardViewController.swift) has tons. Regardless, a PR is more than welcome 🙏 We can figure it out :)

**Comment by andrewtavis** [comment]
Hey again! Sounds wonderful :) I'll go ahead and assign you as this definitely would cover the issue 😊

**Comment by misteu** [comment]
Opened an MR here: https://github.com/scribe-org/Scribe-iOS/pull/213

**Comment by andrewtavis** [comment]
Thanks so much! 🚀 Will be in touch in the coming days when I'm done with #209. Really appreciate these so much 😊

**Comment by andrewtavis** [comment]
All done reviewing this one too, @misteu :) Sorry that the commits look so weird for it. I tried to fix a very small conflict, and then that added a bunch of things to the PR that would delete your work in #212. Hopefully you'll have credit for both of these in no time :)

**Comment by andrewtavis** [comment]
And looking at it, I think that the a shade of grey is better for this so that it doesn't show up toooo much. That change was done in [dd98481](https://github.com/scribe-org/Scribe-iOS/commit/dd98481c5ed85f1368d248846387d1068e4318cd) :)

**Comment by misteu** [comment]
Hey!
thank you for your approval&merging!

Also my hacktoberfest profile is now showing them 👍

What I saw when working on the colors is that there is a lot of logic for getting or setting up light an dark mode colors.

I'd rather move all the colors in a color assets file and have an enum pointing to them. By that you would define light/dark colors in there and never had to check for the traitCollection anywhere.

**Comment by andrewtavis** [comment]
Hey again!

Very happy that the Hacktoberfest profile is giving you your due credit :)

Ya the colors can be quite a hassle, and specifically we need to do a lot of things within the main view controller to make sure they're assigned properly. An enum along with an assets file sounds really great! Do you want to open an issue for this and I can assign you, or just send along a PR?

**Comment by andrewtavis** [comment]
Btw, you're not showing up in the contributors of the project as of now. Let me know if I should look into this :)

**Comment by misteu** [comment]
oh, right that's strange. I think it might be because the email address of my git config is different to mail address at github. I'll check if there is some difference

**Comment by misteu** [comment]
The mail address I'm using in my git config was missing in github. Added it there. Github docs say it might take up to 24h to show up there.

As my avatar is showing up here for the commits merged into your repo, I guess the association itself works 
![grafik](https://user-images.githubusercontent.com/35889530/193470070-95a9fc72-0836-4659-9bc0-959b13dda6ed.png)

**Comment by andrewtavis** [comment]
Looking forward to seeing you in the contributors tomorrow then :)

Let me know what you want to do about your idea for coloration 😊

**Comment by misteu** [comment]
Hi!
Sure, would be happy to refactor the colors!

You can create an issue for it and assign me to it. I should be able to work on it next week 👍

**Comment by andrewtavis** [comment]
Hey again! Just made #216 for this :) Feel free to comment in there and I'll assign you 😊
