### ISSUE TITLE
Fix English word not included text

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#170]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

This is a very simple error. The file [Keyboards/KeyboardsBase/InterfaceVariables.swift](https://github.com/scribe-org/Scribe-iOS/blob/main/Keyboards/KeyboardsBase/InterfaceVariables.swift) still has "Not in directory" for `invalidCommandMsg`, but this needs to be changed to `Not in Wikidata` to match the rest of the messages.

Happy to get to this if no one has interest :)

### Device type

iPhone and iPad

### versions

All versions

**Comment by SaurabhJamadagni** [comment]
Hi @andrewtavis, I am interested in making this correction. Please may I?

**Comment by andrewtavis** [comment]
Fixed in [cb425ff](https://github.com/scribe-org/Scribe-iOS/commit/cb425ff8af0876249b195f0c6dc3ba1b5573595d) :)
