### ISSUE TITLE
Ability to delete placeholder prompt

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#184]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

An issue that has come from the placeholder texts added in #35 is that there is the ability at one point to delete the command prompt. The bug can be reproduced via:

- A command button is pressed
- The shift key is pressed
- The prompt is then black (light mode) instead of grey (a bug in and of itself)
- If the user types while the prompt is black, then the text will be added at the end of the prompt instead of replacing it
- If the user deletes after adding text after the prompt then the prompt can be deleted

This should be fixed before the v1.4.0 release :)

### Device type

iPhone and iPad

### versions

I assume this is happening for all versions.

**Comment by andrewtavis** [comment]
@SaurabhJamadagni, wanted to bring your attention to this :) Obviously no worries on the bug introduction as these things happen with cool new features 😊 I didn't think of this as a potential, but it came up as I was testing it a bit. Let me know if you have any ideas on how to fix this :) Happy to investigate and make the changes myself as you've done so much for this recently!

**Comment by andrewtavis** [comment]
Note that the prompt also turns black (light mode) if the `123` button is pressed.

**Comment by andrewtavis** [comment]
The discoloration is coming from `self.textColor = keyCharColor` within `commandBar.setCornerRadiusAndShadow`. Moving that outside the function and conditionally checking for `commandState == false` before calling it will stop this from happening (stops the first bug), but then typing will replace the last character of the prompt with the typed character and make it black (light mode) again.

**Comment by andrewtavis** [comment]
What this is indicating is that there's an issue with how the conditional that guards `handleDeleteButtonPressed` from being called within `keyLongPressed` is being triggered.

**Comment by SaurabhJamadagni** [comment]
Thank you for making the required changes yourself @andrewtavis. I'll take this as a learning experience to test my implementations more thoroughly from here on. 😊

**Comment by andrewtavis** [comment]
Take it as a learning experience, but also don't worry about it :) I also tested the implementation on the emulator before bringing it in, and didn't realize the bug in my tests either.

**Comment by andrewtavis** [comment]
@SaurabhJamadagni, just finished #176 and sent along v1.4.0 to Apple 😊 The update should be available in the App Store in the next 48 hours 🥳 If you have auto updates it will happen within a couple of days after being updated in the App Store (there's a lag on releases and when auto updates are triggered).

Thanks again for all your help! As you can see in the [changelog](https://github.com/scribe-org/Scribe-iOS/blob/main/CHANGELOG.md), you were the main contributor for this release 😊

Let's connect in the coming weeks. I'll let you know when I hear more about the hackathon, and we can maybe do a call at that point to figure out what we'd like to do for that :)

Have a great rest of your week!

**Comment by andrewtavis** [comment]
Anddddd it's already out 😊😊 So great! 🥳 Sent a preview video to the designer a few days ago, and we're both really excited to see how users will react to the new system. I'm really thinking that this is gonna help user understanding and usability sooo much 🚀

**Comment by SaurabhJamadagni** [comment]
> Thanks again for all your help! As you can see in the [changelog](https://github.com/scribe-org/Scribe-iOS/blob/main/CHANGELOG.md), you were the main contributor for this release 😊

I am so excited about it @andrewtavis! It's an absolute joy to see my contributions reflected in an app on the app store! Thank you so much for all the help you have provided 🥳

> Let's connect in the coming weeks. I'll let you know when I hear more about the hackathon, and we can maybe do a call at that point to figure out what we'd like to do for that :)

Absolutely! That sounds good. I have bookmarked a few issues that seem interesting. Looking forward to our conversation. Thanks 😊

You have a great week too!
