### ISSUE TITLE
Wikimania 2022 Prep and Documentation

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#187]
### Terms

- [X] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

This issue is a discussion of what needs to happen prior, during and after Scribe-iOS' participation in the [2022 Wikimania Hackathon](https://wikimania.wikimedia.org/wiki/Hackathon). Throughout this issue the page [Scribe at Wikimania Hackathon 2022](https://github.com/scribe-org/Scribe-iOS/wiki/Scribe-at-Wikimania-Hackathon-2022) will be made as documentation in the project's Wiki.

**Comment by andrewtavis** [comment]
@SaurabhJamadagni, made this issue so that we can talk about the Hackathon :) You can find information for how to prepare in the [page I created in the Wiki](https://github.com/scribe-org/Scribe-iOS/wiki/Scribe-at-Wikimania-Hackathon-2022). I'll signup soon and connect with them on if we can have a slot in the initial presentation of projects to work on 😊

Let me know if this issue and the wiki page seem sufficient to help us coordinate on this. GitHub also has discussions, but then I don't really find them appealing and don't have them activated on projects.

**Comment by andrewtavis** [comment]
Generally the interest from Wikimedia in the past has been progress on [Scribe-Android](https://github.com/scribe-org/Scribe-Android), so I might work to clear out the directories that have extra files and add a background behind the keys.

**Comment by SaurabhJamadagni** [comment]
> Let me know if this issue and the wiki page seem sufficient to help us coordinate on this. GitHub also has discussions, but then I don't really find them appealing and don't have them activated on projects.

Hi @andrewtavis, I hope you had a great past week :)

I think this would be sufficient for coordinating throughout the hackathon. In case we need to discuss something in more detail, we could always jump on a call. This should be perfectly fine for now. I am not very sure how helpful I'll be with issues for Scribe-Android, but I'll help out as much as I can 😅

 Is there anything you would like me to do in preparation for the hackathon?

**Comment by andrewtavis** [comment]
The week was very nice, @SaurabhJamadagni! Hope the same for you :)

You’re 100% not expected to work on Scribe-Android! Best if you work in here 😊That’s just a reminder for me. 

To start, what are some of the issues you’re thinking you’d like to work on during the hackathon? From there we can do a call to plan the work for them?

**Comment by SaurabhJamadagni** [comment]
> To start, what are some of the issues you’re thinking you’d like to work on during the hackathon? From there we can do a call to plan the work for them?

Some of the issues I would like to work on @andrewtavis are issue #22 and issue #136. These two seem interesting and I think would make a nice addition to the future versions of Scribe. Are they something we can look into? I am very curious about how autocomplete works in keyboards. So it should also be a learning opportunity. Let me know if you had any particular issues in mind as well :)

**Comment by andrewtavis** [comment]
Hi @SaurabhJamadagni 👋😊

Very sorry that you're hearing from me so late! I had quite the busy weekend, and there's lots to do this the new job and other endeavors. Your issue suggestions are ones that are quite important, but I'm not sure if it's exactly what we can achieve at the hackathon. 

Specifically, in reflecting I blocked #22 as we need to have #33 finished first so that the iPad key layouts are done and ready for the pulldown mechanics. iPad users are also a small fraction of the total, so I wouldn't prioritize this now. Hope this makes sense!

As far as #136, this very much so, but then this is extremely difficult as it would require adding and running a predictive model after each key press. I personally am not really sure how to start with this issue 😅 There are many issues in here that are very long term. I also realized that it was `-priority-`, which was misleading. It's just that I'm excited about it, but that label did need to be removed. We'll get to it sooner rather than later, but right now would be a stretch with how much time I have to dedicate to Scribe 😊

Let me throw some issues out and you can let me know what you think :)

For something more challenging, we could work towards being able to do #3 - the most sought after feature at this point:
- This would require us discussing how the mechanics would work, as the command bar wouldn't be present unless the user was executing a command
- I could make a baseline issue for this where we'd suggest words from the combination of all the grammar JSONs that we have
    - We'd basically be changing the text of the `Translate`, `Conjugate`, and `Plural` buttons as the user types and then insert the word when the button is pressed
    - The predictive model for the suggestions would just be the next word alphabetically at first
    - What this would be going towards is the following, where this would be after the user types "Ze":

![Autosuggest](https://user-images.githubusercontent.com/24387426/182542168-f8e337f4-4709-413c-86e4-e6ded470eed7.png)

- The coloration would be done in #164, and you'd obviously be ideal/welcome to work on it :) :)

Aside from the above, here are some simple ones with impact:
- #147
- #103
- #125

**Comment by SaurabhJamadagni** [comment]
Yes @andrewtavis, you make great points about the issues I listed. We can absolutely get to them later. 😊

The simple issues that you have listed seem to be a great starting point. Issue #3 seems like a great feature to implement as the hero item for the hackathon. Implementing it would be a large step towards a great user experience. The predictive model you have proposed also seems like a logical step. 

Just to clarify, the coloration that is being performed is on the basis of gender and not the command state. Is that correct? Also, will the autocomplete be functional when a command state is selected?

**Comment by andrewtavis** [comment]
Glad that you agree, @SaurabhJamadagni 😊 Again your suggestions were very valid, but I'm just trying to figure out the best use of our time at the moment :)

Answers to your questions:
- Yes the coloration within #164 is based on gender :)
- I would say for the MVP the autocomplete would not be functional for the command state. Let's have a discussion about how best to implement that, with your suggestions being very welcome. With the command bar spanning the rest of the screen, we wouldn't have the space to also present suggestions in another field, but we could potentially - later on - do say some greyed out text to complete what the user is typing, and if they press space then it's entered for them? How does that sound?

Looking forward to all this!

**Comment by SaurabhJamadagni** [comment]
> I would say for the MVP the autocomplete would not be functional for the command state. Let's have a discussion about how best to implement that, with your suggestions being very welcome. With the command bar spanning the rest of the screen, we wouldn't have the space to also present suggestions in another field, but we could potentially - later on - do say some greyed out text to complete what the user is typing, and if they press space then it's entered for them? How does that sound?

Yes, I was going to suggest something similar @andrewtavis. We can work on extending the functionality during command states later when we understand and implement the basic mechanics. Currently, I like the implementation of having the suggestions in the command bar. It seems clear and very direct. The problem with the space bar implementation in my opinion is that we also have to implement undo functionality. For example, if a user just wanted the space and not the word completion, when they press delete we must store the previous word. That should increase complexity. So currently the suggestions in the command bar seem like a great step to go in. Of course, the functionality can be modified and extended later as you have in mind. 

I am looking forward to working on this too! Excited for the event :)

**Comment by andrewtavis** [comment]
All sounds good :) Let's look to do the planning call next week, @SaurabhJamadagni! Let me know when you're available and what your preferred chat app is (Google Meet, Zoom, Jitsi). I'm not available on Monday, but maybe Wednesday?

**Comment by SaurabhJamadagni** [comment]
Yes @andrewtavis, absolutely! Sorry for the delayed response. I had a few college assignments to complete. I am available on Wednesday any time between 08:30-13:00 (GMT). Else next I can jump on a call any time directly after 17:00 (GMT) 😅

Do let me know whichever time is convenient for you. Also I understand GMT is the timezone neither of us use, but I just thought it would be simpler. I was assuming you go by the Central European Time. Is that correct? I used GMT right now as I wasn't sure. So let me know if it's a bit of an odd timing. I can definitely adjust.

Google meet would be great as that is my most used platform. But I am perfectly fine with zoom :)

**Comment by andrewtavis** [comment]
No worries on the timing! Hope your studies are going well 👏

Let’s do after 17:00 GMT, as I’ll be at work during the other times :) Using that time frame does make sense, btw, but as you’ll see in the Wikimedia circles folks usually say UTC for it 😊

For Google Meet, can you send an email to the one in my GitHub and I’ll send along a meeting link with a time?

Hope you have a great weekend!

**Comment by SaurabhJamadagni** [comment]
Hi @andrewtavis, I have sent the email to the address from your GitHub profile as you asked. I absolutely forgot to tell you yesterday 😅. I hope you have received it.

**Comment by andrewtavis** [comment]
Hi @SaurabhJamadagni, did receive your mail :) Will reply later tonight with a link for tomorrow after I'm done with work and have some things for the hackathon finished 😊

**Comment by andrewtavis** [comment]
I also added us to the pre-hackathon showcase where I might talk a bit about Spanish, as there's a Spanish language group meeting right after, and will add it to the final showcase when we've made a bit of progress :)

**Comment by andrewtavis** [comment]
Also, here's the [presentation for the hackathon session](https://docs.google.com/presentation/d/12WNSt5xgNIAmSxPfvjno9-sBMGlvxG_xSaAxmHQDRNQ/edit?usp=sharing). Let me know if you have any suggestions :)

**Comment by SaurabhJamadagni** [comment]
Thanks for sharing the presentation @andrewtavis. Excited for the session! Thanks for taking the time out to conduct it :)

It was an absolute joy to speak with you yesterday as well :)

**Comment by andrewtavis** [comment]
Ok, so I finally got into Pheedloop 😅 Apparently my adblocker was screwing up the whole process of registering/logging in. I'm trying to figure out where exactly the Jitsi rooms for the hackathon are, and have sent an email to a Wikimedia organizer. 

I said that I'd send along some interesting sessions that I'll attend. I'll say "Hack" if it's hackathon related, and just "Wikimania" if it's the main sessions.

Friday:
- Hack: Hackathon Opening Ceremony (16-17 UTC)
- Hack: Hackathon social right after (17-17:30 UTC)
- Hack: How to organize a local Hackathon (19:30-20 UTC)

Saturday:
- Lots of stuff that's wayyy to early 😅
- Wikimania: [How to Promote your Activities](https://pheedloop.com/wikimania2022/virtual/?page=sessions&section=SESWNR1TZG2Y0RN6H) (7:25-7:55 UTC)
- I'll be busy for a bit after this, just FYI
- Hack: Ask anything about Wikidata (13-13:30 UTC)
    - Talk is by the product owner of Wikidata
- Hack: Intro to Cloud Services (14-14:30 UTC)
- Hack: Scribe Session 🚀 (14:30-15 UTC)

Sunday:
- Wikimania: [Responsible community governance](https://pheedloop.com/wikimania2022/virtual/?page=sessions&section=SESRLXQ7QXBIS4N31) (10:45-12 UTC)
- I need to meet a friend to talk designs for another project :)
- Wikimania: [Wikimedian of the Year](https://pheedloop.com/wikimania2022/virtual/?page=sessions&section=SES99SR2ZPPC2E5EG) (14:30 UTC)
- Wikimania/Hack: [Hackathon Showcase](https://pheedloop.com/wikimania2022/virtual/?code=ATTE7BQKJGG236TM06MUNK3NG7PS&page=sessions&section=SESNXPAPO7LVR9L46) (15:55-16:45 UTC)
    - Where we'll present the results for the hackathon
- Wikimania: [Democracy and Wikimedia](https://pheedloop.com/wikimania2022/virtual/?page=sessions&section=SESXQH9EUOMLKF7II) (17:25-17:40 UTC)
- Wikimania: [Human Rights Policy Workshop](https://pheedloop.com/wikimania2022/virtual/?page=sessions&section=SESUYH5FH8LABDQGI) (17:45-18:35 UTC)

**Comment by SaurabhJamadagni** [comment]
Thanks for sharing this @andrewtavis! I can see a few sessions that would interest me among these. I am still confused on how to join these though. I can't find the Scribe session or the Wikidata session on the pheedloop event platfrom in the Sessions tab. Will the Jitsi link be posted on the [schedule](https://wikimania.wikimedia.org/wiki/Hackathon/Schedule) page or in pheedloop? 😅

**Comment by andrewtavis** [comment]
There have been some issues with Pheedloop apparently, @SaurabhJamadagni. We were supposed to have a Technical Sessions and a Social Sessions space that we can find, and then the schedule for the hackathon is [here](https://wikimania.wikimedia.org/wiki/Hackathon/Schedule). That schedule gets updated as we go, and now has the links to the Jitsi rooms at the top of the schedule :)

For the Scribe and Wikidata sessions, we'll be in the Technical Sessions room, which can be found [in the agenda](https://wikimania.wikimedia.org/wiki/Hackathon/Schedule#Hackathon_Agenda).

Sorry for the confusion on this! Seems like there were a few hickups, but then this is why it's nice to know the people :)

**Comment by andrewtavis** [comment]
@SaurabhJamadagni, just checking, you're planning on joining starting tomorrow, correct? I'll just plan on working on #188 this evening and then let you know what I get to. From there we can connect when I wake up in the morning 😊

**Comment by SaurabhJamadagni** [comment]
> @SaurabhJamadagni, just checking, you're planning on joining starting tomorrow, correct? I'll just plan on working on https://github.com/scribe-org/Scribe-iOS/issues/188 this evening and then let you know what I get to. From there we can connect when I wake up in the morning 😊

Absolutely @andrewtavis! I'll just go through the codebase tonight in preparation for tomorrow. Have a good evening. I'll check in with you tomorrow 😊

**Comment by andrewtavis** [comment]
60 or so people at the hackathon opening ceremony, so we should have a nice group for tomorrow :)

**Comment by SaurabhJamadagni** [comment]
@andrewtavis  what's the plan for the showcase? I don't need to have a presentation handy right? 😅

**Comment by andrewtavis** [comment]
I can just talk about it if you want me to, or if you'd like you can talk about your part of creating the function :)

**Comment by SaurabhJamadagni** [comment]
I can give it a shot! If I am currenlty on someone else's internet right now. So if I face any problems, you can take it from there.

**Comment by andrewtavis** [comment]
Are you in there though? I don't see you :)

**Comment by SaurabhJamadagni** [comment]
I think I am now. I had joined a different link before 😂

**Comment by andrewtavis** [comment]
Well done 😊

**Comment by SaurabhJamadagni** [comment]
I didn't know I could speak that fast @andrewtavis 🤣

It was super fun working with you on this hackathon! Looking forward to getting more stuff done! Thanks for all your help 😊

**Comment by andrewtavis** [comment]
Pleasure working with you as well, @SaurabhJamadagni! Let's be in touch on #188 and #194 this coming week, but no stress on them :)

I updated the Wiki with info on results from the hackathon, so let's close this and take the rest to the issues themselves :)
