### ISSUE TITLE
Command mode doesn't switch colour on changing appearance mode

### ISSUE THREAD

**Issue by SaurabhJamadagni** [scribe-org/Scribe-iOS#193]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

- The prompt that says what the command does, doesn't change colour when you switch appearance modes. But if you exit command mode and go back again, then it works fine. The placeholder text does change colour though.
- Steps to replicate it:
  -  Select any command.
  - Change from light to dark mode or vice-versa without typing so that the prompt stays.

Images:
Before changing appearance mode:
![IMG_2957](https://user-images.githubusercontent.com/68957712/184291819-2913f1a1-6f28-4957-b3d0-37e95be89306.jpg)

After changing appearance mode:
![IMG_2958](https://user-images.githubusercontent.com/68957712/184291846-9d2209b7-a3af-44ad-bab5-d5a537796a4e.jpg)

After pressing 'x' and choosing the command again:
![IMG_2959](https://user-images.githubusercontent.com/68957712/184291937-2b12094d-18ee-4650-8734-df848762bc99.jpg)

I'll get to this after the Wikimania Hackathon, unless anyone else wishes to contribute. Feel free to do so :)

**Comment by andrewtavis** [comment]
The switching for this will need to go into [checkDarkModeSetColors](https://github.com/scribe-org/Scribe-iOS/blob/d3fcdbaa68216e1a73e6daf90b8541ff74f98b46/Keyboards/KeyboardsBase/ColorVariables.swift#L33) :)

**Comment by andrewtavis** [comment]
This is already switching the colors, so what could be happening is that the part that sets the colors for the command bar isn't being reset when the color mode changes 🤔

**Comment by andrewtavis** [comment]
Was closed in [f0bd0a0](https://github.com/scribe-org/Scribe-iOS/commit/f0bd0a0f98e48f7b7d93125fafd97feb9f7bf98b) :)

**Comment by andrewtavis** [comment]
@SaurabhJamadagni, I finally figured this out in [355bc80](https://github.com/scribe-org/Scribe-iOS/commit/355bc803b319edca0c4879877b18f917a6688d9f) after a poor attempt to fix it in [f0bd0a0](https://github.com/scribe-org/Scribe-iOS/commit/f0bd0a0f98e48f7b7d93125fafd97feb9f7bf98b) :)

**Comment by SaurabhJamadagni** [comment]
> @SaurabhJamadagni, I finally figured this out in [355bc80](https://github.com/scribe-org/Scribe-iOS/commit/355bc803b319edca0c4879877b18f917a6688d9f) after a poor attempt to fix it in [f0bd0a0](https://github.com/scribe-org/Scribe-iOS/commit/f0bd0a0f98e48f7b7d93125fafd97feb9f7bf98b) :)

Haha! Thanks for getting this issue done @andrewtavis. I was unable to get to it. 😊
