### ISSUE TITLE
Menu item to include period and comma in letter keys

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#196]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Something that Android users who switch to iOS usually want is the ability to have a period and a comma on the main keyboard so that they don’t need to press ‘123’ to reach them. An option could be included in Scribe’s menu to allow these keys to be included, with each being added by a separate switch. 

This would be a boolean option where the characters would be added to the array of letter keyboard characters for the keyboards that come from the interface variable files.  

- This issue is currently blocked by #16

### Contribution

I’d be happy to work on this when it’s unblocked :)

**Comment by japanese-goblinn** [comment]
@andrewtavis is this an active issue that I can work on? What is `#men` in `This issue is currently blocked by #men`? Maybe you can suggest more relevant issues that I can work on?

**Comment by andrewtavis** [comment]
> What is `#men` in `This issue is currently blocked by #men`?

What that is is "This issue is currently blocked by #what's that issue about the menu lemme type men and select the auto complete but then it doesn't give me the auto complete so I just get 'men' and don't realize it" 😄

We need to have a menu before this can be worked on, hence #16 needs to be done (fixed). This is a lot of work, so let's finish the current version and then we can move on to that and this issue as well. There is a lot of interest for this, so let's definitely keep it in mind :)

I'll write here with some others that you could consider 😊

**Comment by andrewtavis** [comment]
Regarding issues that might be of good to work on, you now understand a bit of what's going on under the hood for switching conjugations, so https://github.com/scribe-org/Scribe-iOS/issues/211 might be a good fit? That's greying out the left or right button if we're at one of the points where the break would occur in the new enums and disabling the button :) Would definitely be more involved, but I'd be happy to write some directions in there :)

**Comment by andrewtavis** [comment]
Note on this issue: as iPads have periods and commas on the letter keys, this option shouldn’t show up on iPads :)

**Comment by andrewtavis** [comment]
Resolved in the referenced #340 🙃 Thanks @SaurabhJamadagni! 🙌
