### ISSUE TITLE
Add UILexicon access to autocomplete and autosuggest

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#201]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

[UILexicon](https://developer.apple.com/documentation/uikit/uilexicon) contains unpaired lists of names in the user's address book. These words should also be added to the options for autocomplete and autosuggest :)

### Contribution

I'd be happy to work on this once autocomplete and autosuggest are finished, but this is also a great issue for another contributor!

- This issue is currently blocked by #188 and #194

**Comment by andrewtavis** [comment]
@SaurabhJamadagni, will explain your question in here :) What this means is that you can access a list of first name and a list of last names from the user's phone without asking for permissions. So if this works correctly, someone who has me in their contacts would type "McA" and get "McAllister" as a suggestion. I'm not sure if it'd be able to also get abbreviation like `tbh`, but then I don't think that'd be useful.

I do sometimes use this autocomplete feature, so I think it'd be nice to add :)

**Comment by SaurabhJamadagni** [comment]
Ohh I understand @andrewtavis. I first thought that it would be like the 'Text Replacement' feature from the system keyboard. I don't know if you have seen it but you can find it in Settings > General > Keyboard > Text Replacement.

This issue sounds good. Any feature that we use ourselves on a keyboard is a good idea to implement. Thank for the clarification :)

**Comment by andrewtavis** [comment]
Happy to clarify, @SaurabhJamadagni 😊 This isn't a part of v2.0.0, but it's something we can get to easily later on :)

**Comment by giaxonella** [comment]
#210

**Comment by andrewtavis** [comment]
Hi @giaxonella 👋 Not quite sure what #210 is in reference to 🤔 Would be happy to discuss if you'd like to explain :)

**Comment by andrewtavis** [comment]
Closed in 06eaf3b :)
