### ISSUE TITLE
Switch delete key icon when pressed

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#204]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

A common feature of system keyboards is that the icon of the delete button will shift to its filled out version when it's pressed, which currently is not implemented for scribe. The goal of this ticket would be that the icon would switch from `delete.left` to `delete.left.fill` while it's pressed.

### Contribution

Happy to work on this later or support someone who wants to try :)

**Comment by andrewtavis** [comment]
Thanks for your offer to help, @misteu! :) Assigned ✅😊

Let me know if you need any assistance with it later :)

**Comment by andrewtavis** [comment]
And btw, looking at [VocabularyTraining](https://github.com/misteu/VocabularyTraining), super nice to get your interest in the project 😊

**Comment by misteu** [comment]
Haha thanks! I‘m glad that you found my little app :)
Don’t look too close into the code as it’s pretty messy and parked for some time now.

I also thought about adding some separate German articles learning feature or even a separate app just for that (as I met a lot of learners struggling with it, I‘m a German native speaker). 

So, I‘m glad that I found your keyboard as it seems to have the same idea (and more) in mind!

**Comment by misteu** [comment]
Hey there,
had some time to look into the code, it's pretty well documented so it was a rather simple fix :)

I'll open an MR as soon as October start so that it counts towards Hacktoberfest :D

**Comment by andrewtavis** [comment]
Hi @misteu! That's exactly what we're looking for! Happy to merge at the start of October 😊

**Comment by andrewtavis** [comment]
> So, I‘m glad that I found your keyboard as it seems to have the same idea (and more) in mind!

Really happy you found it as well! Also happy that my documentation efforts made the fix easy for you :) Thanks so much for your efforts!

**Comment by andrewtavis** [comment]
Btw, @misteu, feel free to edit the [changelog](https://github.com/scribe-org/Scribe-iOS/blob/main/CHANGELOG.md) to add an entry about this for v2.0.0. Hope is that all the work for autocomplete and autosuggest will be finished in the next few weeks, and this will definitely be something to include within the design changes :)

**Comment by misteu** [comment]
opened a MR: https://github.com/scribe-org/Scribe-iOS/pull/212

**Comment by andrewtavis** [comment]
Hey @misteu! Thanks for the PR 🙌 Will get to this as soon as #209 is merged, which hopefully will be in the coming days 😊

**Comment by andrewtavis** [comment]
@misteu, [ecb08f0](https://github.com/scribe-org/Scribe-iOS/commit/ecb08f037aafbbaf8cbd051c9c7d08b3cb938bcb) is just because I resolved the conflict incorrectly :) Thanks again so much! As stated in the issue, let me know if I need to do anything else to get you your credit :)

**Comment by misteu** [comment]
Hey! yeah as commented there, please add the topic `hacktoberfest` to your repo or the `hacktoberfest-accepted` label to the MR :)
