### ISSUE TITLE
Default autosuggestions for pronouns

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#208]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Once work is finished on #194, another feature that can be added is to create baseline autosuggestions for when a user enters in a pronoun. This would require making sure that all the needed conjugations are present on Wikidata, but generally what we'd be looking for is always suggesting the conjugations of "have," "be" and "can" when a user types a pronoun. This has been found to be a pattern in system keyboards, and making sure that there's some consistency to these very common words makes sense (what words follow pronouns in each language should be checked though).

We'd need to make a variable `pronouns` in [KeyboardsBase/InterfaceVariables.swift](https://github.com/scribe-org/Scribe-iOS/blob/main/Keyboards/KeyboardsBase/InterfaceVariables.swift), and this array would be overwritten in the `set{languageCode}KeyboardLayout` functions with pronouns for each language within their respective `InterfaceVariables.swift` files. We'd then be able to check if one of these words has been typed, and then return the conjugations within `getAutosuggestions` in [KeyboardViewController.swift](https://github.com/scribe-org/Scribe-iOS/blob/main/Keyboards/KeyboardsBase/KeyboardViewController.swift).

- Currently blocked by #194

### Contribution

I'd be happy to work on this or direct someone in a contribution once #194 is finished.

**Comment by SaurabhJamadagni** [comment]
Hey @andrewtavis, I would like to work on this issue. Seems like the extension of what I have already been doing haha. Just to clarify, as we did for placeholder text, we'd have to create a pronouns array for each language. Then if the word typed by the user is in the pronouns array, the correct conjugation of [have, be, can] should be suggested. I am unable to understand how the right conjugation would be suggested. Will it require additional data or will we need to use the `autosuggestions.json` file for it? Could you help me out with this? I'll get to it immediately.

**Comment by andrewtavis** [comment]
This seems like a reasonable one for me too :) 

I'd say let's make use of the verbs we have, and if it can't work for a given language then we leave it. You can see in the German verbs file that we have the verbs "haben" (have), "sein" (to be) and "können" (to be able to), and in that way we can return the given conjugation based on what the pronoun is. We'd need to match the pronouns to their conjugations, but we could save the pronouns in a way that it links to the tense.

You could make a dictionary like:
```swift
-- The abbreviations below mean "First person singular", etc
-- Also sadly German uses the same word for she and they, so we'd need to skip they...
let dePronounToPresentTenseDict: [String: String] = [
  "ich": "presFPS",
  "du": "presSPS",
  "er": "presTPS",
  "sie": "presTPS",
  "es": "presTPS",
  "wir": "presFPP",
  "ihr": "presSPP",
  "Sie": "presTPP"
]
```

Then we could do something like the following:

```swift
if wordToSuggest in pronounToPresentTenseDict.keys {
  completionWords[0] = verbs["haben"][pronounToPresentTenseDict[wordToSuggest]]
  ...
}
```

With something like this we could then go through and figure out all the verbs for the given languages that normally come after pronouns, we could make a version of `dePronounToPresentTenseDict`, and once everything's assigned this is all done :)

Let me know what you think!

**Comment by andrewtavis** [comment]
Plus if we need the conjugations for verbs in other languages, then I can also just go in and add the conjugations into Wikidata myself 😊

**Comment by SaurabhJamadagni** [comment]
> With something like this we could then go through and figure out all the verbs for the given languages that normally come after pronouns, we could make a version of dePronounToPresentTenseDict, and once everything's assigned this is all done :)

Yup that sounds good @andrewtavis. I'll get started with this one then. Once I have something working I'll let you know and then we could discuss if the implementation I have is something we want to go ahead with or if we need to head in a different direction. I'll just use the above dictionary that you have given as reference for now.

**Comment by andrewtavis** [comment]
Sounds great, @SaurabhJamadagni! Looking forward to this! I think this will finish up all the autosuggestions that we're doing by hand, and the best thing is that we'll be using this one, the one for numbers, and the baseline suggestions regardless of when we at one point add in ML models to this 😊

**Comment by andrewtavis** [comment]
Will write to you in here, @SaurabhJamadagni 😊 I just send v2.0.0 along to Apple! 🚀 There likely will be some things we'll need to work out post release, but let's see how it works and react to it 💪 Thanks again so much for your hard and persistent work to get this out. A v2 is really something momentous 🎉

Will let you know when it's passed review!

**Comment by SaurabhJamadagni** [comment]
Let's go @andrewtavis! This is awesome! I am so excited for Scribe! Thanks for all your help in making this happen! Can't wait to hear back from you post review!! 🚀😊

**Comment by SaurabhJamadagni** [comment]
```swift
let dePronounToPresentTenseDict: [String: String] = [
  "ich": "presFPS",
  "du": "presSPS",
  "er": "presTPS",
  "sie": "presTPS",
  "es": "presTPS",
  "wir": "presFPP",
  "ihr": "presSPP",
  "Sie": "presTPP"
]
```

@andrewtavis, a dictionary like this will also be required for English pronouns in InterfaceVariables right? Example,

```swift
pronounsToPresentTenseDict = [
  "I": "presFPS",
  "he": "presTPS",
  "they": "presTPP"
  ..
  ...
]
```

**Comment by andrewtavis** [comment]
Yes, @SaurabhJamadagni :) We'd done a dictionary like this for each language and assign it to a base variable with all the other language specific ones :)

**Comment by SaurabhJamadagni** [comment]
@andrewtavis are there any resources I can look at for these pronoun declensions? I am losing it looking around on the internet for various pronouns and their cases. Especially for foreign languages!! 😅

**Comment by andrewtavis** [comment]
@SaurabhJamadagni, I'd say for right now just set it up for English and German, and we can talk about other languages later :) Plus we don't need to worry about the declensions anyway as that's more for I -> me -> my, but for thus we just want "I have" 😊 Plus let's not stress too much on what we don't understand from other languages, as it's open source, so get it out and hope someone corrects it 😄

**Comment by andrewtavis** [comment]
It’s already out, @SaurabhJamadagni!! :) Working really well :) I’m going to open an issue for a color change for dark mode as I think the conjugation labels are too dark. 

Another thing, we’re one step closer on the issue of the keyboard randomly crashing sometimes, as I’ve noticed that it just stalls a bit sometimes now. Not perfect, but progress! 🚀

**Comment by SaurabhJamadagni** [comment]
Haha true! Will work on the English and German ones for now then. Thanks! 😊

**Comment by andrewtavis** [comment]
Looking forward to the PR! We should also talk about what else to add into the autocompletions, as I think that they’re not including some words that we definitely could get from Wikidata. We have nouns, so far, and maybe we add in infinitives of verbs ant a couple other kinds? I think that all verb conjugations would be a bit much, but let me know what you think 🤔

**Comment by andrewtavis** [comment]
@SaurabhJamadagni, sorry again for the confusing review :) Steps ahead for this issue:

- [ ] Documenting what should be presented for all other languages
- [ ] Allowing for suggestions that aren't conjugated verbs
- [ ] Adding any verb conjugations that are needed to Wikidata
- [ ] Adding all final suggestions

**Comment by andrewtavis** [comment]
Let's just do this for French and Spanish for now, and we can append this as we go if there's a need 😊 For those languages the suggestions are:
- French: to be (être), to have (avoir), and ne
    - We have the conjugations for être and avoir
- Spanish: no, to be (ser) and and the reflexive pronoun for the pronoun (me, te, se nos, os)
    - Note that in Spanish we need to account for gender in first person plural (nosotros/nosotras)
    - We have the conjugation for `ser` in Spanish

**Comment by SaurabhJamadagni** [comment]
> Let's just do this for French and Spanish for now, and we can append this as we go if there's a need 😊 For those languages the suggestions are:

Works @andrewtavis. I'll start of with French. Could you create the necessary dictionary for Spanish? Or how do you wanna proceed?

**Comment by andrewtavis** [comment]
I can definitely make the dictionary for Spanish that maps pronouns to their reflexive counterparts, @SaurabhJamadagni  😊 Send along a PR for French when you can, and I can try to add things to it again 🤣

**Comment by andrewtavis** [comment]
😂😂 I hopefully will figure it out without toooo many auto-notifications, @SaurabhJamadagni 😊

Tomorrow or the next day is more than ok! Rest up and we’ll check in later when the PR comes through :)

**Comment by SaurabhJamadagni** [comment]
> French: to be (être), to have (avoir), and the word ne

@andrewtavis, we have the word 'pouvoir' (to be able to) in the french verbs. But it's conjugations are blank. Should I still include it in the array?

**Comment by andrewtavis** [comment]
I'd switch it over and do `ne` there and have that be consistent for each pronoun, @SaurabhJamadagni :) We'd need to do a simple check to see if the word is in `verbs`, and if not just present the word itself :) I only took a bit of French, but "Je ne, il ne, etc..." is quite common 😊

**Comment by andrewtavis** [comment]
Looking at the [Changelog](https://github.com/scribe-org/Scribe-iOS/blob/main/CHANGELOG.md), @SaurabhJamadagni, I think we'd be good to release v2.1 after this is closed, right? :) One massive update for v2 and another one soon after 🚀

**Comment by SaurabhJamadagni** [comment]
Yes @andrewtavis, looks like it. I am a bit out of town so couldn't get back to you sooner. Else would have closed this issue earlier 😅

I am returning today so will get some work done for this. When should we meet to discuss how to proceed after this? I think the major part to be discussed is implementing the data querying changes. Anything else that comes to mind?

**Comment by andrewtavis** [comment]
All good, @SaurabhJamadagni! There's no urgency for v2.1.0. I've also been super busy and wanted to fix #147 and #201 for some time, but just haven't had the chance 😊

We could do a call tomorrow morning if that'd work, or if not sometime in the evening next week :) I'd say let's keep the current focus for the data and have that be the goal for v2.2.0 🚀

**Comment by andrewtavis** [comment]
Also @SaurabhJamadagni, let me know what you think of the issue template I just wrote up in #104. I didn't want it to be toooo involved at this point, but we did get some PRs on main branches recently, so wanted to include that. The changelog has also already been updated with the expected changes for this issue, so no stress on that for the next PR 😎

Not too sure what else I'd add to it 🤔 I see other ones that ask the person to say if it's a bug fix or a feature request, but that's apparent from our issue labels. Maybe another check later on for if it passes tests, but that'll likely also be automated with GitHub actions, so also maybe not. Lemme know if you have any other suggestions!

**Comment by SaurabhJamadagni** [comment]
> Maybe another check later on for if it passes tests, but that'll likely also be automated with GitHub actions, so also maybe not. Lemme know if you have any other suggestions!

Hey @andrewtavis! Do you want me to work on a CLA (Contributor License Agreement)? I think as the contributor base grows, those would be necessary. I don't know much about them, but the few organisations I have contributed to in the past, all required to sign a CLA. Let me know what you think.

**Comment by andrewtavis** [comment]
We can definitely look into one, @SaurabhJamadagni, but then again we don’t have a place to put it for people to sign as of now as we don’t have a website. I’d say this is something for later, and at the start it’d maybe be “suggested.” With that being said, you’re welcome to work on it! 😊 This could potentially live in [scribe-org/Organization](https://github.com/scribe-org/Organization)?

**Comment by andrewtavis** [comment]
Hey @SaurabhJamadagni 👋 Firstly, I hope the test went well or goes well! [d24f25e](https://github.com/scribe-org/Scribe-iOS/commit/d24f25e0eb31c891c105ec3a1a3a53b539972032) adds the last part for this issue 😊 I figured it's easier for me to do this anyway as a Spanish speaker, and the big thing is that I think it's good that we get v2.1.0 out now before some meetings that I have next week, and also so we can really dive in to #96 for v2.2.0 :)

Let me know if you think a call to plan for that would be a good idea :)

**Comment by SaurabhJamadagni** [comment]
> Firstly, I hope the test went well or goes well!

Hey @andrewtavis! Thanks the easiest way I can describe this exam is that I have mixed feelings 😂

> [d24f25e](https://github.com/scribe-org/Scribe-iOS/commit/d24f25e0eb31c891c105ec3a1a3a53b539972032) adds the last part for this issue

Awesome! Thank you so much for the addition. Let's do a call to discuss the changes that will have to be made. Let me know when you would be available and we can plan one accordingly. 😊
