### ISSUE TITLE
Allow for case conjugation on case annotation button press

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#210]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As work on #197 progresses, an opportunity that opens up is the conjugation of case pronouns for the user when they press the annotation of a preposition. We could use the conjugation view for this, with the pronouns in question again being the label of the cells, but instead of verb conjugations it would be what the pronoun becomes in the given case. If a preposition has multiple cases, then in a similar way it would be great to allow the user to scroll through them as with verb conjugations.

Whether this should be included in v2.0.0 is up for discussion, and this would be problematic as as of now there would be no action on noun annotation button presses, but then we can also disable nouns or just leave them actionless and hopefully develop an action for them later 😊 Issues of user understanding should not necessarily hinder the rollout of what would be another very unique and helpful feature 🚀 

### Contribution

I'd be happy to work on this! It's a bit tough of an issue for newcomers, but I'm also happy to support if someone has interest :)

**Comment by andrewtavis** [comment]
We'd need to create variables that have the conversions from prepositions to the versions within the case to get this done, but this is common information that can be gotten from countless sources.

**Comment by andrewtavis** [comment]
This is now going to be included in v2.0.0 so that this functionality can be shown in the App Store videos :)

**Comment by andrewtavis** [comment]
@SaurabhJamadagni, if you could quickly check the PR for this, that'd be great 😊 This is a strong WIP implementation for this. Obviously it's not good that something like "den/die/das" would be inserted into the proxy for the user, as the ideality would be that we'd ask them which of the three they need and insert only that one, but this is what we can do without reworking the conjugation display in a crazy way. Worst comes to worst they just cancel and type it themselves, but having this as a reference is really convenient and something that I think people will really like 🚀

**Comment by SaurabhJamadagni** [comment]
> if you could quickly check the PR for this, that'd be great

Hey @andrewtavis, sorry I couldn't get to this PR today. I'll give it a look tomorrow first thing in the morning. Hope that's okay. Sorry for the delay. Could you give me a few test words or phrases that I can use to check what this implementation brings?

**Comment by andrewtavis** [comment]
Hey @SaurabhJamadagni, no stress! Tomorrow morning's perfect :) I should have given you more of a background to what's here :)

On a German keyboard if you type prepositions like `mit`, `in`, and `für` you'll see an annotation that is clickable. Clicking that will take you to a screen that like verb conjugation will allow you to scroll and select words. 

There's also an Easter egg in there that happens when you enter the word `Scribe` 🐣😊

**Comment by SaurabhJamadagni** [comment]
> On a German keyboard if you type prepositions like mit, in, and für you'll see an annotation that is clickable. Clicking that will take you to a screen that like verb conjugation will allow you to scroll and select words.
> 
> There's also an Easter egg in there that happens when you enter the word Scribe 🐣😊

Hey @andrewtavis, just reviewed the PR! The changes are great. I definitely didn't feel like it was a WIP implementation. What a great feature addition! 😊

Also, chef's kiss on the Easter egg haha 🚀

**Comment by andrewtavis** [comment]
Glad you liked the Easter egg, @SaurabhJamadagni 😊 I felt like it should at least do something when the user types `Scribe`, and this seems to be a happy medium of not too little and something that would distract :)
