### ISSUE TITLE
Disable and visually disable conjugation scroll buttons when applicable

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#211]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to functionally and visually disable the buttons that allow the user to scroll through conjugations when pressing them will not change the tense. This could also be used or case preposition conjugation in #210 :)

We'd want the icon of the button to be a bit more grey rather than black for light mode and white for dark mode, and within the conjugation assignment there should be check that would prevent the activation of one of the go left button or go right button if the user is at the first or last tense respectively.

### Contribution

Would be happy to work on this, or support if someone has interest in contributing!

**Comment by japanese-goblinn** [comment]
I think I want to take a look on this one

**Comment by andrewtavis** [comment]
Great! Before I assign it, let me give you a quick rundown of what this might entail and then you can confirm if you want to do it :)

Specifically what we're looking at is the following: https://github.com/scribe-org/Scribe-iOS/blob/561c2367d6a7b679747e8fb1dafc0cfbf1886c52/Keyboards/KeyboardsBase/KeyboardViewController.swift#L581

In that function you'll see where `conjugateShiftLeft` and `conjugateShiftRight` are activated, so we'll need that to be conditional, with the same conditions triggering coloration of the icons for the buttons. The button coloration is done here: https://github.com/scribe-org/Scribe-iOS/blob/561c2367d6a7b679747e8fb1dafc0cfbf1886c52/Keyboards/KeyboardsBase/KeyboardViewController.swift#L1195

You'll see the instances of `styleIconBtn` for `conjugateShiftLeft` and `conjugateShiftRight` below, with us needing to set `keyCharColor` to what I'd argue should be `specialKeyColor` so that it matches the conjugation labels which are an appropriate shade of grey given the mode.

Best way to do this is another enum? Likely better than all my booleans that are still flying around the code? 

```swift
enum ConjViewControls {
  case bothActive
  case leftInactive
  case rightInactive
}
```

Then we just use that as a means of determining the change in coloration and activating them or not? We could put it in the conjugate variables section here? https://github.com/scribe-org/Scribe-iOS/blob/561c2367d6a7b679747e8fb1dafc0cfbf1886c52/Keyboards/KeyboardsBase/ScribeFunctionality/CommandVariables.swift#L68

Let me know what you think! 😊

**Comment by japanese-goblinn** [comment]
@andrewtavis Oh, I not really getting what is need to be done here, so I think I'll pass on this. But thanks for trying to explain this.

**Comment by andrewtavis** [comment]
All good, @japanese-goblinn! Glad I explained it at the very least as it'll make it easier fort he next person or myself :)

**Comment by andrewtavis** [comment]
I have an issue for Russian localization that I'd like to check with you on as well :) I'm working on #218, which is the final feature for v2.0.0. In looking at it I'm realizing that there likely are many pronouns for Russian that aren't included in [RUCommandVariables.swift](https://github.com/scribe-org/Scribe-iOS/blob/main/Keyboards/LanguageKeyboards/Russian/RUCommandVariables.swift) because I don't understand how they work. Looks like as of now we have personal pronouns listed, but does Russian also do declension for regular pronouns like he, she, it, or possessive ones line mine and yours? If so, maybe I can make an issue where we add those in?

**Comment by SaurabhJamadagni** [comment]
Hey @andrewtavis, I'll wrap this issue up if that's ok 😊

**Comment by andrewtavis** [comment]
Great, thanks @SaurabhJamadagni! I think this'll be great to include now that that interface is being used so much. Assigning you, and let me know if any questions come up 😊

**Comment by andrewtavis** [comment]
@SaurabhJamadagni [14c098a](https://github.com/scribe-org/Scribe-iOS/commit/14c098a4fe13afb2ef18ded15fc6742991eb6ba2) was the final bit of this. I think that it looks better if we just change `shiftFormsDisplayLeft.isUserInteractionEnabled = false` rather than disable it completely, that way we have the button, but the arrow is greyed out 😊 Let me know what you think, and thanks for the work on this one! ◀️ ▶️ ✅

**Comment by SaurabhJamadagni** [comment]
> I think that it looks better if we just change shiftFormsDisplayLeft.isUserInteractionEnabled = false rather than disable it completely,

Yes @andrewtavis, it looks better! That was my plan too! I just couldn't figure out how to turn user interaction off. That's why disabled it entirely. This is perfect thanks!! 😊🚀
