### ISSUE TITLE
Refactor colors across Scribe-iOS

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#216]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As discussed in #166, the way that Scribe assigns colors is highly verbose and error prone. It would be better if the colors were defined in an asset file and accessed via an enum. This would allow us to not need to check for the `traitCollection` each time the color might switch based on light or dark mode.

### Contribution

This issue has already been requested as part of `Hacktoberfest`, and I'll of course be happy to support where needed 😊

**Comment by misteu** [comment]
Hey!
Thanks for creating the issue :) As discussed, I'm happy to help you out with this one.

**Comment by andrewtavis** [comment]
Assigned! Thanks for your willingness to help out! :) I'd say this might want to wait for #210, which should be closed by tomorrow 😊

**Comment by andrewtavis** [comment]
There's also a 1x1 conjugation/declension view that could be used for the information icon button that you implemented in #166. The issue to add a message to the user when they click that is #214 :)

**Comment by misteu** [comment]
I created a PR for it, see https://github.com/scribe-org/Scribe-iOS/pull/228

It looks like a lot of changes but most of it are added color asset JSONs as you will see :)

**Comment by andrewtavis** [comment]
Thank you, @misteu! I'll take a look at all of this tomorrow :) Really looking forward to these changes and learning more about the methods you're using 😊

**Comment by andrewtavis** [comment]
Thanks for all your work here, @misteu! Let me know if you have interest in anything else :) Big thing we're focussing on is #96 at the moment, and with that reworking the we read in data. At this point the Russian keyboard is crashing from the outset, with the current theory being that the JSONs being loaded in are much too large. I'll be looking into Core Data as suggested by another contributor 😊 You're of course welcome to work on anything that interests you, and know that your input is highly valued! Really has been great to have you 🚀

Thanks again so much 🙏
