### ISSUE TITLE
Refactor conjugation state changes to use case-switch

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#219]
### Terms

- [X] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

This is a simple issue that would help refactor the code a bit :) I noticed that in the `CommandVariables.swift` files I used `if` statements in the `ConjugationStateLeft` and `ConjugationStateRight` functions. An example is [DECommandVariables.swift](https://github.com/scribe-org/Scribe-iOS/blob/main/Keyboards/LanguageKeyboards/German/DECommandVariables.swift), where I correctly used `switch deCaseConjugationState` in a new issue, but in the `else` clause of `if commandState == .selectCaseConjugation` we still have `if deConjugationState == .indicativePresent`. This should be switched to a `case-switch` statement like the following for `deConjugationStateRight`:

```swift
switch deConjugationState {
case .indicativePresent:
  deConjugationState = .indicativePreterite
case .indicativePreterite:
  deConjugationState = .indicativePerfect
case .indicativePerfect:
  return
}
```

This issue would be to switch all `ConjugationStateLeft` and `ConjugationStateRight` functions across all languages to use `switch-case` statements.

I'd be happy to support someone on this if there's interest! 😊

**Comment by japanese-goblinn** [comment]
@andrewtavis Hey! I would like to implement this refactoring

**Comment by japanese-goblinn** [comment]
@andrewtavis working on it!

**Comment by andrewtavis** [comment]
Hey, @japanese-goblinn! Thanks for your willingness to help, and also for the PR! I'll check this later today 😊

**Comment by andrewtavis** [comment]
Thanks for the efforts here, @japanese-goblinn! Very nice to work with you on this 😊 Closing this as we're all done 🚀
