### ISSUE TITLE
Small issue with RU localization

### ISSUE THREAD

**Issue by japanese-goblinn** [scribe-org/Scribe-iOS#221]
### Terms

- [X] I have searched [open localization issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+is%3Aopen+label%3Alocalization)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

I've noticed a small issue in `ruGetCaseConjugationTitle`. Instead of `Винительный местоимения` it should be `Винительное местоимение`. And this applies to other cases. If you @andrewtavis don't mind I can fix this and create a PR

**Comment by andrewtavis** [comment]
Thanks for pointing this out, @japanese-goblinn! You'd be welcome to submit a PR for this and other issues you see in the Russian keyboard :) Honestly I'm just using Google Translate for this, so I'd love some support 😊

**Comment by andrewtavis** [comment]
Closing this now that #223 is merged :) Thanks for the efforts here, @japanese-goblinn! Really have been hoping for someone to come along and help with the Russian localizations. All of this has been very helpful! 🚀
