### ISSUE TITLE
Add description of debugging the debugger to contributing and readme

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#242]
### Terms

- [X] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

Something that's very problematic for new Scribe contributors is that it's hard to get the debugger to work properly. As keyboards are extensions running within the Scribe app, developers need to have their build target be the keyboard that they're testing on to have breakpoints function properly. This was only discovered recently and makes development much smoother 😊

This issue is to make note of this in [CONTRIBUTING.md](https://github.com/scribe-org/Scribe-iOS/blob/main/CONTRIBUTING.md) as well as within the [contributing section of the readme](https://github.com/scribe-org/Scribe-iOS#contributing). It's very important that those who are interested read this message, so I'd suggest that it there be an H3 section above `### Ways to Help`. I think even a section like `### ⚠️ Note on Debugging ⚠️` would be appropriate for this :)

- Note that this issue has been requested already :)

**Comment by andrewtavis** [comment]
@helloITdepartment, issue's here for you 😊 GitHub renders ⚠️ as `⚠️` but large in readmes, kind of like the up arrows for navigating back to the table of contents. I kind of like it, but am open to your suggestions on how to make it more apparent :)

Great talking to you!

**Comment by helloITdepartment** [comment]
Thanks! I'll get to work on it soon as I'm assigned. Gotta get those four hacktober requests in soon anyway 😉

**Comment by andrewtavis** [comment]
Assigned, @helloITdepartment! I'll check the other PR Thursday evening after a presentation I have :) Thanks for it!

**Comment by andrewtavis** [comment]
I made some minor changes to the descriptions and added the section to the table of contents in the changelog, @helloITdepartment, but aside from that all of this was great 😊 Thanks for your efforts here, and looking forward to working with you on more issues! 🚀
