### ISSUE TITLE
Allow for dark mode responsiveness in app screen

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#260]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

In preparation for #16, it would be great if the Scribe menu could be made responsive to light and dark mode. This would entail editing the color assets within [Scribe/Assets.xcassets/Colors](https://github.com/scribe-org/Scribe-iOS/tree/main/Scribe/Assets.xcassets/Colors) so that they're responsive to light and dark modes, and also potentially implementing a color shift within the app itself.

### Contribution

I'd be happy to work on this or assist someone who wants to give it a try 😊

**Comment by SaurabhJamadagni** [comment]
Hey @andrewtavis! I would love to work on this issue. Could you assign me to it?

**Comment by andrewtavis** [comment]
@SaurabhJamadagni, 89d1376 and 3bab4ef put through the medium weight for the `View privacy policy` button and shifts the colors in the way we were discussing in #265 :)

Thanks for your work on this! Closing now 😊
