### ISSUE TITLE
Autosuggestions not triggered after return is pressed for new line

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#270]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

An issue with autosuggestion is that there are no values shown after the user presses the return key to make a new line. Sometimes there are, but often times there aren't. Along with this, after return is pressed there usually are no autocompletions for the first word being typed on the new line. This is problematic as it's breaking the user's expectation of always seeing autosuggestions or completions unless they're typing a long, unrecognized word. 

Happy to work on this myself eventually or support someone who has interest in working on it 😊

### Device type

iPhone and iPad

### Versions

I assume this is happening for all versions.

**Comment by gitpushOmnik** [comment]
I can work on this issue @andrewtavis. Can you please assign it to me?

**Comment by andrewtavis** [comment]
Sure thing, @gitpushOmnik :) A quick thing to check with you is that you've read the [Note on Debugging](https://github.com/scribe-org/Scribe-iOS/blob/main/CONTRIBUTING.md#note-on-debugging) in the contribution guides? This might be an issue where you'd want to check variable values, so be sure to select they keyboard that you're testing on as the target rather than the Scribe app itself 😊

**Comment by andrewtavis** [comment]
Happy to explain further points to you as well! Let me know what would help :)

**Comment by gitpushOmnik** [comment]
Yes I have already read the contribution guide. Thank you so much. Would ask you any questions for implementation if I have any! :)

**Comment by gitpushOmnik** [comment]
Hello @andrewtavis. I have figured out how to fix this bug. The only problem is, after the user presses the return key, do you want the autocomplete function to get triggered or the autosuggestion function? For example, at the very start we have "Ich | die | das " as the suggestions. So lets say a user types "ich". And after that if they press the return key, do you want "habe | bin | kann " to be displayed or do you want the default auto suggestions "ich | die | das" to be displayed again?

**Comment by andrewtavis** [comment]
Hey @gitpushOmnik! Glad to hear you've figured it out :) I'd say it'd be best to do the default auto suggestions as a return implies a new train of though 🤔🙃 Let me know if there's another way I can help!

**Comment by andrewtavis** [comment]
Thanks for your work on this, @gitpushOmnik!
