### ISSUE TITLE
Remove explicit variable definitions where unnecessary 

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#273]
### Terms

- [X] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

This is a very simple issue that's great for someone wanting to make a first contribution to Scribe :) What we want is to make our initial variable assignments across the codes consistent. At times we have assignments like either of the two methods below:

```swift
var capsLockPossible = false
var annotationState: Bool = false
```

It would be great if someone would go through and remove all the unneeded explicit assignments. This is based on [this SO question's answers](https://stackoverflow.com/questions/29551246/is-it-best-practice-to-explicitly-declare-variable-types-on-declaration), which further reference the [Kodeco (Ray Wanderlich) Style Guide](https://github.com/kodecocodes/swift-style-guide#type-inference).

Happy to discuss this issue with someone 😊

**Comment by muntasir14** [comment]
Hi, I would like to try this one. Is it alright?

**Comment by andrewtavis** [comment]
Hey @muntasir14! Yes, I think that for a second contribution this issue is also great 😊 I'll get to #274 soon :) Thanks for sending it along!
