### ISSUE TITLE
Word being replaced in emoji prediction

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#278]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

Emoji autosuggestions were added via #51, but one lingering issue is that at times the word is being replaced rather than the emoji being added after it (similar to how an emoji autocompletion would replace the word, but this is not the desired behavior). An instance of this is when typing the word `Kuss` in German, meaning “kiss”, where when pushing either of the emoji suggestions the word is replaced by the emoji instead of the emoji being inserted after. 

This is likely a conflict with the features implemented for #250 and #256 :)

### Device type

iPhone and iPad

### Versions

I’m assuming all versions

**Comment by ArslanYM** [comment]
Is this issue fixed?

**Comment by andrewtavis** [comment]
Hey @ArslanYM! Thanks for your interest in Scribe :) It’s yet to be fixed and I haven’t started working on it. Let me know if you have interest and I’d be happy to assign it to you? 😊

**Comment by andrewtavis** [comment]
@ArslanYM, I'm going to work on #277 today and think it makes sense if I work on this as well as I'll be testing this behavior :) There are a few more new issues that I made today that could also be of interest 😊

**Comment by andrewtavis** [comment]
Note: specifically there's an issue where the word that would be displayed to a user in case the space autosuggest insertion was wrong is the word itself, but then it was the only option so the space should function normally in this case.

**Comment by ArslanYM** [comment]
No I haven't

**Comment by andrewtavis** [comment]
Great :) Will send along a PR for this shortly 😊

**Comment by andrewtavis** [comment]
Closed in 97c0afb 😊
