### ISSUE TITLE
Case annotations after contracted prepositions

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#279]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Scribe shows case annotations after German prepositions like “in”, “für” and “zu”. As of now it does now show them on cases where a combined preposition has been typed like “zu” + “der” = “zur”. This issue would add a condition to show the appropriate preposition annotations after such words. This issue could also be done in Python in Scribe-Data as well in a way that would simply generate a JSON file with the appropriate data to also include these :)

### Contribution

Happy to work on this or support someone who has interest :)

**Comment by andrewtavis** [comment]
The person has potentially chosen the right option and doesn't need the annotation, but the behavior of showing the annotations after prepositions should be maintained.

**Comment by ArslanYM** [comment]
@andrewtavis Can i work on this?

**Comment by andrewtavis** [comment]
Hey @ArslanYM! Thanks for your interest both here and in #278 😊 You’d be welcome to work on this. Let’s chat quickly on what we think is the best way to do this. Should we add entries to the `prepositions` dictionary on the Swift side, or should this be handled on data preparation? I’m fine with both, and I guess doing the former would be easier and shouldn’t be frowned upon as the data output is sound: “zur” in itself isn’t a preposition. 

If this sounds good, then I think the change would go into `loadKeys` in the main view controller — first checking if the keyboard is German, and then in the initial keyboard load step we’d add the entries to `prepositions` :)

Lemme know what you think! Assigning you now 😊

**Comment by andrewtavis** [comment]
[This line right here](https://github.com/scribe-org/Scribe-iOS/blob/faa21c91bdd19c921bafd9e0c58d9203f18cef4c/Keyboards/KeyboardsBase/KeyboardViewController.swift#L1270) is the conditional that checks if it's the first time the keyboard is loading. Within there is generally where I put the logic that extends the dictionaries and such. You can see in the line below that's in there how we'd add entries:

```swift
nouns["Scribe"] = [
        "plural": "Scribes",
        "form": ""
      ]
```

We'd then generally just need to define which preposition combinations need to be included, check for the German keyboard, and add them in the above way :)

**Comment by ArslanYM** [comment]
@andrewtavis  Sorry for bothering. I don't think i can work on this.

**Comment by andrewtavis** [comment]
No bother! Happy to help you figure it out of you have interest, but no stress if not :)

**Comment by andrewtavis** [comment]
Closed in 97c0afb 🚀

**Comment by andrewtavis** [comment]
Thanks again for chatting with me about this, @ArslanYM! Was really helpful to explain it and plan it out for myself 😊 If you're looking for a good first issue, then #280 would be a great one to jump in to :)

Have a nice weekend!

**Comment by ArslanYM** [comment]
Sure thing. Thankyou for being a great mentor.

**Comment by andrewtavis** [comment]
My pleasure! Thanks again for your interest 😊 Let me know in #280 if you want to be assigned, and again very happy to explain or discuss further :D
