### ISSUE TITLE
Duble dash inserts em dash in proxy

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#280]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is a simple addition to Scribe that allows for an em dash `—` to be inserted if the user does two dashes `-` in a row. This is typical keyboard behavior, and also allows for a easier access to that character. I think putting a conditional for `case "-":` after [this part in the function that determines key functionality](https://github.com/scribe-org/Scribe-iOS/blob/faa21c91bdd19c921bafd9e0c58d9203f18cef4c/Keyboards/KeyboardsBase/KeyboardViewController.swift#L2070) would be a good way to implement this. We'd need to check what the last character in the text proxy is, and afterwards we could do the replacement if there are two in a row 😊

### Contribution

Happy to work on this myself or help someone who has interest!

**Comment by andrewtavis** [comment]
Something to consider is whether we need a menu item for this once #16 is finished 🤔

**Comment by jocoand** [comment]
Hello, is the issue still open? I am interested try solve the issue

**Comment by andrewtavis** [comment]
Hi @jocoand! Thanks for your interest in Scribe 😊 Issue is still open, and I’m happy to get some help with it. I’ll check #285 sometime today :)

**Comment by andrewtavis** [comment]
Thanks for your work on this, @jocoand! Appreciate the help, especially when I'm trying to do a release soonish 😊 Let me know if you'd like suggestions of what other issues you could work on. Would be happy to collaborate again :)
