### ISSUE TITLE
Repeat emojis when using autocomplete/suggest

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#283]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

An idea of how to make the emoji autosuggestions from #51 and the soon to be committed autocompletions from #277 is to keep the emoji view that the user has just interacted with and allow them to press the same emojis multiple times. The general idea on this for the German keyboard would allow someone to write:

```
Hund 🐶🐶🐶🐶🐶🐶
```

It's my expectation that a person would more likely repeat an emoji than use a base autosuggestion that would normally follow it. We'd need the space between the emojis to be deleted after the first one by checking that an emoji autosuggestion or completion has been used, and then the defauly added space could be ignored so long as the user keeps doing more of them :)

### Contribution

Happy to work on this or give someone some guidance on how to work on it 😊 This Issue is a bit difficult though given all the parts of the interface that will need to be conditionally changed.

**Comment by andrewtavis** [comment]
Closed by 4ddf305 😊

@SaurabhJamadagni, let me know what you think of this when you get a second! I thought of it today while working on #277 and really like it :) :)

**Comment by SaurabhJamadagni** [comment]
> let me know what you think of this

Hey @andrewtavis! This is a good one! Really like it too. I knew something was missing when someone selected an emoji suggestion but just couldn't put my finger on what it was. This is nice 😄
