### ISSUE TITLE
Keyboard load is slow because of autocomplete keywords creation

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#286]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

Scribe keyboards are loading slowly, with the main issue being the function `firstKeyboardLoad()`, the part of [loadKeys()](https://github.com/scribe-org/Scribe-iOS/blob/1d36b664a6465331038fe520491a8ab15e9c2ee2/Keyboards/KeyboardsBase/KeyboardViewController.swift#L1392) that is triggered on the first load of the keyboard. At this point we're doing a few very intensive operations to create the variable `autocompleteWords` (now renamed `autocompleteLexicon`). Referencing this variable is intensive in and of itself, but new additions I'm trying to do right now are actually fully crashing the keyboard at start. Removing these operations returns to a smooth load that we had before the addition of autocomplete.

This issue is to document and work on optimizing `firstKeyboardLoad()` so that we can have smoother load times. Along with this is included the addition of emoji keywords as words within the autocomplete lexicon, which as of now is not possible with the current operations. 

### Device type

iPhone and iPad

### Versions

All versions after autocomplete was added

**Comment by andrewtavis** [comment]
This issue is related to #96 as part of this issue will be solved by loading the JSONs into SQLite databases :)

**Comment by andrewtavis** [comment]
Closed via 53ef8c4 🚀🔥

@SaurabhJamadagni, this issue was a major boost to the UX :) The keyboard's no longer loading so long — direct changes for keyboards with small/medium data sets, and now Russian with it's 194K nouns seems to be the only one with any lag, but it at the same time is at least loading, which was not the case before. This was definitely a lot of the problem that we had with #96, with that issue now being focussed on the new data infrastructure to speed it up as much as we can :) Big thing is that I at least was really focussed on the JSONs being a problem, which they are, but the big thing that was causing a slowdown at load was the creation of the autosuggestions in the way that it was being done 😊

Lots of changes recently! Just #96 before v2.2.0 now! 🚀

**Comment by SaurabhJamadagni** [comment]
@andrewtavis this is awesome! How did this occur to you? I was thinking the load of this problem will lie on fixing the data structuring problem. Read through the commit right now. Looking nice. Thank you for this solve, it is going to help out immensely! 😄 🚀

**Comment by andrewtavis** [comment]
@SaurabhJamadagni, it occurred to me when I tried to add the emoji keys to the autocompletion lexicon in the same way that we were doing it and then the keyboard crashed on load 😅 At that point I removed all the other additions to the lexicon for a test and realized that the keyboard loads normally without overloading the `firstKeyboardLoad` conditional :)

Another note for you is that in #282 I switched around the way that the emojis are being triggered. Just FYI, that's now being controlled by an instance of the [EmojisToShow](https://github.com/scribe-org/Scribe-iOS/blob/a798fd6f15487f6fae2a4e235c1ffc330883de07/Keyboards/KeyboardsBase/ScribeFunctionality/CommandVariables.swift#L16) enum rather than a boolean :)
