### ISSUE TITLE
Make boolean checks consistent throughout the app

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#289]
### Terms

- [X] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

Similarly to #273, the way that Scribe is defining booleans is inconsistent throughout the app. We use both of these standards in various places:

```swift
if firstKeyboardLoad == true {}
if inputWordIsCapitalized {}
```

We should make a decision on which of these should be used throughout :) It would be interesting to know which is more the standard within the Swift community so we can follow that 😊

Once the decision is made, this issue would be great for someone who wants to first contribute to Scribe 🚀 Those interested in working on this are welcome to reach out :)

**Comment by andrewtavis** [comment]
@SaurabhJamadagni, obviously not an issue for you, but it'd be great to get your opinion on which of the above boolean check methods would be best :)

**Comment by SaurabhJamadagni** [comment]
Hey @andrewtavis! I have seen the latter be the more prominent standard. Even if the naming style is similar to `firstKeyboardLoad`, I rarely see the variable equated to `true` explicitly. 

We could switch the booleans to be variables with names that have some tense change of the verb is. For example, `firstKeyboardDidLoad`, `isAutoActionState`, etc.

That's been my observation. A verbose variable name which doesn't need to be explicitly compared against a Boolean value should be a good direction. 😄

**Comment by andrewtavis** [comment]
Thanks for your input, @SaurabhJamadagni! So for this `good first issue` the task will be to remove all the explicit boolean comparisons in the app :) I'll go through and change any variable names that don't make sense as boolean from their name, or whoever works on this could also try if they want 😊

**Comment by neisenlo** [comment]
Could I try fixing this?

**Comment by andrewtavis** [comment]
By all means, @neisenlo! Thanks for sending along the PR :) Will assign you and check it 😊

**Comment by andrewtavis** [comment]
@neisenlo, the minor updates I did in 94492d2 including variable name changes close this issue 😊 Thanks so much for your help! Happy to work with you again if you find something of interest 🚀
