### ISSUE TITLE
Combine selectedWordAnnotation and typedWordAnnotation

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#290]
### Terms

- [X] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

This issue is a great `good first issue` for people wanting to learn a bit about Scribe 😊 In doing some refactoring I'm realizing that two functions within [Keyboards/KeyboardsBase/ScribeFunctionality/Annotate.swift](https://github.com/scribe-org/Scribe-iOS/blob/main/Keyboards/KeyboardsBase/ScribeFunctionality/Annotate.swift) — `selectedWordAnnotation` and `typedWordAnnotation` — basically have the same logic, the word being checked in each case is just set in a different way in both cases. This issue would be to simplify the code by creating a third function `wordAnnotation` that would be above the other two functions in the code and have their shared logic. `selectedWordAnnotation` and `typedWordAnnotation` would then have their shared logic removed, and each would call `wordAnnotation` and pass `wordToCheck` as an argument.

Would be happy to discuss and work with someone on this!

**Comment by vaibhavmishra4g** [comment]
hey could you assign me the issue and pls guide me for the solution

**Comment by andrewtavis** [comment]
Hey @vaibhavmishra4g! Thanks for your willingness to help 😊 First thing first would be to check which parts of the code for the two functions is repeated. Anything that’s repeated would then be moved into a third function, `wordAnotation`. From there we just call the new function from within the old two so that we keep the code DRY :)

Assigning you now! Let me know if you have any other questions 😊 Happy to help 😇

**Comment by vaibhavmishra4g** [comment]
so basically i have to create a parent function and it would further encapsulate the two similar child functions?

**Comment by andrewtavis** [comment]
You can think of it that way, yes :) Big this is that it doesn’t encapsulate the other functions they have their own logic. It’s more a base function that then has a different argument passed to it in the two functions that call it :) If you have suggestions though those would be welcome! 😊 Big thing is we want to get all the repeated code for each of these functions to be in one place :)

**Comment by andrewtavis** [comment]
Hey @vaibhavmishra4g 👋 Just checking in to make sure that you don't have any further questions :) No stress if you need a bit of time. I'm just planning my issues and think I'll jump into the related #164 when we're done with this one 😊

**Comment by andrewtavis** [comment]
0fca0fa closes this issue :) Sorry to take this over, @vaibhavmishra4g! As [I said](https://github.com/scribe-org/Scribe-iOS/issues/290#issuecomment-1517014650) I'm trying to start work on #164 and this needed to be done before. Happy to have your work on another issue if there's interest. I just made #296 today which should be fairly straight forward 😊 Thanks for the discussion here!
