### ISSUE TITLE
Update suggestions and emojis based on selected annotation

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#291]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue was rewritten after realizing that the feature should be much bigger. As of now the autosuggestions and emojis are not being updated when a user moves the cursor to another part of the text proxy. Furthermore, a feature of Scribe is that when a word is selected and the Scribe key is pressed, that we can see the gender or case annotations for the given word (gender for nouns and case for prepositions). What makes sense with this feature would be that if there were emoji suggestions for the word that's selected, that along with the annotation these would also be shown. As of now this is not the case, with the suggestions normally being for the previous word in the proxy.

Example: in the German keyboard when a person types the word `Buch` they see book emoji suggestions. If the keep typing and then select `Buch` again and press the Scribe key, they see the Annotation, but they don't see the emojis. Having the emojis there would also give the user the ability to replace the selected word with an emoji if they want 🙃

### Contribution

Would be happy to help someone who's interested in working on this, or can also get to it myself at some point in the future 😊

**Comment by SaurabhJamadagni** [comment]
Hey @andrewtavis, assign me this one whenever you have time. I'll get started on it :)

**Comment by andrewtavis** [comment]
Sounds good, @SaurabhJamadagni! Assigning it now 🚀

**Comment by SaurabhJamadagni** [comment]
Breaking the issue down into sub-tasks:
- [x] Emoji suggestions when pressing Scribe key.
- [ ] Updating autosuggest when cursor is moved.

Hey @andrewtavis, I am not able to figure out how I can detect change in cursor position. From the docs I looked through, we could use a delegate method that is called when the cursor changes but that is for a UITextInput and not UITextDocumentProxy. Can you think of any way we can detect cursor movement? One absolutely terrible approach that came to mind is to run a timer that checks if the cursor is between words and not at the end after a set interval of time. But I really don't want to do it that way. Let me know if anything comes to mind :)

**Comment by andrewtavis** [comment]
@SaurabhJamadagni, let me know how you're doing on this one :) As I said on Matrix, totally fine to send along the current work on this one and we can figure out the cursor movement together 😊

In other news I finished up #164! 🥳 Really is looking great 🚀 I think that that feature and this one when combined with the other the minor issues completed is enough for v2.3.0 😊

**Comment by andrewtavis** [comment]
Sorry for the accidental close 😅

**Comment by SaurabhJamadagni** [comment]
Hey @andrewtavis, I thought the first part is working correctly but there's a bug I came across today. I'll push the changes right now. I am sorry, I wish I could push the fixed version of it. 

To produce the bug: 
- Type "Buch Homburg Jacken"
- Select "Buch" and press the scribe key. Should work as intended.
- Select "Jacken" and press the scribe key. Should also work as intended.
- Now select "Homburg" and you should still see emojis intended for "Buch"

The problem is some kind of a unintended reassignment somewhere. I couldn't trace it today. Will push the changes. Hope they are a little bit helpful atleast 😅

**Comment by SaurabhJamadagni** [comment]
Created a PR for the changes. 

Just saw the new annotation changes. Had not pulled from the main branch in quite a while. I love the way it looks! Awesome stuff 🤯 Could you share issue number that added those changes? Curious about the SQL involved if any.

**Comment by andrewtavis** [comment]
Hey @SaurabhJamadagni! The issue number for the new annotation work was #164 :) There wasn't any new SQL involved necessarily, just checking if the word for the auto action was in the nouns table and then coloring the new style of annotations if it's in there. The main function that does it all is the following:

https://github.com/scribe-org/Scribe-iOS/blob/3798c830ff3d4b6a66a677c374b880972dee0336/Keyboards/KeyboardsBase/ScribeFunctionality/Annotate.swift#L252

Glad you like the new changes! I'll check your PR and hopefully be able to give it a fix and add in the cursor move (or we can give up on this if it's not possible).

**Comment by andrewtavis** [comment]
@SaurabhJamadagni, 8f409ec finishes up what you were working on in #298 😊 Trick was triggering it all within `conditionallySetAutoActionBtns` such that within both `getAutocompletions` and `getAutosuggestions` there's a check to see if text is being selected, and if so then the prefix is replaced with the selected text for the remainder of the operation. We now have the autosuggestions also updating :) :)

I'll look into updating the suggestions and emojis based on moving the cursor. Has to be possible somehow 🤔 Once that's done we're ready for v2.3.0!

**Comment by andrewtavis** [comment]
Looking at it a bit more, @SaurabhJamadagni, the transitions based on cursor move really seem to be hidden in the documentation…. I’m gonna close this one and make a new one for the cursor interactions only that we can get to at some point :) More important that we release the new updates 😊

**Comment by andrewtavis** [comment]
Looking at it a bit more, @SaurabhJamadagni, the transitions based on cursor move really seem to be hidden in the documentation…. I’m gonna close this one and make a new one for the cursor interactions only that we can get to at some point :) More important that we release the new updates 😊

**Comment by andrewtavis** [comment]
Just sent v2.3.0 off for review, @SaurabhJamadagni 😊 Definitely an improvement over 2.2.0, and that's really saying a lot :) :) I'll update the [project board](https://github.com/orgs/scribe-org/projects/1) by archiving the issues that were done for this release and give the issue priorities an update :)

**Comment by andrewtavis** [comment]
Already live 😊😊 Super cool stuff! 🥳
