### ISSUE TITLE
Add German indefinite articles to case-declension tables

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#303]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As a part of some of the article selections that we'll be doing in #302 we'd need to also include the indefinite articles for German into the case-declension tables. This would require the values first being included in [LanguageKeyboards/German/DECommandVariables.swift](https://github.com/scribe-org/Scribe-iOS/blob/main/Keyboards/LanguageKeyboards/German/DECommandVariables.swift) and then adding them to the switch declension display ordering in the same file. We'd also need to rename the current articles as definite pronouns rather than just pronouns so that there's a distinction. After this we can add the needed code into the declension display functions to get it all working correctly 😊

### Contribution

I'll work on this soon to prepare to work on #302 or am also happy to support :)

**Comment by andrewtavis** [comment]
Note that this is also a `good first issue` if someone has interest :) Happy to direct someone in how to add all this information in in the right places 😊

**Comment by lucastronova** [comment]
I have a PR open for this issue (#306)

**Comment by andrewtavis** [comment]
Thank you, @lucastronova! Will get to it soon :) Really appreciate the help with this 😊

**Comment by andrewtavis** [comment]
06bc3ae does the change that I mentioned in the PR, @lucastronova :) Thanks again for your work here!
