### ISSUE TITLE
Menu items for social links

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#315]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to create menu items for the various social links that the Scribe community has within the about tab of the menu being created in #16. These links are detailed in the [designs in Figma](https://www.figma.com/file/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?type=design&node-id=405%3A393&t=nCPFM9zwswgPWWI6-1) :) The links we need are:

- To the [Scribe-iOS repo on GitHub](https://github.com/scribe-org/Scribe-iOS) with the GitHub logo
- To the [public Scribe Matrix space](https://matrix.to/#/#scribe_community:matrix.org) with the Matrix logo
- To the [Scribe-iOS issues on GitHub](https://github.com/scribe-org/Scribe-iOS/issues) with a ladybug icon
- A mailto link to the Scribe email address (we should discuss this email) with an email icon
- A link to Scribe on the App Store asking people to rate it with a star icon

Note:

- Blocked by #16 and #309

### Contribution

This issue is a part of Google Summer of Code 2023 ☀️ Happy to support as needed 😊

**Comment by SaurabhJamadagni** [comment]
Hey @andrewtavis, we are checking if the base iOS version is above or below 10 in the code below. Do we need this check as Scribe seems to have a deployment target of iOS 13.0? I couldn't think of any use case and just wanted to make sure.

https://github.com/scribe-org/Scribe-iOS/blob/fa59078df3879e68e7e805dc4a936379e2cd636a/Scribe/ViewController.swift#L347-L352

**Comment by SaurabhJamadagni** [comment]
Also @andrewtavis, could you reshare the temporary email address we are redirecting the user to? I can't remember what it was 😅

**Comment by andrewtavis** [comment]
scribe.language@gmail.com

I have some notes on potential URLs for next week :)

**Comment by andrewtavis** [comment]
Closed via #328 😊 Thank you, @SaurabhJamadagni! 🥳
