### ISSUE TITLE
Share Scribe menu item

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#316]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to add an option to the menu whereby users can share Scribe with others. This option would appear on the about tab of the menu being created in #16. We should first research how to effectively trigger a share UI, and then the link being pointed to would then be Scribe on the App Store 😊 

- Blocked by #16 and #309

### Contribution

This issue is included in Google Summer of Code 2023 ☀️ Happy to help as needed!

**Comment by SaurabhJamadagni** [comment]
Hey @andrewtavis, I think we are done with this one too. Shall we close this issue?

**Comment by andrewtavis** [comment]
Yes, true, @SaurabhJamadagni! This issue was closed by #328 :) Closing now 🥳
