### ISSUE TITLE
Menu back button component

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#320]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would be to create a baseline back button component that would be used and reused across Scribe menu pages. What it would include would be a chevron pointing to the left and a field that would receive a string that describes what the user would be going back to. The colors for the aforementioned elements would be determined by light or dark mode automatically. Furthermore, this element should be stuck to the top of the menu screen such that as the user scrolls down it will still be visible with a bit of an opacity less than one. 

### Contribution

This issue is included in Google Summer of Code 2023 ☀️🥇 Happy to help research how best to set up this component 😊

**Comment by SaurabhJamadagni** [comment]
This should be automatically handled by using a [Navigation Controller](https://developer.apple.com/documentation/uikit/uinavigationcontroller) on the root view. It would maintain a stack of the views that are pushed on top of it. A back button is created automatically, tapping which pops the top most view bringing us back to the previous view.

I'll demo this in our meeting @andrewtavis. It is probably exactly what we need. But we can make changes if required. From what I can see, we can adjust the back button tint as well as give it custom text. Although, by default it takes on the title of the previous page as its text.

**Comment by andrewtavis** [comment]
This feature was included in #324 in so far as it's built in behavior for the new app screen components :)
