### ISSUE TITLE
Add app hints to convey instruction/information

### ISSUE THREAD

**Issue by wkyoshida** [scribe-org/Scribe-iOS#329]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

**WHAT**

This issue is for app hints on each app page, i.e. overlaid text that provide quick instruction/information about a page (purpose of the page, what a user can do on the page, etc.) These would:
- Exist for each app page
- Automatically display the first time a user visits a page (will have to store this interaction history)
- Use a light bulb icon :bulb: on each page that can be clicked to display the app hint for the page again 

**EXAMPLE USES**
- Could be used to also prompt users to install keyboards if none are installed yet
- Within the keyboard settings, could display: “Here’s where you can change how each Scribe keyboard functions”

### Contribution

- App hints planned as part of GSoC work by @SaurabhJamadagni  
- Designs for the app hints will be made by @andrewtavis

**Comment by andrewtavis** [comment]
Designs are all done at this point 😊 I didn't put it in the prototype as I felt like it's not necessary to see exactly how it would work, but here's an image for documentation as well as the component :)

![App Hint Tooltip](https://github.com/scribe-org/Scribe-iOS/assets/24387426/cb8af737-f132-49b6-a861-fb8d85a399d4)
![About Scribe - Light](https://github.com/scribe-org/Scribe-iOS/assets/24387426/be7e1971-c25e-4b25-bc0f-a883f8b554bf)

**Comment by fabulouiOS-monk** [comment]
Hi @andrewtavis, What's the status of this? Has anyone picked it up yet? 
If not I can start with this 😄 !

**Comment by andrewtavis** [comment]
Hey @fabulouiOS-monk 👋 Sounds good :) This would be great to get some help with! As a first step, would you document some of the steps you'll take to work on this? Then once we agree on things you can get started on the coding 😊

**Comment by fabulouiOS-monk** [comment]
Hey @andrewtavis, Here's the Action plan:

1. Implement the UI for the tip card (let us call it a tip card). Since you already have the design prepared I will proceed with that, I just will need **icon**, and **Color coding**.

2. Capturing device-related data (I know we don't do it right now) but we will need it to check whether the user has newly downloaded the app or if he/she is new to the Scribe app.

3. Discuss which screens this tip card is really useful, and If we have old users where to place that light bulb icon, So that users can access the tip card anytime.

4. For new users the duration till the Tip card will be shown.

**Comment by andrewtavis** [comment]
Hey @fabulouiOS-monk 👋 Some feedback on this:

1. For the lightbulb icon use `lightbulb.max` from SF Symbols, and the [designs here](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=1258%3A3595&t=2D19g7tTwKN8KU3x-1) have the colors if you need that can be seen by selecting the app hint tooltips. All of the colors are already defined in the apps assets.

2.  Let's avoid doing this. I think the way we planned it was to just have a default value, which thinking about it we'd need a default value for each page/hint. Once the tooltip is shown once, it goes to false, and then we'll also include a menu option in about to reset the app hints and then they'll all be true again.

3. Now I see what you mean by app data. For now let's just have it be set to true from the start, and hopefully that means that old users will see it and be annoyed by it once, but then people won't need to worry about it further. If it's being reset it each a new version is installed, then we can react to that with a new issue :)

4. For the duration, let's keep it easy on ourselves and have the tooltip disappear on click of ok, or if the user changes to a new screen. Maybe we can also get rid of it on any click of the screen, but we can discuss this with the larger community 😊

Let me know what you think on the above! Happy for further feedback on this! Really exciting to get this going 🚀

**Comment by fabulouiOS-monk** [comment]
Great let me have some work on it and let you know @andrewtavis!!

P.S: I might take some time on this, if it doesn't impact the release 😬

**Comment by andrewtavis** [comment]
Totally fine, @fabulouiOS-monk! This isn't necessary for the next release, so take your time and let us know how we can help!

**Comment by fabulouiOS-monk** [comment]
Hey @andrewtavis, Just for the updates!
1. I have been working on the view part, Initially I started with SwiftUI and integrated it with UIKit (but failed).
2. I have implemented the same in UIKit and am working on showing it on other views.

**Comment by andrewtavis** [comment]
Thanks for the update and the hard work here, @fabulouiOS-monk! Appreciate the efforts, and no stress if it's taking some time 😊

**Comment by andrewtavis** [comment]
Closed by #459 🙌 Awesome that this was figured out so quickly and at such a perfect time, @fabulouiOS-monk! Thanks again :)
