### ISSUE TITLE
Swipe between parent views within menu

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#337]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would allow a user to swipe between parent views in the Scribe menu. The way it would work is that the user would be able to swipe back when in a child screen of the menu like for keyboard settings, but if they're on the main `Installation`, `Settings` or `About` screens then swiping would allow them to switch to one of the other tabs.

### Contribution

Happy to help with this if it's needed! This issue is assigned to @SaurabhJamadagni as a part of GSoC 2023, but if someone else wants to work on it then he could also review the contribution :)

**Comment by nyfz18** [comment]
Hi!

**Comment by andrewtavis** [comment]
Hi @nyfz18 👋 I screwed up and said #337 when I should have said the other one we talked about - #33 :) This one is the one that would require you to have a simulator 🙃 We can check out #33 for now and then figure out the next thing to do after that!

**Comment by nyfz18** [comment]
sure! I'll take a look at it

**Comment by SaurabhJamadagni** [comment]
Hey @andrewtavis, for this issue I was wondering if we can go with a package that will allow for this functionality. Here's the [link](https://github.com/marcosgriselli/SwipeableTabBarController/tree/master) to it. The animation based approach I talked about last week just doesn't feel natural. Any other approach I have seen will need a lot of reengineering. This can be a difficult change since a Tab Bar is close to the root view controller on top of which we have the rest of the screens in the Storyboard file. Can we give this package a try? Maybe it could be useful.

**Comment by andrewtavis** [comment]
Looks good to me, @SaurabhJamadagni! Feel free to implement using `SwipeableTabBarController` :)

**Comment by SaurabhJamadagni** [comment]
Hey @andrewtavis just to confirm, what have you used to install the swiftyJSON and GRDB packages? Was it swift package manager?

**Comment by andrewtavis** [comment]
Hey @SaurabhJamadagni 👋 Yes, I used Swift Package Manager :)

**Comment by andrewtavis** [comment]
@SaurabhJamadagni, the most recent commit expands the Powered By section at the end of the readme to include [this section](https://github.com/scribe-org/Scribe-iOS#code-and-dependencies). Feel free to send a commit to edit it if you think it's not enough! Very happy to give a bit more credit to our dependencies 😊 Great idea 👍👍 

With that this is closed up! 📱 As I said in review, happy to test on a physical device before 3.0's release. Would be good to get in the mode of doing that regardless :)

**Comment by SaurabhJamadagni** [comment]
> happy to test on a physical device before 3.0's release.

Yes let's try to @andrewtavis. Thanks for adding the new section to the readme. Looks great :)
