### ISSUE TITLE
Menu item to disable accent characters on keyboard letter keys

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#339]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would provide an option in the `Settings/LANGUAGE/Layout` menu option that allows for the user to disable the accent characters for a given keyboard. Examples would include:

- German would disable `ä`, `ö` and `ü`
- Spanish would disable `ñ`
- Swedish would disable `ä`, `ö` and `å`
- ...

The default of this option would be that it's selected. Deselecting this option would then add these to the alternate characters for the given keyboard.

### Contribution

I'd be happy to work on this at some point in the future or support someone who has interest 😊

**Comment by mariaykim** [comment]
Hi Andrew, I can work on this issue!

**Comment by andrewtavis** [comment]
Hey @mariaykim! Thanks for your interest in Scribe and helping out 😊 Will assign now, and pinging @SaurabhJamadagni who'd also be able to help if you need any assistance. Please let us know if there's anything we can to to support!

**Comment by andrewtavis** [comment]
Closed by #368 and minor changes in f56b4df :) There are some edits to the layouts that need to happen to make sure that everything's looking ok, but those can be done in #362.

Thanks again for the support here, @mariaykim! By all means let me know if there's another issue you'd like to work on 😊
