### ISSUE TITLE
Space bar read keyboard name when switched to

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#34]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue focuses on a minor UI element missing from Scribe keyboards - that the space bar doesn't change to the name of the keyboard when it is switched to by pressing the `🌐` rather than long holding it to select from the menu. Having this feature would help users better recognize the keyboard they're using, especially for users who use more than one Scribe Keyboard. Code for this would be written in [KeyboardViewController.swift](https://github.com/scribe-org/Scribe-iOS/blob/main/Keyboards/KeyboardsBase/KeyboardViewController.swift).

**Comment by pankova** [comment]
Hello! It seems to be not reproduced for the current version from the App Store. iPhone 12 mini, iOS 15.5
https://user-images.githubusercontent.com/7028613/181825656-f7a70c97-2007-46c1-a35b-f97e6a272075.MP4

**Comment by andrewtavis** [comment]
Hi @pankova, thanks for reaching out, and also for the effort in creating the video! 😊 What the spacebar is changing to there is the word for "space" for the given language, whereas when you switch to a system keyboard you see "English (US)" for a second or so before it switches to "space" (as shown at the end of the video). Generally the idea would be that before the German keyboard switches to "Leerzeichen", similarly it would say "Deutsch (Scribe)" for a moment.

It'd be great to get your feedback on whether you'd think this is something that should be included! Generally I opened this as my thought is that Scribe should do things that a system keyboard does, and sometimes I do get confused for a sec when I'm on Spanish Scribe when I really want German. 

If this should be worked on, the feature is likely the creation of a function that would be triggered by [loadInterface](https://github.com/scribe-org/Scribe-iOS/blob/6b9889d6a1d658a7f83b7fdd3062d203da1ba356/Keyboards/KeyboardsBase/KeyboardViewController.swift#L41) within `KeyboardViewController.swift`. The user would change the keyboard, and `asyncAfter` could be used to change the text on the space bar to "space" in the given language after a bit of time.

Thanks again for reaching out! 🙏

**Comment by helloITdepartment** [comment]
I'd like to work on this! I think I've nearly got it solved

**Comment by andrewtavis** [comment]
Glad to hear, @helloITdepartment, and thanks for reaching out so I can assign you! 😊

**Comment by andrewtavis** [comment]
Just checking in with you, @helloITdepartment :) :) Let me know if you have any questions on the code base that I can help with!

**Comment by helloITdepartment** [comment]
Actually I do, is there somewhere we can chat for a minute so I can explain the issue I've run into?

**Comment by andrewtavis** [comment]
Sure, we can do a mini call to discuss this! Do you want to send along an email to the one I have in my profile? We can then figure out a time for a call. Also let me know what your preferred video service is (Zoom, Google Meet or Jitsi are the ones I use most, but open to others).

**Comment by helloITdepartment** [comment]
Wonderful! I'll do that now, thanks

**Comment by andrewtavis** [comment]
Btw, feel free to add a little blurb about this into the [CHANGELOG.md](https://github.com/scribe-org/Scribe-iOS/blob/main/CHANGELOG.md) for v2.1.0 🚀 Thanks for all the hard work! Really glad we figured it out, and looking forward to seeing it animated!

**Comment by andrewtavis** [comment]
Thanks for your work on this, @helloITdepartment! As mentioned, might be good to check the GitHub docs on [pull requests](https://docs.github.com/en/get-started/quickstart/github-flow). Really was fine though! Really excited to have this in there now! 😊
