### ISSUE TITLE
Tiếng Việt 

### ISSUE THREAD

**Issue by LeQuangHuy-1809** [scribe-org/Scribe-iOS#341]
### Terms

- [X] I have searched [open localization issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+is%3Aopen+label%3Alocalization)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

https://github.com/google/styleguide/tree/775126844062ab645cdf0acf907a2a03be939366

**Comment by andrewtavis** [comment]
Hey @LeQuangHuy-1809 👋 Thanks for opening the issue and for your interest in Scribe :) I'm a bit confused with what you'd like to do with this issue. You've opened a `Localization` issue and the title is Vietnamese in Vietnamese. Would you have interest in helping with Vietnamese localizations?

**Comment by andrewtavis** [comment]
Or were you by chance referring to the [Google Swift Styleguide](https://google.github.io/swift/) as this project is written in Swift?

**Comment by andrewtavis** [comment]
> > Hey @LeQuangHuy-1809 👋 Thanks for opening the issue and for your interest in Scribe :) I'm a bit confused with what you'd like to do with this issue. You've opened a Localization issue and the title is Vietnamese in Vietnamese. Would you have interest in helping with Vietnamese localizations?

> I am interested in helping localize Vietnamese

Hey again @LeQuangHuy-1809 :) Do you have interest in localizing parts of the Scribe documentation to Vietnamese, or is this related to Google? If you'd like to do a version of [our readme](https://github.com/scribe-org/Scribe-iOS/blob/main/README.md) or app texts in Vietnamese, then this would be welcome 😊 I won't be able to help you if you're wanting to help localize Google documentation.

**Comment by andrewtavis** [comment]
Closing this issue as it seems to be unrelated. Let me know if you have any further questions, @LeQuangHuy-1809 :)
