### ISSUE TITLE
no:label

### ISSUE THREAD

**Issue by LeQuangHuy-1809** [scribe-org/Scribe-iOS#342]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

Tôi không thể mở các nội dung trang web trên trình duyệt Safari vì webkit đã gặp lỗi nội bộ và thêm một vấn đề nữa là các trang web tài liệu tiếng anh khi mở trên Chrome không hổ trợ tiếng Việt và không thể dịch tài liệu tiếng anh bằng google dịch…hãy giúp tôi mở các vấn đề trên như một đặc ân…

### Device type

iPhone

### Versions

16.3.1(20D67)

**Comment by andrewtavis** [comment]
Hey @LeQuangHuy-1809 👋 I'm a bit confused by this issue as you're referencing version `16.3.1(20D67)`, but we're currently only at version `2.3.0`. I translated what you wrote and also don't really understand how it relates to this software. Scribe makes iOS keyboards, and how this relates to you not being able to open content on Safari or Chrome not being able to translate the pages doesn't relate to our team.

I'm going to close this issue as it seems unrelated, but will write to you in #341 :)
