### ISSUE TITLE
New menu layout improvements for iPads

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#351]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As of now there are some issues with how the new menu is being presented on iPads. Spacing is a bit off in some places, and text sizes should likely be larger to reflect the size of the screen and fill it up more proportionally.

### Contribution

I'll work on this before the next release as a way to continue to get more experience with the code that @SaurabhJamadagni has been writing for GSoC :)

**Comment by andrewtavis** [comment]
@SaurabhJamadagni, let me know if you have some suggestions on this, but as I said I think it'd be good if I do this :)

**Comment by SaurabhJamadagni** [comment]
Yup totally @andrewtavis. Let me know if any of my code needs revision too :)

**Comment by andrewtavis** [comment]
CC @henrikth93, there are a couple things here that need to get fixed for this issue:

1. For menu screens like the installation directions, privacy policy and others, we'll potentially need to have new text areas that we then have larger margins (x and y-axis) for
2. For the menu options, we'll similarly need to increase the margins
3. We also need to increase the text sizes for iPads and make the icons a bit bigger

As discussed in the call, @henrikth93, can you work on making the texts and icons a bit bigger for the iPad menus, and I'll come through and fix the margins?

**Comment by andrewtavis** [comment]
606a67a closes this 🥳🥳🥳🥳🥳 @henrikth93, I'd definitely pull in the most recent changes before you get to work on #445 :) There likely will be some minor edits before the release, but this is most of the work, and it's time to start finalizing things!

**Comment by henrikth93** [comment]
> [606a67a](https://github.com/scribe-org/Scribe-iOS/commit/606a67a0fa3f665349f2402ef265e743c015b588) closes this 🥳🥳🥳🥳🥳 @henrikth93, I'd definitely pull in the most recent changes before you get to work on #445 :) There likely will be some minor edits before the release, but this is most of the work, and it's time to start finalizing things!

Great!! Will do!
