### ISSUE TITLE
Information Tooltip texts for menu options

### ISSUE THREAD

**Issue by SaurabhJamadagni** [scribe-org/Scribe-iOS#354]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue will help in deciding the text that is shown when the information tooltip icons are pressed for the menu options.

![Screenshot 2023-08-14 at 12 11 36 PM](https://github.com/scribe-org/Scribe-iOS/assets/68957712/6323c180-7aac-4946-8834-bb151fece443)

Currently, the [design file](https://www.figma.com/file/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?type=design&node-id=405-464&mode=design&t=uk8X9eZGWPrcwkrl-0) doesn't have what text is displayed when a certain tooltip icon is pressed. We can discuss concise and clear texts that convey the use of the feature. Also, keeping localization in mind if we can set up the file structure such that it helps down the line then it's even better. 

If needed the issue could be split into parts -- one to discuss what the texts should be, second to understand how it would efficiently plug into the menu.

### Contribution

I would be happy to help anyone interested in working on this issue. If not I'll take it up myself. @andrewtavis and @wkyoshida  we could discuss the texts too if okay.

**Comment by SaurabhJamadagni** [comment]
@andrewtavis could this be considered a `good first issue`?

**Comment by andrewtavis** [comment]
I’d say there’s enough domain knowledge required that a new contributor wouldn’t be able to do versions without a lot of help 🤔 Let’s just plan on defining these in the daily today, @SaurabhJamadagni :)

**Comment by andrewtavis** [comment]
I'd say something along the lines of "Increase color contrast for a clearer and more comfortable viewing experience." So about the length of the second one :)

Thanks for checking, @SaurabhJamadagni!

**Comment by SaurabhJamadagni** [comment]
1. High color contrast: "Increase color contrast for a clearer and more comfortable viewing experience."
2. Default keyboard: "Select a keyboard layout that suits your typing preference and language needs."
3. Default currency symbol: "Choose your preferred currency symbol."
4. Comma and period on ABC: "Include comma and period keys on the main keyboard for convenient typing."
5. Include accent keys on ABC: "Add accent keys to the primary keyboard layout."
6. Double space periods: "Toggle to automatically insert a period with double space."
7. Autosuggest emojis: "Turn on emoji suggestions for more expressive typing."
8. Delete punctuation spacing: "Remove spaces before punctuation marks."
9. Hold for alternate characters: "Activate alternate characters by holding keys."
10. Annotate suggest/complete: "Provide suggestions based on annotations for grammatical correction."
11. Hold delete is word by word: "Delete text word by word with a press and hold."
12. Default emoji skin tone: "Set a default skin tone for emojis."

Thoughts @andrewtavis and @wkyoshida?

**Comment by andrewtavis** [comment]
Thanks for these, @SaurabhJamadagni! My comments:

- "Choose your preferred currency symbol."
  - “Choose your preferred currency symbol that will appear on the numbers view.”
  - So they understand the purpose :)
  - We should make sure to disable this for iPads 🤔
- "Add accent keys to the primary keyboard layout."
  - “Include accented letter keys on the primary keyboard layout.”
- "Toggle to automatically insert a period with double space."
  - “Automatically insert a period when the space key is pressed twice.”
- "Provide suggestions based on annotations for grammatical correction."
  - “Underline suggestions and completions to show their genders as you type.”
- "Delete text word by word with a press and hold."
  - “Delete text word by word when the delete key is pressed and held.”

Those are my initial thoughts for now. We can finalize those and I’ll update the Figma!

**Comment by wkyoshida** [comment]
For the `High color contrast` one, I was thinking that primarily we'd want to state the improved accessibility, no? 
So I was thinking something along the lines of: 
> "Increase color contrast for improved accessibility and a clearer viewing experience."

Or was I thinking of something else?

**Comment by andrewtavis** [comment]
That sounds great to me, @wkyoshida :)

**Comment by SaurabhJamadagni** [comment]
> We should make sure to disable this for iPads 🤔

Why so @andrewtavis? iPad layouts don't get a currency symbol?

The new list for the tooltips texts would be:

1. High color contrast: "Increase color contrast for improved accessibility and a clearer viewing experience."
2. Default keyboard: "Select a keyboard layout that suits your typing preference and language needs."
3. Default currency symbol: “Choose your preferred currency symbol that will appear on the numbers view.”
4. Comma and period on ABC: "Include comma and period keys on the main keyboard for convenient typing."
5. Include accent keys on ABC: “Include accented letter keys on the primary keyboard layout.”
6. Double space periods: “Automatically insert a period when the space key is pressed twice.”
7. Autosuggest emojis: "Turn on emoji suggestions for more expressive typing."
8. Delete punctuation spacing: "Remove spaces before punctuation marks."
9. Hold for alternate characters: "Activate alternate characters by holding keys."
10. Annotate suggest/complete: “Underline suggestions and completions to show their genders as you type.”
11. Hold delete is word by word: “Delete text word by word when the delete key is pressed and held.”
12. Default emoji skin tone: "Set a default skin tone for emojis."

**Comment by andrewtavis** [comment]
> iPad layouts don't get a currency symbol?

They do of course, but they’re all on the same page, @SaurabhJamadagni :) Basically this option for iPhones says “You don’t need to first press `123` and then `#+=` to get to your preferred currency symbol. It’s just on `123`”. For iPads all the currency symbols are on the same page, and I don’t think swapping key positions is worthwhile. 

Final thoughts on this to make some of the shorter ones more descriptive:
- Autosuggest emojis: “Turn on emoji suggestions and completions for more expressive typing."
- Delete punctuation spacing: "Remove excess spaces before punctuation marks."
- Hold for alternate characters: "Select alternate characters by holding keys and dragging to the desired character.”
- Default emoji skin tone: "Set a default skin tone for emoji autosuggestions and completions.” 

I’ll update the Figma if the above changes sound good to you two 😊

**Comment by SaurabhJamadagni** [comment]
> For iPads all the currency symbols are on the same page, and I don’t think swapping key positions is worthwhile.

Ahhh got it! Thanks :)

> I’ll update the Figma if the above changes sound good to you two 😊

The changes look good to me. We can use these definitely 👍

**Comment by andrewtavis** [comment]
Updated the designs in Figma with the [chosen texts](https://www.figma.com/file/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?type=design&node-id=1417%3A815&mode=design&t=UpUKn3557bV1B0tR-1) :) Thanks all for the input! Closing now 😊
