### ISSUE TITLE
Add issues to Scribe Board via templates

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#355]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As discussed in the Scribe weekly, it would be great if issues would be automatically added to the Scribe board when they're made. @SaurabhJamadagni offered to work on this :)

### Contribution

I'll review once this goes through!

**Comment by andrewtavis** [comment]
@SaurabhJamadagni, looks like the line needs to be 'projects: ["scribe-org/1"]', and we can do this as the last meta tag above `body` and below `labels` in each of the [issue templates](https://github.com/scribe-org/Scribe-iOS/tree/main/.github/ISSUE_TEMPLATE) 😊

**Comment by andrewtavis** [comment]
Annnddddd, @SaurabhJamadagni, I think this is a great opportunity to do a quick PR to Scribe-Data with that there new fork of yours 😉😉😉😉

**Comment by SaurabhJamadagni** [comment]
> Annnddddd, @SaurabhJamadagni, I think this is a great opportunity to do a quick PR to Scribe-Data with that there new fork of yours

Oooo I thought it was only missing for the Scribe-iOS repo. Sending this one right away in that case 🚀

**Comment by andrewtavis** [comment]
Closed via #357 and the corresponding Scribe-Data issue :) Just checked and it is working 🚀
