### ISSUE TITLE
Add continuous tenses as conjugation options for the English keyboard

### ISSUE THREAD

**Issue by wkyoshida** [scribe-org/Scribe-iOS#358]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is for the needed changes to include the continuous tenses in the conjugation view for the English keyboard. Functionally, the conjugation view may not need large changes; this issue is more of a placeholder/reminder for the work in case the initial English keyboard is ready before the adjacent Scribe-Data work (https://github.com/scribe-org/Scribe-Data/issues/45) is completed.

**Comment by wkyoshida** [comment]
Potentially related to the past completed issue: https://github.com/scribe-org/Scribe-iOS/issues/30

**Comment by andrewtavis** [comment]
Assigning this to you and closing it directly @Jag-Marcel as this issue's all done via the work in #484 :)
