### ISSUE TITLE
Can not use Scribe keyboard when emulating iPhone

### ISSUE THREAD

**Issue by henrikth93** [scribe-org/Scribe-iOS#359]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

When emulating an iPhone 14 Pro with iOS 16.4 in Xcode 14.3.1 I am not able to switch between the regular keyboard and the Scribe keyboard. Clicking in the text input field with my mouse does not work.

https://github.com/scribe-org/Scribe-iOS/assets/106680402/8b70bdb8-3fb7-4bfb-b76f-70868e6be708

### Device type

iPhone

### Versions

MacOS 13.4.1  and Scribe 2.3.0

**Comment by henrikth93** [comment]
Sorry, I realize now that you can not use your physical keyboard as input.

**Comment by andrewtavis** [comment]
No nee
