### ISSUE TITLE
Allow for swiping between conjugation and declension views

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#361]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would add swipe functionality to the conjugation and declension views for Scribe keyboards, with the former being displayed when a user presses the conjugate key and enters a verb and the latter being displayed when a user clicks on a preposition's case to see the possible pronouns that could be used. As of now we have a left and right button to the side of the view that are used to switch views, with the goal being that the user would also be able to swipe. The left and right buttons would not be removed to make sure that the user can still understand the ability to switch views :)

The code for this would generally follow the patterns used in #337 that added swipe support to the new menu 🚀

### Contribution

Happy to work on this with someone or get to it myself! 😊

**Comment by andrewtavis** [comment]
CC @SaurabhJamadagni on this :)

**Comment by andrewtavis** [comment]
CC @Taufi, can you write in here so I can assign you as well :)

**Comment by andrewtavis** [comment]
Exactly, @Taufi :) As soon as you write in I can assign you. Helps us keep an overview of who's on what 😊

Let me know if there's anything I can do to help!

**Comment by andrewtavis** [comment]
Many thanks for checking in, @Taufi!

**Comment by henrikth93** [comment]
> Thanks for the research so far, both of you! 🙌 Both are really good points!
> 
> Originally I was typing out that `ViewDidLoad` makes sense to keep the keyboard load times down, but that's also with the assumption that a person will use conjugate at least once when using Scribe. Maybe for Scribe-Desktop where someone's writing an email or a paper, but I'd say that in a typical phone interaction a person is using verbs that they generally know how to conjugate, and just need help in special circumstances. In this case I'd go with `setConjugationBtns`, with this also having the architectural bonus that its usage is closer to its function :)
> 
> How does this sound?

Makes sense!

**Comment by andrewtavis** [comment]
Closed by #412 🥳 Thanks so much, @Taufi and @henrikth93 for the great collaboration on this!
