### ISSUE TITLE
Size keys on expanded iPad keyboards

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#362]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is the second half of #352 where the expanded keyboard layouts for iPads are assigned and are able to be switched to with the `123?!` key. Within this issue we'll go through and create conditionals to style the keyboards based on the new keys such as the tab key and others :)

Note that we'll be going for a generic layout for all keyboards. In the system keyboard sometimes there are differences like the return key being L shaped and other elements, but this will not be done at this time. Goal for this is to include this in the 3.0.0 release 🚀

### Contribution

Happy to support someone with interest in working on this!

**Comment by andrewtavis** [comment]
CC @henrikth93 who's working on #352 :)

**Comment by andrewtavis** [comment]
Thank you, @henrikth93! Assigning now 🚀🚀

**Comment by andrewtavis** [comment]
Hey there @henrikth93 👋 Here are the layouts that we're looking for in one place that I'm bringing over from #33:

## Danish (#133)

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 21 57 51](https://github.com/scribe-org/Scribe-iOS/assets/24387426/fe160c02-0a4c-4a4b-ac56-dad97894b8cb)

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 15 28](https://github.com/scribe-org/Scribe-iOS/assets/24387426/c6c26bcc-cd12-49ee-a9f6-bbefb4e24f7f)

## English (#7)

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 00 15](https://github.com/scribe-org/Scribe-iOS/assets/24387426/6dfe5775-98af-4339-be3d-6fc62b0b278e)

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 16 16](https://github.com/scribe-org/Scribe-iOS/assets/24387426/d4e7ac2d-b440-45f6-9541-2ecaa7d0f2af)

## French

### Canada

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 01 04](https://github.com/scribe-org/Scribe-iOS/assets/24387426/4aa79db1-1ab1-4118-b403-17291b9b71e4)

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 16 50](https://github.com/scribe-org/Scribe-iOS/assets/24387426/a81f8dfa-0821-486c-bc02-2be079d0aac6)

### France

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 01 31](https://github.com/scribe-org/Scribe-iOS/assets/24387426/8fb7cfb3-c67a-4550-a454-256d58c19659)

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 17 20](https://github.com/scribe-org/Scribe-iOS/assets/24387426/673a3840-136f-49b2-8d30-c5bb65c0ca64)

## German

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 21 51 44](https://github.com/scribe-org/Scribe-iOS/assets/24387426/a5de06e8-7326-47a6-b42f-c4ec98fe128c)

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 17 52](https://github.com/scribe-org/Scribe-iOS/assets/24387426/ac1c7b94-721a-44f9-b99c-fdff80619fda)

## Hebrew (#134)

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 02 22](https://github.com/scribe-org/Scribe-iOS/assets/24387426/30e2b2d8-68b3-4d5b-81b5-7a86c40e602f)

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 18 24](https://github.com/scribe-org/Scribe-iOS/assets/24387426/a19388e1-15ed-453e-8fe5-0b0f662efd73)

## Italian

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 02 56](https://github.com/scribe-org/Scribe-iOS/assets/24387426/2a107801-3884-4a22-9590-d3a3022f0e54)

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 19 19](https://github.com/scribe-org/Scribe-iOS/assets/24387426/1d7b47bb-9f48-4e68-b0d4-dcd7dfcd1427)

## Norwegian (Bokmål, #135)

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 03 25](https://github.com/scribe-org/Scribe-iOS/assets/24387426/82fa8138-5ab1-4c18-9661-62c9779d820f)

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 19 50](https://github.com/scribe-org/Scribe-iOS/assets/24387426/38920456-2351-432c-8562-34fab72787a5)

## Portuguese

### Brazil

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 21 04](https://github.com/scribe-org/Scribe-iOS/assets/24387426/c4a43d96-40f7-44fd-a14d-c2ebb8a191aa)

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 20 20](https://github.com/scribe-org/Scribe-iOS/assets/24387426/a18e482f-0a25-4374-a155-18bb7bab9b86)

### Portugal

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 04 56](https://github.com/scribe-org/Scribe-iOS/assets/24387426/9e7caa72-31a3-4d6a-a4e3-cca350760875)

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 21 37](https://github.com/scribe-org/Scribe-iOS/assets/24387426/12ab16b8-cd22-4763-9dff-7c7d11d782a3)

## Russian

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 05 24](https://github.com/scribe-org/Scribe-iOS/assets/24387426/8e285f76-4e7f-4337-9977-b94eb8632212)

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 22 03](https://github.com/scribe-org/Scribe-iOS/assets/24387426/3cebc16d-eeab-4e72-bffd-5c08c13b6589)

## Spanish

### Mexico

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 23 11](https://github.com/scribe-org/Scribe-iOS/assets/24387426/20515ec7-aed4-43eb-8f0e-d07d6bce2f41)

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 22 32](https://github.com/scribe-org/Scribe-iOS/assets/24387426/19c9deb9-24ae-4702-90e0-20db7eec7346)

### Spain

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 07 07](https://github.com/scribe-org/Scribe-iOS/assets/24387426/df941665-7e7b-4ab8-9983-06357208adeb)

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 23 39](https://github.com/scribe-org/Scribe-iOS/assets/24387426/b8200f1b-95bc-44ea-acb5-40c318b19667)

## Swedish

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 07 40](https://github.com/scribe-org/Scribe-iOS/assets/24387426/f0208bc8-db8a-4785-a261-08a10be65a34)

![Simulator Screenshot - iPad Pro (12 9-inch) (4th generation) - 2023-07-12 at 22 24 06](https://github.com/scribe-org/Scribe-iOS/assets/24387426/942c85f4-e41b-473f-8f21-11e3e151aff1)

**Comment by andrewtavis** [comment]
Do you want to work on this issue keyboard by keyboard? I don't think that we need separate issues for each one, but we can do separate pull requests 😊

**Comment by henrikth93** [comment]
> Do you want to work on this issue keyboard by keyboard? I don't think that we need separate issues for each one, but we can do separate pull requests 😊

Separate PRs sounds good!

**Comment by andrewtavis** [comment]
In addition to this, we need to make sure that the number keys row is has more height :)

**Comment by andrewtavis** [comment]
List of keyboards:
- [ ] English
- [ ] French
- [ ] German
- [ ] Italian
- [ ] Portuguese
- [ ] Russian
- [ ] Spanish
- [x] Swedish

Let's make sure to add in a right shift key for the symbol keys for each keyboard so that that row has appropriate spacing. Another minor change is that the tab key should be a bit more narrow so that the key spacing on that row is consistent with the rest of the keyboard :)

**Comment by henrikth93** [comment]
> List of keyboards:
> 
> * [ ]  English
> * [ ]  French
> * [ ]  German
> * [ ]  Italian
> * [ ]  Portuguese
> * [ ]  Russian
> * [ ]  Spanish
> * [x]  Swedish
> 
> Let's make sure to add in a right shift key for the symbol keys for each keyboard so that that row has appropriate spacing. Another minor change is that the tab key should be a bit more narrow so that the key spacing on that row is consistent with the rest of the keyboard :)

To me, the German version also looks good.

**Comment by andrewtavis** [comment]
I'll close out German after we have the next PR that also adds in the rest of the minor changes below:

> Let's make sure to add in a right shift key for the symbol keys for each keyboard so that that row has appropriate spacing. Another minor change is that the tab key should be a bit more narrow so that the key spacing on that row is consistent with the rest of the keyboard :)

Really looking forward to getting this all done, @henrikth93 😊 Let me know if you need any support!

**Comment by andrewtavis** [comment]
Closed via #362! 🥳 So great that we have this done now! 🚀 Thanks @henrikth93
