### ISSUE TITLE
Multiple Delete Keys on IPad

### ISSUE THREAD

**Issue by stilianb** [scribe-org/Scribe-iOS#366]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

In the current main branch, all keyboards (not including Hebrew, Danish, and Norwegian) have multiple delete keys within their respective interfaces on IPad.

Here's an example of the issue:
<img width="492" alt="deletekeybug" src="https://github.com/scribe-org/Scribe-iOS/assets/49213751/c0e8e45e-fdaa-4b30-b618-652454c0c8d0">

`letterKeys[0].append("delete")` within each languages interface seems to be appending another delete key for IPad layouts.

The earliest instance I could find of this change being made was in #33.

Removing this line in each interface seems to solve the issue.

### Device type

iPad

### Versions

iOS 17, Scribe 2.3.0

**Comment by andrewtavis** [comment]
Hey @stilianb! Thanks so much for pointing this out 😊 Would you have interest in working on this?

**Comment by stilianb** [comment]
Yes! I'd be happy to.

**Comment by andrewtavis** [comment]
Fantastic, @stilianb! Assigning you now :)

**Comment by andrewtavis** [comment]
Closed by #367! Thanks for opening the issue and sending along a fix, @stilianb! As I said in the PR, I'll finalize these conditions soon and then put this addition of the delete key back in a context that it's needed.
