### ISSUE TITLE
Improve contributing guidelines for all scribe-org repos

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#369]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

A [recent PR for another project of mine](https://github.com/activist-org/activist/pull/434) really improved the contributing guidelines and readme instructions for [activist-org/activist](https://github.com/activist-org/activist). The contribution guidelines for Scribe were the basis of the ones for activist, so it'd be great if those changes could be reflected in all scribe-org repos. A contributor could do this for all of them if they wanted, or we could split it up 😊 Generally what we want is the [exact same changes](https://github.com/activist-org/activist/pull/434/files) that happened in that PR :)

### Contribution

Happy to support someone in this! This is a great `good first issue` :) :)

**Comment by kuddlefishbwaa** [comment]
Hello! I would love to work on this!

**Comment by andrewtavis** [comment]
Thanks for the interest in helping, @kuddlefishbwaa! Will assign you now, and please let us know if you have any questions! Let's start with Scribe-iOS and we can check the changes to the first repo, and then you'd be welcome to do the same for the others after that 😊

**Comment by andrewtavis** [comment]
1e5c53d sends along the final changes for this, @kuddlefishbwaa 😊 Thanks again for the support here! I also just updated the other repos in the organization, so I think we're good to go! 🚀
