### ISSUE TITLE
Add functionality to new keyboard keys on expanded layouts

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#371]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Now that we have new expanded keyboard layouts thanks to #352, one thing that's needed is to add some styling and functionality to a few new buttons that we have. These include a tab key and a caps lock key.

### Contribution

This issue is of high priority as it's needed so that we can release the new keyboard layouts for iPads. With that being said, the changes are not too difficult as it's mostly going in and making changes within the following function https://github.com/scribe-org/Scribe-iOS/blob/2b544e06c4e8377809069308c673a3623eb3ba62/Keyboards/KeyboardsBase/KeyboardViewController.swift#L2073

We'd need lines for `case "indent"` and `case "uppercase"` specifically :)

**Comment by andrewtavis** [comment]
Hey @damien-rivet! Thanks for your interest in helping out :) It is still available! I'll assign you now, and please let me know if I can do anything to support 😊

**Comment by damien-rivet** [comment]
@andrewtavis I've made good progress on the implementation.

As always, this issue is not as simple as it looks, here's a summary of my current status on it.

## Indent key

Nothing fancy here, I added the '\t' character append and I've added the "indent" icon (with support for right-to-left).

## Caps lock key

Slightly harder than the indent key as there are behaviour changes locked in with the shift button but in the end it's working like a normal keyboard.

## Other

I did some minor refactoring for the keys style update to better separate sizing and styling. I've also started the work to extract the constants for special keys into a dedicated file instead of littering the code with hardcoded string.

---

I still have some intensive testing to do but once it's cleared out, I'll create a PR with before / after screenshots and recordings to demonstrate the changes.

**Comment by andrewtavis** [comment]
Thanks for this, @damien-rivet! Really happy to get the support here :) I'll share this with the dev sync we're having in a few minutes, or you'd of course be welcome to join that if you're free 😊 Details for that are on our [General channel on Matrix](https://matrix.to/#/!yQJjLmluvlkWttNhKo:matrix.org?via=matrix.org).

**Comment by andrewtavis** [comment]
@henrikth93, sounds like we should hold off a moment on #362 for these changes, but let's check in after @damien-rivet sends along the PR. I'll merge that very quickly and then we can start right away with the formatting for the various layouts. We can of course discuss in the sync as well! 🥳

**Comment by damien-rivet** [comment]
@andrewtavis not necessarily, if the changes aren't too drastic I should be able to resolve the potential conflicts when rebasing on `main`.

**Comment by damien-rivet** [comment]
@andrewtavis I've just opened the PR, let me kow if I need to do some extra stuff to make it compliant.

**Comment by andrewtavis** [comment]
Sorry for the wait on the PR review, @damien-rivet! As stated I had designs added on to normal work plus open-source, so it's been a week 😅 Very much is compliant, and we just need to figure out the two introduced bugs :)

As stated when I was doing the review, you've gone through a wide range of the code base, and if seen any places where there could be some improvements to quality then please feel free to open an issue!

**Comment by andrewtavis** [comment]
Closed via #373 and minor formatting in 859bf2f 🥳 Really thanks so much, @damien-rivet! Would be wonderful to work with you again 😊 We have a [Matrix community](https://matrix.to/#/#scribe_community:matrix.org) that the team uses to discuss ideas/questions, and we also do a call every two weeks for an hour to discuss bi-weekly plans :) :) The next dev sync will be this Saturday at 14:00 UTC, with the details for that being shared in the [General channel on Matrix](https://matrix.to/#/!yQJjLmluvlkWttNhKo:matrix.org?via=matrix.org).

Also happy to also communicate with you on GitHub. As stated in the PR review, you could provide some invaluable support as far as deriving issues to be done for refactoring, bug fixes and the like :)

Thanks and all the best!
