### ISSUE TITLE
Remove `Disable accent characters` for menus that it's not needed on

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#372]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

 In #339 we added an option to disable the accent characters of certain keyboards. Something that we need to do now is have this option show up in the settings only for those languages that it makes a change for: specifically German, Swedish and Spanish. 

Would be great if someone wants to help with this! Happy to support or get to it soon 😊

### Device type

iPhone and iPad

### Versions

Current development branch

**Comment by henrikth93** [comment]
I am interested in this one

**Comment by andrewtavis** [comment]
Thanks @henrikth93! Assigning you now :)

**Comment by andrewtavis** [comment]
It took just a bit for the hack to really grow on me, @henrikth93 :) d2e4c67 sends along formatting for the code, but aside from that all's great. Makes sense to me. We want an index, we need a default in case it's not there, and we assign -1 so we don't need to deal with converting the type. Thanks for the work here and the great idea! 😊
