### ISSUE TITLE
Improper use of while loop

### ISSUE THREAD

**Issue by flumaves** [scribe-org/Scribe-iOS#380]
### Terms

- [X] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

    var i = 0
    while i < 3 {
        // doing work here
        i += 1
    }

The for loop is a better alternative here, like

    for i in 0..<3 {
        // doing work here
    }

**Comment by flumaves** [comment]
Maybe this issue can be merged into the issue #379

**Comment by andrewtavis** [comment]
Hey @flumaves 👋 Makes sense to me! Feel free to send along a stand alone PR for any changes that match this and we can close this up :)

**Comment by andrewtavis** [comment]
Let me know if it's ok to assign you :)
