### ISSUE TITLE
Extract keyboard key padding functionality from KeyboardKeys.swift

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#383]
### Terms

- [X] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

The goal of this issue would be to move the functionality for adding padding to keyboard keys to the [KeyboardKeys.swift](https://github.com/scribe-org/Scribe-iOS/blob/main/Keyboards/KeyboardsBase/KeyboardKeys.swift) file from the main keyboard view controller. @henrikth93 has expressed interest in this :)

**Comment by henrikth93** [comment]
> @henrikth93, do you want to write in here so I can assign? :)

Sure!

**Comment by andrewtavis** [comment]
Assigned! Let me know if we should do another check in at some point :)

**Comment by andrewtavis** [comment]
Closed via #389 with minor formatting in 0c721ec 😊 Thanks for the continued efforts here, @henrikth93! Can't believe we're so close to having the new layouts set up! 🥳
