### ISSUE TITLE
Add license information at the top of each Scribe file

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#391]
### Terms

- [X] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

Based on a comment in #384, it looks like something we're missing for the GPL license is a notice at the top of each file. The directions for releasing GPL based code can be found [here](https://www.gnu.org/licenses/gpl-howto.en.html). It would be good for us to check what else is required and expand this issue to include other elements we're missing.

Happy to discuss this with people and implement parts of it once we've figured out all the changes that are needed!

**Comment by Jag-Marcel** [comment]
Alright, currently my plan would be to add something like this to every file:
```
/**
 * [Short description
 * of the file]
 * 
 * Copyright (C) 2023-2024 Scribe
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
```
The short description would be something like "This file controls outlets to the buttons on the 'About' page of the app" (for AboutTableViewCell.swift); the rest is the same I found on other files that already had a license notice.

**Comment by andrewtavis** [comment]
Sounds great to me, @Jag-Marcel! Appreciate you taking this on :) If you need any help with the file descriptions, then just let me know. Also happy to do some of those if you're not sure 😊

**Comment by andrewtavis** [comment]
Closing this up 🥳 Thanks for all this, @Jag-Marcel!
