### ISSUE TITLE
Convert i18n over to a JSON directory

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#392]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Something that Scribe-iOS will need to implement for a common localization process with Scribe-Android is to have a common JSON directory that has all of the localized strings that are needed for the app. This directory would then be controlled by [Scribe-i18n](https://github.com/scribe-org/Scribe-i18n) in a way that changes to i18n would then trigger PRs in Scribe-iOS and Scribe-Android (and any other repos). We'll need a base `en-US.json` file and then a file for any other language that we're localizing Scribe into 😊

We're choosing to stick with JSON to assure that localization tools like [Transifex](https://www.transifex.com/) or [weblate](https://weblate.org/en/) can be used for community localizations. We have some texts like the privacy policy that need formatting and thus their own `.swift` files, but for individual like menu option labels these can be stored within a common file. The general idea would be to save them in a JSON and then make use of [SwiftyJSON](https://github.com/SwiftyJSON/SwiftyJSON) to load them in and access the key-value pairs.

Parts to this issue:
- [ ] See if there's a good extension for this that is well maintained
- [ ] Set up Transifex/Weblate/TranslateWiki for Scribe
- [ ] Explore commits from external source i18n software to i18n repo to this repo
~~- [ ] Switch over string references in the menu to use JSON keys for localized strings~~
  - We'll have new issues for this :)

### Contribution

Happy to discuss the implementation of this and work on it or support! The focus should be on first getting all the English texts into the system, and then we can move over to [Scribe-i18n](https://github.com/scribe-org/Scribe-i18n) to start adding in new languages that will then be triggered when the user changes their system language.

**Comment by andrewtavis** [comment]
@Jag-Marcel, can you write in here so I can assign? :)

**Comment by andrewtavis** [comment]
We can get started on this once #415 is merged in 🚀

**Comment by Jag-Marcel** [comment]
👍

**Comment by andrewtavis** [comment]
Thanks @Jag-Marcel! ☀️☀️

**Comment by andrewtavis** [comment]
Closed via #452 🥳 Thanks for all the work here, @Jag-Marcel! Great progress so far 👏👏
