### ISSUE TITLE
Noun-gender annotation formatting broken on device orientation change

### ISSUE THREAD

**Issue by henrikth93** [scribe-org/Scribe-iOS#396]
From issue #388

- The transition is great!
- Sometimes the keys are not exactly sized the way they should be, but it's a major improvement
- Looks like it might be good to call the annotation function one more time after the transition?
  - We can discuss in the sync, but for me with the German keyboard the annotation bar under words shifts afterwards, but after I start typing it looks ok again (see screenshots)

![Simulator Screenshot - iPhone 15 Pro - 2024-01-13 at 14 17 44](https://github.com/scribe-org/Scribe-iOS/assets/24387426/cb56963d-563c-4872-82f1-a458d6c4a87c)

![Simulator Screenshot - iPhone 15 Pro - 2024-01-13 at 14 18 04](https://github.com/scribe-org/Scribe-iOS/assets/24387426/f260b63b-6fe6-4d85-b012-ee22ad7963dc)

After fixing that we should be good to go! 🚀

_Originally posted by @andrewtavis in https://github.com/scribe-org/Scribe-iOS/issues/388#issuecomment-1890456102_

**Comment by andrewtavis** [comment]
Thanks for making the issue, @henrikth93! I'd be happy to support someone with interest in working on this, and I'm sure @henrikth93 would be as well 😊

**Comment by andrewtavis** [comment]
Closed via #406 🥳 Thank you, @Taufi! Would be very happy to work with you again 😊
