### ISSUE TITLE
Show Wikidata description view on click of missing verb conjugations

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#400]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

An idea for how to prompt people to contribute back to Wikidata would be for the missing conjugation prompt to be a link to the lexeme for the given verb such that the user could then add it in for themselves and others. This would require the lexeme to be added into the data process as is planned for Scribe-Data, so for now this issue is blocked.

### Contribution

Happy to work on this or support someone with it eventually!

**Comment by wkyoshida** [comment]
Very interesting idea @andrewtavis!!
Makes me wonder if there are any other cases where it would be a cool idea for us to link back to Wikidata.. :thinking:
Starting off with this though sounds great to me! :rocket:

**Comment by andrewtavis** [comment]
Ya I think this can just be the start. Obviously we could even implement some REST API changes where say the user could directly add the given conjugation rather than just going to the page, but this is enough for now 😊

**Comment by Jag-Marcel** [comment]
I'd be interested in this 👍

**Comment by andrewtavis** [comment]
Thanks @Jag-Marcel! Happy to discuss this with you later :)

**Comment by andrewtavis** [comment]
Hey @Jag-Marcel :) So here's a bit more of an explanation here:

- Within Scribe we can can see this `Not on Wikidata` message when we try to conjugate something that's not in the SQLite files
- It'd be great if we added a `Click to edit` that's a link text blue
- The conjugation field would then function as a button, with the links leading someone to a Lexeme search for the given string like the following:

https://www.wikidata.org/w/index.php?search=L%3Asein

From there we can make another issue that adds on more functionality after GSoC where we'll then have the Wikidata Lexeme IDs, at which point we can link to the direct Lexeme rather than a search :)

This is the first step in integrating a bit more as a project that's giving back to Wikidata as well! Really exciting stuff 😊

Let us know if you have further questions!

**Comment by Jag-Marcel** [comment]
I tried making it work with the same method used to open links in Safari in other places, like the about tab (`UIApplication.shared.open(url)`), but this doesn't work because the keyboard doesn't have access to the shared container. Even enabling `RequestsOpenAccess` in the keyboards' `info.plist` files and allowing it in the settings doesn't work.
For the same reason, `SFSafariViewController` from `SafariServices` just opens the Safari view within the keyboard view, meaning it's just a tiny window at the bottom of the screen.
Apparently Apple doesn't allow you to open links from a keyboard whatsoever, so seemingly the only option is to copy a link to the clipboard, so the user can open it themselves. My idea would be to use a single-tile view in the keyboard to give the user some information about what's happening and give them the link for the missing word.

**Comment by andrewtavis** [comment]
Really appreciate all the research here, @Jag-Marcel! Sad that the result isn't what we're hoping for, but really thorough and commendable! 👏 @wkyoshida, what are you thinking on this? What we were discussing is a copy URL to clipboard functionality. Aside from that it looks like we won't be able to implement anything... I think that for now the link to a Wikidata search is limited in use, but with the LID it would be a bit better? 🤔

**Comment by andrewtavis** [comment]
Ok, so from the dev sync we decided that:
- We'd like all missing verb conjugations to also have an information icon `(i)` on them like the command bar does when we trying to run a command over something that's not in the database
  - I.e. translate fdsafdas or any gibberish and you'll see `Not in Wikidata` with an info icon on the right
  - We'd like this also on missing conjugations
- Clicking the missing conjugation would also load the 1x1 conjugation display with the description of Wikidata as when the user clicks the info icon `(i)` when translating something that's not in the database

Let me know if more information is needed here, @Jag-Marcel! Glad we're making progress here!

**Comment by andrewtavis** [comment]
Closed via #415 😊 Thanks for getting to this, @Jag-Marcel!
