### ISSUE TITLE
Wikidata intelligent Default

### ISSUE THREAD

**Issue by intelligentAI1** [scribe-org/Scribe-iOS#404]
### Terms

- [X] I have searched [open and closed data issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Adata+)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Languages

intelligent

### Description

Wikidata 系统 intelligent

**Comment by intelligentAI1** [comment]
[GitHub](https://github.com/scribe-org/Scribe-iOS/issues/404)

**Comment by intelligentAI1** [comment]
![IMG_0088](https://github.com/scribe-org/Scribe-iOS/assets/161969135/288957e5-7681-4d29-93b2-ffcba9f1aecc)

**Comment by andrewtavis** [comment]
Closing as this is off topic.
