### ISSUE TITLE
Fix for inconsistent corners in certain views

### ISSUE THREAD

**Issue by Jag-Marcel** [scribe-org/Scribe-iOS#416]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The 1x1 view in the conjugation view (e.g. used for the Wikidata explanation) has slightly more rounded corners than the rest of the view's buttons. Either the more rounded corners or the more pointy corners should be used consistently instead.
You get to a view like this by entering gibberish (for example "aaaaa") into any scribe functionality.

**Example:**
<img width="348" alt="image" src="https://github.com/scribe-org/Scribe-iOS/assets/63468878/1d979706-7d0e-44b3-b0c2-c2ce479554ad">
**Close-up:**
![image](https://github.com/scribe-org/Scribe-iOS/assets/63468878/a49ec2d7-26bf-4b43-8b59-48b61f85f03d)

### Contribution

I am available for any questions regarding this issue, I could also work on it myself at some point.

**Comment by andrewtavis** [comment]
Thanks for the issue, @Jag-Marcel! 😊

**Comment by fabulouiOS-monk** [comment]
Hi @Jag-Marcel, I tried reproducing the issue. I do not see any inconsistency. 
<img width="463" alt="Screenshot 2024-05-07 at 3 19 09 PM" src="https://github.com/scribe-org/Scribe-iOS/assets/60264030/2cce3fb8-8f9c-491a-a9cf-bc75783f1250">
<img width="52" alt="Screenshot 2024-05-07 at 3 19 25 PM" src="https://github.com/scribe-org/Scribe-iOS/assets/60264030/607a26a5-0947-4948-9b98-e031ea62190f">


Please guide If I missed any thing!

**Comment by fabulouiOS-monk** [comment]
Hey @andrewtavis, I didn't have any changes that would reflect a darker shadow. This screenshot is straight up from the cloned repo code.

**Comment by Jag-Marcel** [comment]
Whoops, looks like I missed this, I tried using the main branch and the corners are normal, so it seems this is a bug introduced in my PR #415. I'm using a 15 pro simulator @andrewtavis, but it looks like the problem here was just that I forgot to check against my changes.
The darker shadows and outline on the scribe bar are weird though, they don't show up on my end either. Speaking of the outline though, I can see that it exists on the original, but it's almost the same colour as the background, which means it creates a tiny gap between the bar and the shadow. This seems unintended to me, maybe we can look into this at some point as well?

**Comment by fabulouiOS-monk** [comment]
Hi @andrewtavis, the simulator was iPhone 15 pro (17.2) and it was in light mode(as far as I remember, I didn't switch it between dark and light mode).

**Comment by andrewtavis** [comment]
Thanks so much for the further information, @fabulouiOS-monk! @Jag-Marcel, I was going to say that we can remove the border around the command bar as the shadow will cover it for us, but then in dark mode it's necessary to distinguish it from the rest of the interface. Maybe we can remove it on light mode :) I'll make an issue regardless and ping the both of you in there!

Thanks for the conversation, you two! 🚀

**Comment by andrewtavis** [comment]
Minor note from the dev sync: the thought on this is that maybe the a11y settings were turned on such that the command bar was made a bit more visible? Maybe because they had a border, this border was enhanced? Thoughts on this @fabulouiOS-monk? Changes for removing it are good anyway!

**Comment by fabulouiOS-monk** [comment]
> Minor note from the dev sync: the thought on this is that maybe the a11y settings were turned on such that the command bar was made a bit more visible? Maybe because they had a border, this border was enhanced? Thoughts on this @fabulouiOS-monk? Changes for removing it are good anyway!

Sorry didn't get you, what is `a11y` settings?

**Comment by fabulouiOS-monk** [comment]
Yes, a11y may be the factor for enhanced shadow and border. But if it was there for the border it should be applied to the full view and shadow. 

And in future, if we are going to implement accessibility Identifiers, it can be addressed in that. Or I am fine with reverting the changes.

**Comment by andrewtavis** [comment]
Thanks for checking in, @fabulouiOS-monk :) We're good with the changes. I'll send along another minor change for the command bar based on discussions we had in the dev sync. Would be great to have you in the next one! Details for that are in the [general channel on Matrix](https://matrix.to/#/!yQJjLmluvlkWttNhKo:matrix.org?via=matrix.org).
