### ISSUE TITLE
Inconsistent command bar outline behavior

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#423]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

Something that was discussed in #416 is that we're at times seeing inconsistent borders around the command bar. The following is from an iPhone 15 Pro simulator:

<img width="348" alt="image" src="https://github.com/scribe-org/Scribe-iOS/assets/63468878/1d979706-7d0e-44b3-b0c2-c2ce479554ad">

And the following is from an iPhone 15.2 Pro simulator:

<img width="463" alt="Screenshot 2024-05-07 at 3 19 09 PM" src="https://github.com/scribe-org/Scribe-iOS/assets/60264030/2cce3fb8-8f9c-491a-a9cf-bc75783f1250">

In the above, the shadows are darker under the buttons, and the border around the command bar is also darker. One way to improve this a bit would be to remove the border around the command bar on light mode, as the shadow is providing enough contrast (is needed on dark mode though).

Open to discussions on this and working with people on it!

### Device type

iPhone

### Versions

Current main version

**Comment by andrewtavis** [comment]
CC @Jag-Marcel and @fabulouiOS-monk 😊 Let me know on the idea of removing the border around the command bar! Happy to get suggestions on what's up with the shadows as well :)

**Comment by fabulouiOS-monk** [comment]
Hi @andrewtavis, I did some work on it and here are the Screenshots with the code updates:
**Removed shadow from below the bar**

In Dark mode:
<img width="387" alt="noShadow-Dark" src="https://github.com/scribe-org/Scribe-iOS/assets/60264030/402362a3-ea94-49f4-bf31-7f987aa078a1">

In Light mode:
<img width="385" alt="noShadow-Light" src="https://github.com/scribe-org/Scribe-iOS/assets/60264030/e4f7a2b8-2945-4324-a542-06c361d8d0ac">

**Comment by fabulouiOS-monk** [comment]
If all good from your side I can raise  PR for it.

**Comment by andrewtavis** [comment]
Thanks for looking into this, @fabulouiOS-monk :) Looking at it, I think that having the shadow still would be important, but maybe we can try removing the border from the command bar and Scribe key in light mode? Maybe the contrast is enough to also work in dark mode, but let's check in light mode first 😊

**Comment by andrewtavis** [comment]
Assigning you as we're working on this, @fabulouiOS-monk :)

**Comment by fabulouiOS-monk** [comment]
Sure, thank you will look into it.

**Comment by andrewtavis** [comment]
Thanks for the repeat to check our understanding, @fabulouiOS-monk! All sounds good, and looking forward to seeing what you find out 😊

**Comment by fabulouiOS-monk** [comment]
@andrewtavis, Here are the Screenshots with the border removed and the shadow kept as it is:

**Dark mode** (I think the contrast is enough to make the difference):
<img width="391" alt="withoutBorder-dark" src="https://github.com/scribe-org/Scribe-iOS/assets/60264030/66248723-708d-4d7a-b725-9020c7635b31">

**Light mode**:
<img width="384" alt="withoutBorder-light" src="https://github.com/scribe-org/Scribe-iOS/assets/60264030/9db1f6e6-9ddf-4954-8977-abf506f07ab8">


P.S: Took time since working this with my regular job ;)

**Comment by fabulouiOS-monk** [comment]
@andrewtavis, So do we need to update it or let it be?

**Comment by andrewtavis** [comment]
Hey @fabulouiOS-monk 👋 Have been at work :) I think we're good for a PR so I can play around with it myself and see 😊 Thanks for the work till now!

**Comment by fabulouiOS-monk** [comment]
Hey @andrewtavis, Thank you, I raised the PR!

**Comment by andrewtavis** [comment]
Thanks, @fabulouiOS-monk! I'll try to get to it this weekend with the other PR :) :)

**Comment by andrewtavis** [comment]
Closed via #438 🚀 Thanks so much for the conversation here and the changes, @fabulouiOS-monk! 😊
