### ISSUE TITLE
SwiftLint: Fix todo throughout codebase

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#424]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Work for this issue would remove `todo` as a disabled rule from [.swiftlint.yml](https://github.com/scribe-org/Scribe-iOS/blob/main/.swiftlint.yml) and fix all errors for it in the codebase.

Docs for todo are here: https://realm.github.io/SwiftLint/todo.html

We'd know that this is successful if our SwiftLint pull request workflow passes on the pull request for the change 🚀

### Contribution

I'll work on this one by making issues to account for all todos that include information on what's to be done and the location of the original todo 😊

**Comment by christianbilodeau** [comment]
Hi, I looked into this one, just to confirm, all the TODOs are of the format: 

> add < key > to rightKeyChar if the keyboard has 4 rows

I'm assuming "4 rows" refers to the "floating keyboard" feature on iPad, which allows the user to minimise the keyboard and move it around the screen? It's the only keyboard format where I've seen the need for the correct popup on right key characters.

Thanks!

**Comment by andrewtavis** [comment]
Hey @christianbilodeau 👋 I'm thinking four rows is actually something to do with whether the numbers row is present or not, actually. Thanks for your consideration of this! Would be great to get some support making these issues and getting rid of the todos :)

**Comment by christianbilodeau** [comment]
Hello again @andrewtavis, the _add "p" to rightKeyChar if the keyboard has 4 rows_ comments might be non-issues, as seen at least on my iPad mini iOS 18 simulator. The "p" key doesn't appear at the very right of the screen and therefore the current popup makes sense as it is (it appears to be cropped at the top, but that's a different issue):

<img width="300" alt="Screenshot 2024-10-01 at 15 18 36" src="https://github.com/user-attachments/assets/40dac12b-33bb-4159-a648-aaef22671a85">


However, I did notice some keys having the wrong popup when the keyboard has 5 rows (big iPad).

 \  Should be left:

<img width="300" alt="Screenshot 2024-10-01 at 15 20 45" src="https://github.com/user-attachments/assets/a99c223c-34e0-44f2-b43c-7ceb63029553">

_*_ Should be right:

<img width="330" alt="Screenshot 2024-10-01 at 15 21 11" src="https://github.com/user-attachments/assets/c15dccda-001b-448e-9c35-3560580cb5cb">

Same issue for the symbol keys at the same positions. Happy to create issues for these if you confirm.

**Comment by andrewtavis** [comment]
Closed by d808dcd as it looks like all the TODOs were removed in recent work. swiftlint now checks for these, and the above commit also details the testing for the codebase and notes it in the PR template.

Thanks much for the discussion here, @christianbilodeau! 😊
