### ISSUE TITLE
SwiftLint: Fix orphaned_doc_comment throughout codebase

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#425]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Work for this issue would remove `orphaned_doc_comment` as a disabled rule from [.swiftlint.yml](https://github.com/scribe-org/Scribe-iOS/blob/main/.swiftlint.yml) and fix all errors for it in the codebase.

Docs for `orphaned_doc_comment` are here: https://realm.github.io/SwiftLint/orphaned_doc_comment.html

We'd know that this is successful if our SwiftLint pull request workflow passes on the pull request for the change 🚀

### Contribution

This would be a great `good first issue` for someone wanting to start with Scribe-iOS development. Happy to support! 😊

**Comment by jon-tous** [comment]
Hi, happy to take this on as my first issue here :) @andrewtavis thanks for the warm welcome!

**Comment by andrewtavis** [comment]
Thanks for your interest in helping out, @jon-tous!

**Comment by andrewtavis** [comment]
Closed by #487 😊 Appreciate the quick contribution and the great communication, @jon-tous!
