### ISSUE TITLE
SwiftLint: Fix opening_brace throughout codebase

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#426]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Work for this issue would remove `opening_brace` as a disabled rule from [.swiftlint.yml](https://github.com/scribe-org/Scribe-iOS/blob/main/.swiftlint.yml) and fix all errors for it in the codebase.

Docs for `opening_brace` are here: https://realm.github.io/SwiftLint/opening_brace.html

We'd know that this is successful if our SwiftLint pull request workflow passes on the pull request for the change 🚀

### Contribution

This would be a great `good first issue` for someone wanting to start with Scribe-iOS development. Happy to support! 😊

**Comment by mostazomarc** [comment]
I'll be working on it!

**Comment by andrewtavis** [comment]
Nice, @mostazomarc! Thanks for picking up so many of these 😊

**Comment by andrewtavis** [comment]
Closed via #443 🚀 Appreciate all the work here, @mostazomarc! Again, let me know on if showing up to a dev sync would be of interest at some point :)
