### ISSUE TITLE
SwiftLint: Fix blanket_disable_command throughout codebase

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#427]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Work for this issue would remove `blanket_disable_command` as a disabled rule from [.swiftlint.yml](https://github.com/scribe-org/Scribe-iOS/blob/main/.swiftlint.yml) and fix all errors for it in the codebase.

Docs for `blanket_disable_command` are here: https://realm.github.io/SwiftLint/blanket_disable_command.html

We'd know that this is successful if our SwiftLint pull request workflow passes on the pull request for the change 🚀

### Contribution

This would be a great `good first issue` for someone wanting to start with Scribe-iOS development. Happy to support! 😊

**Comment by jon-tous** [comment]
Hi! It looks like SwiftLint found no violations of this rule currently in the codebase. I can submit a quick PR to remove the rule from disabled_rules which would close this issue and enforce the rule moving forward.

**Comment by andrewtavis** [comment]
Closed by #489 :) Appreciate all the effort to get the swiftlint checks being more comprehensive, @jon-tous!
