### ISSUE TITLE
SwiftLint: Fix for_where throughout codebase

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#428]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Work for this issue would remove `for_where` as a disabled rule from [.swiftlint.yml](https://github.com/scribe-org/Scribe-iOS/blob/main/.swiftlint.yml) and fix all errors for it in the codebase.

Docs for `for_where` are here: https://realm.github.io/SwiftLint/for_where.html

We'd know that this is successful if our SwiftLint pull request workflow passes on the pull request for the change 🚀

### Contribution

This would be a great `good first issue` for someone wanting to start with Scribe-iOS development. Happy to support! 😊

**Comment by jon-tous** [comment]
Happy to take this one on!

**Comment by andrewtavis** [comment]
Assigned, @jon-tous! :) Let us know if there's anything we can do to help 😊

**Comment by andrewtavis** [comment]
Closed via #488 🚀 Please let us know if there's another issue you'd be interested to work on, @jon-tous! Happy to also answer any questions you have about the project, with a call being possible as well if you'd find it helpful :)
