### ISSUE TITLE
SwiftLint: Fix trailing_whitespace throughout codebase

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#429]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Work for this issue would remove `trailing_whitespace` as a disabled rule from [.swiftlint.yml](https://github.com/scribe-org/Scribe-iOS/blob/main/.swiftlint.yml) and fix all errors for it in the codebase.

Docs for `trailing_whitespace` are here: https://realm.github.io/SwiftLint/trailing_whitespace.html

We'd know that this is successful if our SwiftLint pull request workflow passes on the pull request for the change 🚀

### Contribution

This would be a great `good first issue` for someone wanting to start with Scribe-iOS development. Happy to support! 😊

**Comment by mostazomarc** [comment]
I'll be working on it!

**Comment by andrewtavis** [comment]
Thanks, @mostazomarc! :)

**Comment by andrewtavis** [comment]
Closed by #435. Appreciate the quick work here, @mostazomarc! Happy to work on another linting error, or let me know if something else sounds interesting 😊
