### ISSUE TITLE
SwiftLint: Fix vertical_whitespace throughout codebase

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#430]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Work for this issue would remove `vertical_whitespace` as a disabled rule from [.swiftlint.yml](https://github.com/scribe-org/Scribe-iOS/blob/main/.swiftlint.yml) and fix all errors for it in the codebase.

Docs for `vertical_whitespace` are here: https://realm.github.io/SwiftLint/vertical_whitespace.html

We'd know that this is successful if our SwiftLint pull request workflow passes on the pull request for the change 🚀

### Contribution

This would be a great `good first issue` for someone wanting to start with Scribe-iOS development. Happy to support! 😊

**Comment by mostazomarc** [comment]
I'll be working on it!

**Comment by andrewtavis** [comment]
Thanks @mostazomarc! Looking forward to the PR 🙌

**Comment by andrewtavis** [comment]
Closed via #442 :) Thank you, @mostazomarc!
