### ISSUE TITLE
SwiftLint: Fix void_function_in_ternary throughout codebase

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#431]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Work for this issue would remove `void_function_in_ternary` as a disabled rule from [.swiftlint.yml](https://github.com/scribe-org/Scribe-iOS/blob/main/.swiftlint.yml) and fix all errors for it in the codebase.

Docs for `void_function_in_ternary` are here: https://realm.github.io/SwiftLint/void_function_in_ternary.html

We'd know that this is successful if our SwiftLint pull request workflow passes on the pull request for the change 🚀

### Contribution

This would be a great `good first issue` for someone wanting to start with Scribe-iOS development. Happy to support! 😊

**Comment by mostazomarc** [comment]
I'll work on it!

**Comment by andrewtavis** [comment]
Thanks for picking all these up, @mostazomarc!

**Comment by andrewtavis** [comment]
Closed via #444 🚀 Great to have all of this progress, @mostazomarc!
