### ISSUE TITLE
SwiftLint: Fix empty_enum_arguments throughout codebase

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#432]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Work for this issue would remove `empty_enum_arguments` as a disabled rule from [.swiftlint.yml](https://github.com/scribe-org/Scribe-iOS/blob/main/.swiftlint.yml) and fix all errors for it in the codebase.

Docs for `empty_enum_arguments` are here: https://realm.github.io/SwiftLint/empty_enum_arguments.html

We'd know that this is successful if our SwiftLint pull request workflow passes on the pull request for the change 🚀

### Contribution

This would be a great `good first issue` for someone wanting to start with Scribe-iOS development. Happy to support! 😊

**Comment by fabulouiOS-monk** [comment]
Will be working on this!

**Comment by andrewtavis** [comment]
Thanks for picking it up, @fabulouiOS-monk!

**Comment by andrewtavis** [comment]
Closed by #439 😊 Thanks for the help here, @fabulouiOS-monk!
