### ISSUE TITLE
SwiftLint: Fix closure_parameter_position throughout codebase

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#433]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Work for this issue would remove `closure_parameter_position` as a disabled rule from [.swiftlint.yml](https://github.com/scribe-org/Scribe-iOS/blob/main/.swiftlint.yml) and fix all errors for it in the codebase.

Docs for `closure_parameter_position` are here: https://realm.github.io/SwiftLint/closure_parameter_position.html

We'd know that this is successful if our SwiftLint pull request workflow passes on the pull request for the change 🚀

### Contribution

This would be a great `good first issue` for someone wanting to start with Scribe-iOS development. Happy to support! 😊

**Comment by fabulouiOS-monk** [comment]
Will be working on it!

**Comment by andrewtavis** [comment]
Thanks, @fabulouiOS-monk! Will give the PR a review sometime over the weekend :)

**Comment by andrewtavis** [comment]
Closed via #437 🚀 Appreciate all the work you're putting in, @fabulouiOS-monk!
