### ISSUE TITLE
Change color of installation directions corner on click

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#461]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

When first entering the Scribe application the user is presented with keyboard installation instructions. Clicking this will take the user to the settings for Scribe where they can easily select which keyboard to install. One minor issue with this is that the orange corner of the settings directions (see below) doesn't change color with the rest of the view when it's clicked. This issue would fix this 😊

![Simulator Screenshot - iPhone 15 - 2024-06-15 at 12 47 28](https://github.com/scribe-org/Scribe-iOS/assets/24387426/a103676a-beaf-4240-8399-8de7fb337533)

### Contribution

Happy to support or get to this eventually myself! This would be a fairly good `good first issue` if someone would like to give it a shot, or also would be great for a current community member to work on!

**Comment by fabulouiOS-monk** [comment]
@andrewtavis, I can get this done!

Just a re-validation, we want the **settings gear icon to blink as the other parts, right?**

**Comment by andrewtavis** [comment]
Exacctly, @fabulouiOS-monk! I'll review it soon 😊

**Comment by andrewtavis** [comment]
Closed by #464 🥳 Thank you, @fabulouiOS-monk! Great to already be making progress on v3.1! 🚀
