### ISSUE TITLE
Add animation to app hints appearing and disappearing

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#462]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

In #329 we added in hints to the UI to explain what certain tabs are doing for the user. As of now these hints appear and disappear without an animation or transition. It would be great if they would include one! See below for an example of the app hints:

![Simulator Screenshot - iPhone 15 - 2024-06-15 at 12 51 08](https://github.com/scribe-org/Scribe-iOS/assets/24387426/4389a11b-c348-4f92-9ac5-b5299b0ad15a)

### Contribution

Happy to help with this or get to it myself eventually! Would also be great to get some support for this from the community 😊

**Comment by andrewtavis** [comment]
@fabulouiOS-monk, do you want to write in here so I can assign as #468 will close this with the new work you have locally? :)

**Comment by fabulouiOS-monk** [comment]
Yep, assign it to me. Thanks!

**Comment by andrewtavis** [comment]
Closed by #468 😊 Thanks so much for the hard work here and the dedication, @fabulouiOS-monk! 🙏
