### ISSUE TITLE
Clicking `OK` on app hint when it's over a menu option clicks the menu option

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#465]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

Some unexpected behavior for the app hints is that when they're over a an app settings option, then the settings option is clickable from beneath the hint. This is not common as it's uncommon for the settings pages to be scrollable at this time given how many options there are, but is the case for iPhones with home buttons like an iPhone 8 or SE. See screenshot below:

![Simulator Screenshot - iPhone SE (3rd generation) - 2024-06-16 at 12 37 28](https://github.com/scribe-org/Scribe-iOS/assets/24387426/19d39f3b-a239-4570-9e60-1436d90ad84d)

In this screenshot I've scrolled down slightly such that now the app hint is above the option to view the source code on GitHub. Clicking the app hint in this case opens the link to GitHub rather than closing the hint.

### Device type

iPhone

### Versions

v3.0 and current main

**Comment by andrewtavis** [comment]
CC @fabulouiOS-monk :) Would you want to look into this? This and #462 would basically finish up the app hints, to my knowledge. We'd need to eventually figure out how to change them if say a user goes into a keyboard's settings or does an app tutorial, but for the current iteration these issues would be great to handle pre-v3.1! 😊

**Comment by fabulouiOS-monk** [comment]
@andrewtavis, Ok let me check this out!

**Comment by andrewtavis** [comment]
Thanks for this, @fabulouiOS-monk! :)

**Comment by andrewtavis** [comment]
Closed by #468 😊 Thanks, @fabulouiOS-monk! 🚀
