### ISSUE TITLE
Allow menu options to have text to the left of the selector

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#469]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As discussed in a recent call, we'd like to break #255 up into smaller issues :) This issue will focus on adding an option to put text to the left of selectors in menu options, so when there's a chevron as the right icon of a menu option, we could then put text like the current translation language to its left. We'll also use this in #255 for the menu options themselves. Designs for various menu options with this element can be seen [here](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=513-1616&t=nLduZtGK7BTGyEgx-1) 🖼️

### Contribution

@Jag-Marcel will be doing this as a part of GSoC 2024 ☀️ Please write in here so we can assign, and let us know if any support is needed! 😊

**Comment by Jag-Marcel** [comment]
Thank you 🙏

**Comment by andrewtavis** [comment]
Closed by #476 :) Thanks for the great work to make the menu so consistent, @Jag-Marcel! 🚀
