### ISSUE TITLE
Add radio button menu option selection table

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#470]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As discussed in a recent call, we'd like to break #255 up into smaller issues :) This issue will focus on creating a menu table with radio buttons, which will be used in #255, #314 and others! Designs for this can be seen on Figma [here](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=544-1527&t=nLduZtGK7BTGyEgx-1) 🖼️

### Contribution

@Jag-Marcel will be doing this as a part of GSoC 2024 ☀️ Please write in here so we can assign, and let us know if any support is needed! 😊

**Comment by Jag-Marcel** [comment]
Thank you 🙏

**Comment by andrewtavis** [comment]
Closed by #476 🙌 So happy to have this done so we can use it for other menu options, @Jag-Marcel! 🚀
