### ISSUE TITLE
Add link to Mastodon to the app About tab

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#474]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would add a link to the [Scribe Mastodon account](https://wikis.world/@scribe) to the About tab of the application. Placement and design can be seen in the following export from the [Figma designs](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=513-2206&t=VVL5wiVs67VtbJHI-1).

![Menu Options](https://github.com/user-attachments/assets/e5624a5a-9110-4423-a58a-66ba335fead6)

The external link should direct the user to: https://wikis.world/@scribe

### Contribution

Would be happy to support someone who has interest in working on this! This would be a great `good first issue`, or is also open to other contributors to tackle 😊

**Comment by andrewtavis** [comment]
Ping @fabulouiOS-monk via the sync discussion, can you write in here and I'll assign? :)

**Comment by fabulouiOS-monk** [comment]
Yup.

**Comment by andrewtavis** [comment]
Closed by #478 😎 Awesome that both of these issues were closed up so quickly, @fabulouiOS-monk! 👏
