### ISSUE TITLE
Add reset icon to reset app hints option in the app About tab

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#475]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

A nice addition to the application About tab would be to have an icon for each menu option. For this, we can add a spiral arrow icon to the `Reset app hints` option as shown below from the [designs on Figma](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=513-2206&t=TU1aMxLXHaeY9cc6-1):

![Menu Options](https://github.com/user-attachments/assets/dd0483e0-f6f4-4240-bca5-3e7efd93ae1b)

We need to make sure it's colored the same as the other icons, and we can use `arrow.circlepath` from SF Symbols :)

### Contribution

Happy to support someone with interest in working on this! This is a great `good first issue`, but is also open to other members of the community 😊

**Comment by andrewtavis** [comment]
Ping @fabulouiOS-monk via the sync discussion, can you write in here and I'll assign? :)

**Comment by fabulouiOS-monk** [comment]
Yup, here we go.

**Comment by andrewtavis** [comment]
Closed by #478 😊 Thanks for all the help and getting to it all so quickly, @fabulouiOS-monk!
