### ISSUE TITLE
Remove accent characters menu option from iPads

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#477]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

An issue that we have right now is that the disable accent characters option is available for iPads when it shouldn't be. Enabling this option crashes the keyboard, so it should be removed as this option doesn't add much for an iPad user (likely wouldn't be used).

One consideration though is that the Layout section of the menu would then be empty. We thus should conditionally render the settings section if there is an option present, or remove the entire section if it's not needed :)

Happy to support or work on this!

### Device type

iPad

### Versions

v3.0 and current main

**Comment by fabulouiOS-monk** [comment]
@andrewtavis, you can assign me this now. I will be in touch with you regarding the details. Thank you!

**Comment by andrewtavis** [comment]
Thanks so much for picking this up, @fabulouiOS-monk! 🚀

**Comment by andrewtavis** [comment]
Closed by #480! 🎉 Thanks so much for the quick work here, @fabulouiOS-monk! 🚀
