### ISSUE TITLE
Add menu option for turning off the double space period shortcut

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#479]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would add a menu option into all keyboard settings that would allow the user to turn the double space period shortcut off. The shortcut should be on by default. The placement for the option can be seen in the [Figma designs](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=513-1616&t=UBIa86s4uq4Mr97Z-1) as well as below:

![Keyboard Settings - Light](https://github.com/user-attachments/assets/b91f3a2f-7f7a-4703-83c7-f6e52cd22049)

### Contribution

Would be happy to work on this eventually or support someone who has interest! 😊

**Comment by andrewtavis** [comment]
Sure thing, @vickcoo! Please let us know if there's anything we can do to help :)

**Comment by andrewtavis** [comment]
Closed via #491 🚀 Thanks so much for the contribution, @vickcoo! Very much hope it's not the last :)

**Comment by vickcoo** [comment]
Thanks @andrewtavis 😊, I will contribute more!
