### ISSUE TITLE
Switch all language references in code to ISO-2 codes

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#494]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is a simple one of renaming variables. As of now throughout the codebase we're naming variables based on the language and the ISO-2 code of the language, so like `EnglishVarName` and `enVarName`. We should rather use ISO-2 codes throughout the codebase so it's consistent.

As a part of this, we should also organize some of the new files within the repo, which can be done by maintainers in the PR that comes from this :)

### Contribution

Happy to support with renaming and help move files around once the PR is up! 😊

**Comment by andrewtavis** [comment]
Note that we'll still have the Language names as directories names within the language keyboards directory, but the code references themselves should just be the two letter codes :)

**Comment by krp-bot9** [comment]
@andrewtavis I would love to work on this issue, please assign this to me

**Comment by helocordi** [comment]
Hi @andrewtavis I'm looking for a good first issue to contribute to. Could I check for this one ?

**Comment by andrewtavis** [comment]
Would be great, @helocordi! Please let us know if you need any support :)

**Comment by andrewtavis** [comment]
Hope it's ok if we reassign, @henrikth93! Lots else you can get to :) Let's be in touch during the sync!

**Comment by henrikth93** [comment]
> Hope it's ok if we reassign, @henrikth93! Lots else you can get to :) Let's be in touch during the sync!

That is absolutely fine! When it comes to issues I feel like I have hoarded a little hehe.

**Comment by helocordi** [comment]
> Would be great, @helocordi! Please let us know if you need any support :)

Thank you, I'll take a look then

**Comment by ThousandYearGrind** [comment]
Hi @andrewtavis ! Is this issue resolved? I'm looking to make my first-ever contribution.

**Comment by andrewtavis** [comment]
@helocordi is working on this right now, @ThousandYearGrind :) Please let us know if there's another issue that you'd have interest in 😊

**Comment by henrikth93** [comment]
> Hi @andrewtavis ! Is this issue resolved? I'm looking to make my first-ever contribution.

Hello @ThousandYearGrind and welcome!
I am assigned to an issue, which maybe you want to take over? https://github.com/scribe-org/Scribe-Android/issues/149

It is Android-related, is that something you want to do?

**Comment by ThousandYearGrind** [comment]
Hi @henrikth93 , and thank you for your offer. I would to give the issue a try!

**Comment by ThousandYearGrind** [comment]
> > Hi @henrikth93 , and thank you for your offer. I would to give the issue a try!
> 
> Nice, do you know how to assign yourself?

No, how do I do that?

**Comment by andrewtavis** [comment]
A bit confused by the conversation above. Let me know which issue we're talking about here and I can assign :)

**Comment by ThousandYearGrind** [comment]
> A bit confused by the conversation above. Let me know which issue we're talking about here and I can assign :)

@andrewtavis https://github.com/scribe-org/Scribe-Android/issues/149

**Comment by andrewtavis** [comment]
Closed by #524 🚀 Thank you for the help and the great communication here, @helocordi! 😊
