### ISSUE TITLE
Create GitHub Actions workflow to run CI process

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#499]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would implement a GitHub Actions workflow whereby the CI process for Scribe-iOS that's being worked on in #8 would be ran on every pull request. Direction on how to test Swift projects with GitHub Actions can be see [here](https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-swift). Note that we would like this at first to be a separate workflow `pr_ci.yaml` and be included as another step in [.github/workflows/pr_swiftlint.yaml](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/workflows/pr_swiftlint.yaml) so that we can see which setup works better for maintainers (this will be discussed in the community as well).

### Contribution

CC @fabulouiOS-monk, who said he'd have interest in this :) Also CC @vickcoo :) Let us know if there's anything we can do to support!

**Comment by fabulouiOS-monk** [comment]
Thank you @andrewtavis for creating the issue. Will start working on it.

**Comment by andrewtavis** [comment]
Thanks for the initiative here, @fabulouiOS-monk! :) :)

**Comment by andrewtavis** [comment]
PR is merged in, @fabulouiOS-monk :) Feel free to also send along edits to the testing file if you think they're needed!

**Comment by andrewtavis** [comment]
Closed by #500 🚀 Thanks so much for the work here, @fabulouiOS-monk! So much progress coming recently 😊
