### ISSUE TITLE
Check of privacy policy

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#50]
### Terms

- [x] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue)
- [x] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

Scribe's [privacy policy](https://github.com/scribe-org/Scribe-iOS/blob/main/PRIVACY.txt) is a general sketch of what's needed for a proper privacy policy, but there likely are issues with it as it was not written by a legal professional. Input on how it could be improved would be much appreciated!

**Comment by wldeh** [comment]
I would be happy to work on improving the privacy policy. I believe that it is already quite well written and doesn’t require any major changes.

However, it would be beneficial to add a section about the security measures we have in place to protect user data as well as information about how users will be notified when the privacy policy is updated. I do think collecting data is essential to sustaining and improving the app and is definitely something we should discuss and consider.

That being said some more extensive changes would include providing more detailed information about the third-party services we use, potentially along with links to their privacy policies and data handling practices. Adding a summary of the privacy policy at the beginning would be very helpful as well. If you want me to draft a pull request addressing these changes, feel free to let me know!

**Comment by andrewtavis** [comment]
Hi @wldeh! Great to firstly hear that there aren’t major changes needed 😊 Your suggestions sound great as well :) You are more than welcome to draft a suggestion!  

Let’s work on the normal [privacy policy](https://github.com/scribe-org/Scribe-iOS/blob/main/PRIVACY.txt) in an initial commit, and then after we agree on the changes you’d also be welcome to commit to the [other version](https://github.com/scribe-org/Scribe-iOS/blob/main/Scribe/AppTexts/English/ENPrivacyPolicy.swift) that’s in app :)

**Comment by wldeh** [comment]
> Scribe's [privacy policy](https://github.com/scribe-org/Scribe-iOS/blob/main/PRIVACY.txt) is a general sketch of what's needed for a proper privacy policy, but there likely are issues with it as it was not written by a legal professional. Input on how it could be improved would be much appreciated!

Hi @andrewtavis, sorry, forgot about this. Making changes currently and will share soon. Happy to collaborate on your other project as well. Thanks!

**Comment by andrewtavis** [comment]
No stress, @wldeh! Happy to remind and totally fine to have this slip your mind :) Thanks for your interest in the other project. I'll check what you have in #287 later today 😊

**Comment by wldeh** [comment]
> 

Hi @andrewtavis, no worries at all! I'm currently working on the privacy policy updates and will share them soon. Excited to collaborate on your other project as well. Thanks for your understanding!

**Comment by andrewtavis** [comment]
Closed via #287 and 1ca6971 😊 We can rework the privacy policy in the future as new changes to the app are added.

I also realized that with the CLDR data for emojis we needed to update that section :) Good timing on helping with this, @wldeh! And thanks again so much for the help!
