### ISSUE TITLE
Version needs to be converted to an external link to directs towards the releases on GitHub

### ISSUE THREAD

**Issue by angrezichatterbox** [scribe-org/Scribe-iOS#504]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The About page currently has a Feedback and support table view that consists of Rate Scribe, Report a bug, Send us an email, and Reset app hint options. The issue is to add another option for Version that would redirect the user to the Github Releases of Scribe-iOS.

Image references are given below:

<img width="603" alt="369754764-09fb6202-7a50-4914-b883-01a994f5c703" src="https://github.com/user-attachments/assets/2e989ac8-ad4d-4f83-b2bb-32cbbd599583">

**Comment by andrewtavis** [comment]
Thanks for the issue over here, @angrezichatterbox!

**Comment by andrewtavis** [comment]
Closed by #505 :) Thanks for the hard work here and for your patience, @Mehul721! Please let us know if you have interest in working on something else 😊
