### ISSUE TITLE
[iPad] Wrong popup for some keys on larger iPad models

### ISSUE THREAD

**Issue by christianbilodeau** [scribe-org/Scribe-iOS#509]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

Some characters should be considered to be "left" or "right" key characters on larger iPad models (see xInterfaceVariables.swift files)

For example, this \ should show a "left" popup:

<img width="300" alt="Screenshot 2024-10-01 at 15 20 45" src="https://github.com/user-attachments/assets/4ffbb06c-937c-4eb4-8de1-8c043eabc121">

And this * should show a "right" popup:

<img width="330" alt="Screenshot 2024-10-01 at 15 21 11" src="https://github.com/user-attachments/assets/00ecdd2a-ad71-4462-9517-7d819c45dc73">

### Device type

iPad

### Versions

iOS 17.5.1 & Scribe 3.1.1

**Comment by christianbilodeau** [comment]
I can tackle this one

**Comment by christianbilodeau** [comment]
PR opened [here](https://github.com/scribe-org/Scribe-iOS/pull/511). Doing the changes I uncovered a separate [issue](https://github.com/scribe-org/Scribe-iOS/issues/510) about repeating keys :)

**Comment by andrewtavis** [comment]
Thanks so much for all the issues, @christianbilodeau! 🚀 Looking forward to the review :)

**Comment by andrewtavis** [comment]
Closed via #511 🚀 Thanks so much for a great contribution, @christianbilodeau! Hope we'll be able to work with you again 😊 Please feel free to open issues anytime!
