### ISSUE TITLE
Move installation corner to the left when menu language is RTL

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#513]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would add in an optional top left corner triangle for the installation screen of the menu for RTL languages. As Arabic is the only RTL language in Scribe-i18n at this time, the menu should check to see if Arabic has been selected and then switch the corner triangle if so. The current interface can be seen here:

![Installation Directions](https://github.com/user-attachments/assets/b7b53dcd-91fb-4975-a715-e59d9b3eda13)

### Contribution

Happy to support with this and review when a PR is up! Can also work on it myself if needed 😊

**Comment by andrewtavis** [comment]
We're down to this issue for v3.2.0, @Jag-Marcel 😊 Let me know if a call would be helpful on this or if there's anything else I can do to support! :)

**Comment by Jag-Marcel** [comment]
@andrewtavis I'll probably manage to do it over the coming week, I just didn't have the time to look into it yet. I'll update you if I need support but it should be fine for now.

**Comment by andrewtavis** [comment]
Sounds perfect, @Jag-Marcel! Hope the weekend's going well :)

**Comment by andrewtavis** [comment]
Closed by #516 🚀 Let's Close up #517 and #518 before the next release, @Jag-Marcel, as they really do impact the user experience. I did my best in #516 to fix the apparent changes that were needed like the chevron direction and also the Settings tab headers for RTL languages. Maybe for #518 something will jump out to you?

Let me know if you'd have interest in picking up either of those, and thanks for getting to this one! Almost there! 🚀

**Comment by andrewtavis** [comment]
Thanks for self assigning #518, @Jag-Marcel! 😊😊

**Comment by andrewtavis** [comment]
Let's be in touch on all this :)
