### ISSUE TITLE
Remove menu corners from About pages

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#514]
### Terms

- [X] I have searched [open and closed design issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Adesign)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

A decision was recently made that the corner triangles for the app menu are more of a problem than the benefits that they bring to the UI. In #513 we're allowing for RTL language support for the installation page and keeping the corner triangle, and aside from this we should also remove the triangles from the `Wikimedia and Scribe`, `Privacy Policy` and `Third-party licenses` pages in `About`. This will make localization and specifically RTL localization dramatically easier.

### Contribution

Happy to support here and review when a PR is opened 😊

**Comment by andrewtavis** [comment]
Would you have interest in picking this up, @henrikth93? Might be a good one to get to along with #494? :)

**Comment by henrikth93** [comment]
Sure! I can work on this!

**Comment by andrewtavis** [comment]
Thanks! Let's sync on this once we get the needed updates done :) I think this'll be a good chance for you to work more with layouts 😊

**Comment by andrewtavis** [comment]
FYI @henrikth93 we discussed that we're down to this one, #513 and #490 to then release the next version 😊

**Comment by henrikth93** [comment]
> FYI @henrikth93 we discussed that we're down to this one, #513 and #490 to then release the next version 😊

Alright! I am looking at it right now.

**Comment by andrewtavis** [comment]
Closed in #515 with a final change in da3cb6f 🚀 Thanks for the great work here, @henrikth93! 😊
