### ISSUE TITLE
About tab localizations don't have proper padding

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-iOS#518]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

The labels for table views within the About tab are directly at the right margin of the screen for right to left languages rather than being inline with the right edge of the table view. This is a bug for the Arabic localization of the app, and can be seen below:

![Simulator Screenshot - iPhone 16 Pro Max - 2024-11-30 at 14 18 40](https://github.com/user-attachments/assets/a7f8d375-f505-4d1c-b8f9-f2c721c5ee9e)

Ideally we would derive where padding can be added and conditionally add it.

Note that this is only for the About tab, but there was a similar issue for the Settings tab that was fixed via changes to `SettingsViewController.swift`. The structure of the About tab isn't the same though, so we can't use the same solution (potentially).

### Device type

iPhone and iPad

### Versions

Current development branch

**Comment by andrewtavis** [comment]
Closed by #521 🚀🚀🚀 Thanks for taking down such a key issue for us for your first PR :)

If you have interest in another issue, #517 would be great to get some help on, or aside from that please let us know what you'd find rewarding to work on!

**Comment by andrewtavis** [comment]
Closed by #521 🚀🚀🚀 Thanks for taking down such a key issue for us for your first PR, @victorsaccucci :)

If you have interest in another issue, #517 would be great to get some help on, or aside from that please let us know what you'd find rewarding to work on!

**Comment by victorsaccucci** [comment]
Thank you 😊! I just submitted a pull request for #517. I hope this helps!

**Comment by andrewtavis** [comment]
Awesome! Great to have you in the community 😊😊
